### PR TITLE
fix playlist of bilibili

### PR DESCRIPTION
**Pull request by ljhcage**
playlist option has always download the same file in bilibili, the bug is fixed now

### CODE REVIEW

**Comment by soimort** [comment]
Thanks for the PR -- fixed by #2614.

**Comment by fireattack** [comment]
This seems still broken. 

`you-get https://www.bilibili.com/video/av3803921/?p=2` will download p1, not p2 as expected.

**Comment by ljhcage** [comment]
@fireattack `you-get --playlist https://www.bilibili.com/video/av3803921/?p=2 ` will do

**Comment by ljhcage** [comment]
@fireattack the code in my own repo will do, which didn't merge into the master branch

**Comment by fireattack** [comment]
Yeah, that's what I was trying to say. #2614 didn't cover this PR's feature, at least not entirely.

**Comment by ljhcage** [comment]
@fireattack OK, I will pull a new PR as soon as possible, thanks

**Pull request closed without merging**
