### PR TITLE
Pandatv fix #1612

### LINKED ISSUE #1612: pandatv 熊猫直播流加了认证，大主播的房间extractors基本上都失效了
pandatv 熊猫直播流加了认证，大主播的房间基本上都失效了。但某些24小时播出的房间，特别（未知原因）房间，还可以用，比如这个： `http://www.panda.tv/491124` 

下面是失败信息（**注意，这个房间可能测试时下播了**），注意，最后一行 HTTP Error 403: Forbidden：

you-get --debug http://www.panda.tv/888888
Site:       panda.tv
Title:      JY:下午lol晚上狼人杀！
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Traceback (most recent call last):
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 762, in download_urls
    total_size = urls_size(urls, faker=faker, headers=headers)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 401, in urls_size
    return sum([url_size(url, faker=faker, headers=headers) for url in urls])
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 401, in <listcomp>
    return sum([url_size(url, faker=faker, headers=headers) for url in urls])
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 395, in url_size
    response = request.urlopen(url)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Downloading JY-下午lol晚上狼人杀！.flv ...
     %[========================================] 1/1you-get: version 0.4.595, a tiny downloader that scrapes the web.
you-get: ['http://www.panda.tv/888888']
Traceback (most recent call last):
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.595', 'console_scripts', 'you-get')()
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\__main__.py", line 92, in main
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 1414, in main
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 1327, in script_main
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 1143, in download_main
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 1407, in any_download
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\extractors\panda.py", line 30, in panda_download
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 785, in download_urls
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 477, in url_save
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\site-packages\you_get-0.4.595-py3.6.egg\you_get\common.py", line 395, in url_size
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Users\Uuz\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

### PR DESCRIPTION
**Pull request by Erk-**
I have made a fix for #1612.

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1613)

### CODE REVIEW

**Comment by Erk-** [comment]
Will work on it some more.

**Comment by Erk-** [comment]
@lamlam123tld3 in the latest commit I fixed it:
`while (pl_code_error and counter < len(data2["backup"])):`

**Comment by Erk-** [comment]
I have made it to use the api, so it is a lot cleaner.

**Comment by soimort** [comment]
Could you please rebase and squash commits into one? Thanks!

**Pull request closed without merging**
