### PR TITLE
Add metacafe support, fix #83

### LINKED ISSUE #83: [Support Request] Metacafe
- http://www.metacafe.com/watch/sy-1717373239001/p_nk_blow_me_one_last_kiss_official_music_video/

### PR DESCRIPTION
**Pull request by cnbeining**
Test:

```
$ python3 you-get http://www.metacafe.com/watch/10859352/angelina_jolie_wows_in_low_cut_camisole_in_hawaii_after_mastectomy/
Video Site: metacafe
Title:      Angelina Jolie Wows in Low-Cut Camisole in Hawaii After Mastectomy
Type:       MPEG-4 video (video/mp4)
Size:       7.73 MiB (8104213 Bytes)

Downloading Angelina Jolie Wows in Low-Cut Camisole in Hawaii After Mastectomy.mp4 ...
 16.2% (  1.2/7.7  MB) [=======                                 ] 1/1
```

Also fix readme's "/" issue by myself.

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/620)

### CODE REVIEW

**Comment by soimort** [comment]
Won't work for me.

```console
$ you-get -i http://www.metacafe.com/watch/mu-1142568/come_back_song_darius_rucker_music_video/
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get-develop/you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1028, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 915, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 807, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1021, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/metacafe.py", line 18, in metacafe_download
    url = unquote(url_raw)
UnboundLocalError: local variable 'url_raw' referenced before assignment
```

**Comment by cnbeining** [comment]
image

Maybe this thing is....just not working?

**Comment by soimort** [comment]
This video is perfectly playable on my side. Strangely, the video in #83 displayed the same error message "This Video cannot be played on this device" as you observed.

screenshot from 2015-09-03 23-42-01

**Comment by cnbeining** [comment]
The problem is related with the region.

I've used Canadian and US IP addresses, but still cannot watch it.

It could be possible to bypass this limit with XFF, but that's beyond the design of ```you-get```.

**Comment by soimort** [comment]
The point is, this video ([link](http://www.metacafe.com/watch/mu-1142568/come_back_song_darius_rucker_music_video/
)) can be streamed in my browser, but it throws a `UnboundLocalError` when I'm trying to download from the same region (while it shouldn't).

Or can you just give me a sample of video that works for you? I can test it on a US server.

**Comment by cnbeining** [comment]
Maybe you can try this one:

http://www.metacafe.com/watch/11372514/furious_petes_surprise_proposal_workout/

```
python3 you-get http://www.metacafe.com/watch/11372514/furious_petes_surprise_proposal_workout/
Video Site: metacafe
Title:      Furious Pete's Surprise Proposal Workout!!
Type:       MPEG-4 video (video/mp4)
Size:       11.21 MiB (11759003 Bytes)

Downloading Furious Pete's Surprise Proposal Workout!!.mp4 ...
```

**Comment by soimort** [comment]
Aha, this one's actually working... will look further into the matter later on.

**Comment by soimort** [comment]
:ok_hand:

**Pull request merged**
