### PR TITLE
Fix Bilibili 403 error

### PR DESCRIPTION
**Pull request by soimort**
1. Add `Referer` in both `url_info()` and `download_urls()`.
2. Specify the `Range` explicitly. 

Test links:
* http://www.bilibili.com/video/av10289657/
* http://www.bilibili.com/av10299156
* http://www.bilibili.com/av10354175

### CODE REVIEW

**Comment by rosynirvana** [comment]
```
./you-get -di 'http://www.bilibili.com/video/av10308208/'
[DEBUG] get_content: http://www.bilibili.com/video/av10308208/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=17030209&from=miniplay&player=1&sign=ba6299804af2fb71ead49c97baaedc15
[DEBUG] url_info: http://cn-zjwz-cu-v-09.acgvideo.com/vg2/5/85/17030209-1.flv?expires=1494095100&platform=pc&ssig=swoF68mv0UFhMyHIptPfyg&oi=_&nfa=zn2OTN7O9p3rqnr0+3S2RQ==&dynamic=1&hfa=2067713848
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://www.bilibili.com/video/av10308208/']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1440, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1351, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1153, in download_main
    download(url, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 1433, in any_download
    m.download(url, **kwargs)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/extractors/bilibili.py", line 187, in bilibili_download
    info_only=info_only)
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/extractors/bilibili.py", line 101, in bilibili_download_by_cid
    _, type_, temp = url_info(url, headers={'Referer': 'http://www.bilibili.com/'})
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 419, in url_info
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "/Users/Maxwellgoblin/misc/you-get/src/you_get/common.py", line 306, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

$ git pull upstream develop
From https://github.com/soimort/you-get
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
```

**Comment by soimort** [comment]
@soimort-bot Test this: http://www.bilibili.com/video/av10308208/

**Comment by rosynirvana** [comment]
Always send ```Range``` may break sohu
#1979

**Comment by xfengw** [comment]
you-get https://www.bilibili.com/video/av85767184?p=23 --debug
[DEBUG] get_content: https://www.bilibili.com/video/av85767184?p=23
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
you-get: version 0.4.1410, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av85767184?p=23'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xfeng\AppData\Local\Programs\Python\Python37\Scripts\you-get.exe\__main__.py", line 7, in <module>
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1766, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1654, in script_main
    **extra
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1310, in download_main
    download(url, **kwargs)
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1757, in any_download
    m.download(url, **kwargs)
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\site-packages\you_get\extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\site-packages\you_get\extractors\bilibili.py", line 171, in prepare
    initial_state = json.loads(initial_state_text)
  File "c:\users\xfeng\appdata\local\programs\python\python37\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Pull request merged**
