### PR TITLE
A semi-automatic way to download Youku videos.

### PR DESCRIPTION
**Pull request by love1st**
A semi-automatic way to download Youku videos.

### CODE REVIEW

**Comment by soimort** [comment]
This PR basically makes the youku extractor unusable *unless one has a ckey and can modify the source code*, thus it's unacceptable.

Please think of a better way doing this.

**Comment by shNanChen** [comment]
@love1st  能不能简单教1下，怎么在chrome中获取ckey

**Comment by love1st** [comment]
@shNanChen I also suggest you enabling HTML5 player for youku and you need only to find the request starting with **get.json?client_ip=192.168.1.2**. Ckey is in the related Request URL.
snipaste_20180326_220533

**Comment by shNanChen** [comment]
复制调试信息  最方便
image

**Comment by tcsp** [comment]
@love1st I find the ckey "107%23ssO5fwS9sn2XamFn6SHNXzy1XnIgg%2FCEXKh1w3nZtKZ5dw6F%2FQswDXd86%2BEqbul%2FXzIMHsR0KNJgbKT%2BCWUd%2Bw7h6WfqwE69g5Ywpvr7UzHftzp96zAwdCaED15Vkbmz%2BLXlENO4l8%2FEXFXFdkOy2yqk3cxl1dGIFdCBbWKEuYru3dTY2HTV793WucorE2GRed%2F2C3%2Fwrh%2FoCJpimpjAJjt8uTkDvpRIbcHmcYTCvqCIvmi3WH%2Fhijn83cfiDkdr8dE6drQro3i%2F3dl3jHOM2EqRu7oXfc53Z1iT38jxCC%2Blo7MSmKQMgpVAeds8Qv7pfDVmUeeeb%2FuqZgjCNfVkVp%2BQupmOUBIgcmyVwVlUGuhnGfQiklX4iQLPUZNuFZx9x1V%2FwO%2Bge%2FrxekVWBfpeVgHpegNOUm0BZDDBZzTZorF0e1yQ7QMB7EhHocbbfdcIFmYLwWEGuY%2Bl3dXj7jyV2yT6uxGWbKcRQFD7eu5%2FNA%2FEXF0%3D%23100", but it can not return the success response.

**Comment by tcsp** [comment]
@love1st firstly i try this url "https://ups.youku.com/ups/get.json?vid=XMTUwOTQ5MTQwOA==&ccode=0502&client_ip=192.168.1.1&utid=56dAE7CaPQQCAXygGxpja2Dz&client_ts=1522121197&ckey=107%23ssO5fwS9sn2XamFn6SHNXzy1XnIgg%2FCEXKh1w3nZtKZ5dw6F%2FQswDXd86%2BEqbul%2FXzIMHsR0KNJgbKT%2BCWUd%2Bw7h6WfqwE69g5Ywpvr7UzHftzp96zAwdCaED15Vkbmz%2BLXlENO4l8%2FEXFXFdkOy2yqk3cxl1dGIFdCBbWKEuYru3dTY2HTV793WucorE2GRed%2F2C3%2Fwrh%2FoCJpimpjAJjt8uTkDvpRIbcHmcYTCvqCIvmi3WH%2Fhijn83cfiDkdr8dE6drQro3i%2F3dl3jHOM2EqRu7oXfc53Z1iT38jxCC%2Blo7MSmKQMgpVAeds8Qv7pfDVmUeeeb%2FuqZgjCNfVkVp%2BQupmOUBIgcmyVwVlUGuhnGfQiklX4iQLPUZNuFZx9x1V%2FwO%2Bge%2FrxekVWBfpeVgHpegNOUm0BZDDBZzTZorF0e1yQ7QMB7EhHocbbfdcIFmYLwWEGuY%2Bl3dXj7jyV2yT6uxGWbKcRQFD7eu5%2FNA%2FEXF0%3D%23100" in chrome, then it works not ok.But when i just paste the ckey in the code and work it, it's ok.

**Comment by tcsp** [comment]
@love1st then i have another problem that is this ckey has expires? Should i exchange it in time?

**Comment by love1st** [comment]
@tcsp Sorry, I can't solve your problem. Maybe you can just use it in the python program. I'm not sure whether the ckey will expire, I've used this method for a few months, and I only changed ckey once.

**Comment by shNanChen** [comment]
@tcsp 视频开始播放后，右键就能出来这个菜单；我搞不太清楚是不是HTML5播放器之类的

**Comment by tcsp** [comment]
@love1st Thanks anyway.Recently i have a problem when i use you-get to download iqiyi videos such as this url "http://www.iqiyi.com/v_19rrhgbm04.html".Do you have some suggestions to solve it?If you have not encountered this problem or have no idea, just ignore my question.

**Comment by tcsp** [comment]
@shNanChen 公司只有休息时间才能看视频，所以刚才看不到-_-!现在看到了

**Comment by StLym** [comment]
@shNanChen 按照调试信息里面的ccode，改了youku.py，但是依旧客户端无权播放,201。目前只能使用0590，但是这个ccode没有1080p

**Comment by love1st** [comment]
@tcsp  I've tested several times. If we just paste "http://ups.youku.com/ups/get.json?client_ip=192.168.1.2......" in Chrome, we will receive 201 error. The reason is **Referer** field should be contained in the header of the request. I used Postman to simulate the request with **Referer** embedded in the header and got the right response. Youku.py has already taken **Referer** into consideration, so we can get what we want when using you-get.

**Comment by love1st** [comment]
@StLym  You may have to paste your ckey from the debug information in the youku.py. Changing ccode to 0502 without ckey is useless.

**Comment by love1st** [comment]
@shNanChen I’ve found that ckey isn't related to users. I pasted a ckey obtained when I logged out the account and it did work. Could you help us conduct some more test with this ckey "107%23ssOlJsS9sOIfcHx4BPRDXKF1lnIgg%2FCEXzT1TIQZmFFEx17p0%2Foz%2FFqhkrBWgzIMHsR0KNJgbKT%2BCWUdRaT7mWdXo9L4FqEdPVj5hTWSAstKUjYIs%2FosNSCXXQoNbKvNQXEXE1yAuqVx32EJ2Hy67TCLoxPql0obQmhWqYKauW%2BxodEj7HqDBgQgC5ShvpRIQDyVhP38uoCyhmg7WHOg%2BkCHu7JoE0UxcmhOtVe0htnpo6uLkyMi2T%2FktvZuv1PGDiOkqP9ZUMi%2F32r3iDiU7ErewQfFZ5fb0kMzt%2BtdGOV8ec%2BkgyC4m1HmGfNwlvmUaijuGSTtcP%2BRu9%2BAyHnbSmTVI553Q6JRIZQyhhqDbOLeUvVTygMA69i%2FI6a5vvBpZcVneUekc3lP3yVDyHVILDFLdgxDDkzcvvyXE8T4l8OJGum4PxODPyd%3D" ?

**Comment by StLym** [comment]
@love1st Thanks. It works.

**Pull request closed without merging**
