### PR TITLE
Can't download multipart video in Bilibili

### PR DESCRIPTION
**Pull request by kpwd**
tetsai@tetsai-NH50-70RA:/tmp/pyou-get https://www.bilibili.com/video/av8977143 --playlist --debug
[DEBUG] get_content: https://www.bilibili.com/video/av8977143
[DEBUG] get_content: https://www.bilibili.com/video/av8977143
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=14820815&otype=json&qn=80&quality=80&type=&sign=11864b9d7bf9c690fc70a58ffb7309a8
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=14820815&otype=json&qn=64&quality=64&type=&sign=8077207c25f79596c169bc4602706f74
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=14820815&otype=json&qn=32&quality=32&type=&sign=2a735c0e8729f87a13b460318e9d2573
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=14820815&otype=json&qn=16&quality=16&type=&sign=d9cc6fb02041a8dc8bc7264e93b3ab58
[DEBUG] get_content: http://comment.bilibili.com/14820815.xml
you-get: version 0.4.1388, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av8977143'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=True, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/home/tetsai/bin/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/tetsai/Git/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/tetsai/Git/you-get/src/you_get/common.py", line 1766, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/home/tetsai/Git/you-get/src/you_get/common.py", line 1654, in script_main
    **extra
  File "/home/tetsai/Git/you-get/src/you_get/common.py", line 1308, in download_main
    download_playlist(url, **kwargs)
  File "/home/tetsai/Git/you-get/src/you_get/common.py", line 1762, in any_download_playlist
    m.download_playlist(url, **kwargs)
  File "/home/tetsai/Git/you-get/src/you_get/extractors/bilibili.py", line 632, in download_playlist_by_url
    self.download(**kwargs)
  File "/home/tetsai/Git/you-get/src/you_get/extractor.py", line 209, in download
    stream_id = itags[0]
IndexError: list index out of range
tetsai@tetsai-NH50-70RA:/tmp/p$

### CODE REVIEW

**Comment by kpwd** [comment]
Main problem: json format has beeen change,make self.dash_streams become empty,look : 
biliblili.py 
488  if 'dash' in playinfo['data']:

no 'dash' in json data,so make  self.dash_streams empty,cuse:
stream_id = itags[0]
IndexError: list index out of range

**Comment by soimort** [comment]
Should be fixed by #2751.

**Comment by Soulwail** [comment]
This problem still exists.

**Comment by Core055** [comment]
Today I  have met this problem too , but yesterday  I can  even download the multipart video
So Could you please tell me how to solve this problem ??
In next version??

**Pull request closed without merging**
