### PR TITLE
Fix DouyuTV

### LINKED ISSUE #580: douyuTV 解析有错误
代码中用：
get_html("http://www.douyutv.com/api/client/room/"+room_id)
获取JSON 请求
实际上是
http://www.douyutv.com/swf_api/room/ + room_id + ?cdn=&nofan=yes&_t=xxx&sign=zzz

例如：
http://www.douyutv.com/swf_api/room/272097?cdn=&nofan=yes&_t=23966627&sign=6556f08f3fdd4d9d943a76bad5ea179a

但我不太清楚xxx和zzz是如何生成的，所以还请大家帮忙。

### PR DESCRIPTION
**Pull request by liushuyu**
Fix DouyuTV and close #580

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/631)

### CODE REVIEW

**Comment by zhangn1985** [comment]
好像不够好。有一部分页码还是会有crash。

**Comment by zhangn1985** [comment]
you-get http://www.douyutv.com/cms/zt/dmb.html
Traceback (most recent call last):
  File "/home/../source/you-get/you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/.../source/you-get/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/.../source/you-get/src/you_get/common.py", line 1049, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/.../source/you-get/src/you_get/common.py", line 934, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/.../source/you-get/src/you_get/common.py", line 826, in download_main
    download(url, **kwargs)
  File "/home/.../source/you-get/src/you_get/common.py", line 1042, in any_download
    m.download(url, **kwargs)
  File "/home/.../source/you-get/src/you_get/extractors/douyutv.py", line 18, in douyutv_download
    server_status = data.get('error',0)

**Comment by zhangn1985** [comment]
crash 的页面应该用playlist来实现。所以应该没问题。可以merge。

**Comment by soimort** [comment]
Merged. Thanks!

**Pull request closed without merging**
