### PR TITLE
icourse: add supprt

### LINKED ISSUE #1451: 希望添加对“爱课程网”的支持
这个网站好多好的课程，想离线下来寝室断网后看，希望能够支持，谢谢
视频链接：http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=51267&courseId=3622
如果能支持下面这种整个科目下载，就最好不过啦
科目链接：http://www.icourses.cn/coursestatic/course_3622.html

### PR DESCRIPTION
**Pull request by liushuyu**
Add support for iCourses

Should close #1451

**Known issues**
- Playlist download **ONLY** can originate from `http://www.icourses.cn/coursestatic/course_*.html` like sites
- Sometimes, the server will refuse the request due to high traffic (rush hour?)
- Sometimes, the request will fail due to poor network condition (but will retry)

---

This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1472)

### CODE REVIEW

**Comment by liushuyu** [comment]
In addition: I don't know how to use the new `VideoExtractor` Class... So the code is in a mess, please forgivme...

**Comment by liushuyu** [comment]
@cnbeining So you  have said you'll be able to review this... ?

**Comment by cnbeining** [comment]
I apologise(mainly due to my laziness) but it would be much easier if you rebase your commit si we can make your PR through the automatic tests.

Nice PR.

**Comment by liushuyu** [comment]
@cnbeining Rebased

**Comment by liushuyu** [comment]
@cnbeining Per #1477 , I found this annoying site has assigned different URLs to different chunks of the video (approx. 15 MB/chunk). So is there any way for `you-get` `download` module to do something like this?

**Comment by cnbeining** [comment]
Download-urls function would accept a list of URLs regardless the domains.

2016年10月24日星期一，liushuyu <notifications@github.com> 写道：

**Comment by liushuyu** [comment]
Pre-requirement: PR #1478 
Because this site requires to change URL (setting `Range` parameter will cause 403 Forbidden or 405 Not Allowed) when downloading different chunks of the video file

**Comment by liushuyu** [comment]
If everything works, this will close #1477

**Comment by soimort** [comment]
Any special reason to use `url_save_chunked` rather than `url_save`?
(The first one was intended for downloading data with chunked transfer encoding, if recall correctly. Based on my rough observation, this is not the case for icourses.cn. It has a conventional `Content-Length`:)

screenshot from 2016-11-03 00-09-03

**Comment by liushuyu** [comment]
>Any special reason to use `url_save_chunked` rather than `url_save`?
>(The first one was intended for downloading data with chunked transfer encoding, if I recall correctly. Based on my rough observation, this is not the case for icourses.cn. It has a conventional `Content-Length` :)

Well, if you try to use `wget` `curl` or something to download the video, you'll notice the server hang up (kill) the connection by force when you download approx. 15MB of data. A workaround in #1478 add some special functions to `url_save_chunked` (reason why is `url_save` is used by almost every other sites, so it may break everything if I modified that) to dynamically update URLs when downloaded chunk reaches 15 MB

>It has a conventional `Content-Length` :)

Yes and no, when you change the URL to try to seek the stream, you'll notice the `Content-Length` no longer rational. And `Range` parameter will cause server to return `405 Not Allowed`

**Comment by soimort** [comment]
LGTM, thanks!

**Comment by x2yline** [comment]
Thanks for the author's contributions, I have been looking for a way to get the video of icourse for several times, and it works well.

 But I still have problems in dowloading the ppts of icourse

I have try many times to download the ppts of icourse such as: http://www.icourses.cn/coursestatic/course_6701.html

I want to download the document in this page, and finally via extensions in chrome browser I got a swf file from:
http://file1.icourses.cn/process4/campus/processres/swf/2015/10/8/ff808081-4e17ed2a-0150-459dc552-57c2.swf
but it seems that no application can open it, so expecting the ppts support or docs support,

 Thanks!

**Comment by cnbeining** [comment]
Off topic:

You could try googling the course name and chances are they are provided
independently somewhere else.

a medical student <notifications@github.com>于2016年11月27日 周日上午3:10写道：

**Comment by x2yline** [comment]
Thanks for replying, and we have googled and also seach for it in baidu, but it's the only doc we can found on internet, our teacher tell us studying in icourse, but we have no way to download it,

**Comment by Bigzhangwei** [comment]
@x2yline 我照着@liushuyu的方法做了一遍还是不行，不知道是icourse更新了还是怎样？你好像会，不知道能不能教我一下，我也是生物狗

**Comment by x2yline** [comment]
@Bigzhangwei 有的可能是网络问题，这个我也不太懂，有时候多试几次换个网络环境就可以了

**Pull request merged**
