### PR TITLE
fix bug about renaming videos when downloading with ffmpeg

### PR DESCRIPTION
**Pull request by Yohohaha**
when i was downloading videos at iqiyi, i found the video name can't be renamed, the problem is supposed to be when downloading with ffmpeg, it hasn't dealed with the output_filename variable, i have fixed it and now it works well.

---

This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1424)

### CODE REVIEW

**Comment by Erk-** [comment]
Does this also fix #1409?

**Comment by soimort** [comment]
Please fix the syntax error and make sure this works on your local machine.

**Comment by Yohohaha** [comment]
It can work well on my pc, and it seems can fix #1409.

**Comment by Erk-** [comment]
@Yohohaha  you need a ":" on the end of line 972 in common.py it shoud be
`if(output_filename):` instead of `if(output_filename)`

**Comment by Yohohaha** [comment]
oh, thanks,

**Pull request closed without merging**
