### PR TITLE
[acfun]fix youku cloud source

### LINKED ISSUE #2043: acfun rc4 decode error
D:\Develop\Python\Scripts>you-get --debug -o  E:\               http://www.acfun.cn/v/ac3732437
[DEBUG] get_content: http://www.acfun.cn/v/ac3732437
[DEBUG] get_content: http://www.acfun.tv/video/getVideo.aspx?id=5216210
[DEBUG] get_content: http://aplay-vod.cn-beijing.aliyuncs.com/acfun/web?vid=592942c60cf23aef48cf522e&ct=85&ev=2&sign=1_1495885707_bc8c33e40d9bb11af6aa
ba6a3cd48c72
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3732437']
Traceback (most recent call last):
  File "d:\develop\python\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\develop\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Develop\Python\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\develop\python\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\develop\python\lib\site-packages\you_get\common.py", line 1467, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\develop\python\lib\site-packages\you_get\common.py", line 1378, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, capti
on=caption)
  File "d:\develop\python\lib\site-packages\you_get\common.py", line 1180, in download_main
    download(url, **kwargs)
  File "d:\develop\python\lib\site-packages\you_get\common.py", line 1460, in any_download
    m.download(url, **kwargs)
  File "d:\develop\python\lib\site-packages\you_get\extractors\acfun.py", line 122, in acfun_download
    **kwargs)
  File "d:\develop\python\lib\site-packages\you_get\extractors\acfun.py", line 73, in acfun_download_by_vid
    yk_streams = youku_acfun_proxy(info['sourceId'], info['encode'])
  File "d:\develop\python\lib\site-packages\you_get\extractors\acfun.py", line 25, in youku_acfun_proxy
    dec_text = rc4(b'2da3ca9e', enc_text).decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte

### PR DESCRIPTION
**Pull request by rosynirvana**
```
$ ./you-get -i http://www.acfun.cn/v/ac3498708 http://www.acfun.cn/v/ac2678901
Site:       AcFun.tv
Title:      各种宠物的错误打开方式 - ⑧月份的幻想酱
Type:       MPEG-4 video (video/mp4)
Size:       124.42 MiB (130468221 Bytes)

Site:       AcFun.tv
Title:      滑稽的宠物 - 柏斯布德绮姐
Type:       MPEG-4 video (video/mp4)
Size:       30.07 MiB (31534354 Bytes)
```
```
$ ./you-get -i http://www.acfun.cn/v/ac3627993
Site:       AcFun.tv
Title:      【日剧】月付百万的女人们 02 配信版【Melonpan字幕组】 - 慕藍zzz
Type:       MPEG-4 video (video/mp4)
Size:       289.78 MiB (303859436 Bytes)
```
2nd commit fix #2043
fixed: #2008 #1914 #1696
outdated: #1339 #1629

### CODE REVIEW

**Comment by kang0024** [comment]
你好，能把可覆盖文件发一下吗？ 我今天也下载不了acfun.cn，和上面的错误一样。谢谢！

**Comment by rosynirvana** [comment]
https://raw.githubusercontent.com/rosynirvana/you-get/da1339b0b035be7a176605295215d9ad2103d715/src/you_get/extractors/acfun.py

https://raw.githubusercontent.com/rosynirvana/you-get/da1339b0b035be7a176605295215d9ad2103d715/src/you_get/common.py

**Comment by kang0024** [comment]
出现错误：

you-get --debug http://www.acfun.cn/v/ac3020261_3
[DEBUG] get_content: http://www.acfun.cn/v/ac3020261_3
[DEBUG] get_content: http://www.acfun.tv/video/getVideo.aspx?id=4037333
[DEBUG] get_content: http://aplay-vod.cn-beijing.aliyuncs.com/acfun/web?vid=CNTUxMTI4MA==&ct=85&ev=3&sign=1_1497161645_67e04a4d5c2114ee45068d4669e88f12
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.cn/v/ac3020261_3']
Traceback (most recent call last):
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kang0024\AppData\Local\Programs\Python\Python36-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\acfun.py", line 122, in acfun_download
    **kwargs)
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\acfun.py", line 73, in acfun_download_by_vid
    yk_streams = youku_acfun_proxy(info['sourceId'], info['encode'])
  File "c:\users\kang0024\appdata\local\programs\python\python36-32\lib\site-packages\you_get\extractors\acfun.py", line 25, in youku_acfun_proxy
    dec_text = rc4(b'8bdc7e1a', enc_text).decode('utf8')
NameError: name 'rc4' is not defined

**Comment by rosynirvana** [comment]
```common.py```你没换吧

**Comment by kang0024** [comment]
换了。确切来说是本来就没有common.py这个文件，所以不是替换，是直接添加的。

**Comment by rosynirvana** [comment]
```
src/you_get/extractors/acfun.py
src/you_get/common.py
```
你找错路径了，```common.py```在extractors目录的上一层
没有```common.py```整个程序运行不了

**Comment by kang0024** [comment]
对我刚发现，囧。现在可以了，谢谢！

**Pull request merged**
