### PR TITLE
Fixed bilibili download 403 error

### PR DESCRIPTION
**Pull request by FSpark**
It's not just the UA's fault, because other browsers can access it successfully with the same UA. Add a Accept request-header and everything seems to work.

### CODE REVIEW

**Comment by FSpark** [comment]
@soimort P.s. Could you tell me what's problem with this commit https://github.com/soimort/you-get/pull/2699 ? I removed it this time, but I think it is really useful...🤔

**Comment by lxfly2000** [comment]
我这里试了并没有403错误啊

**Comment by FSpark** [comment]
> 我这里试了并没有403错误啊

一切正常？那还不好= = 昨天试了正常之后，发现是我之前就改过了UA，改回来就403了

**Comment by soimort** [comment]
> @soimort P.s. Could you tell me what's problem with this commit #2699 ? I removed it this time, but I think it is really useful...

Sorry about the delay in reviewing #2699. It looks good; see the comments there.

Meanwhile there's no need for reverting that commit in this PR. You could just create a separate branch for the intended commit c4d011b, otherwise please squash redundant commits into one.

**Comment by soimort** [comment]
Thanks for the PR!

**Comment by FSpark** [comment]
> > @soimort P.s. Could you tell me what's problem with this commit #2699 ? I removed it this time, but I think it is really useful...
> 
> Sorry about the delay in reviewing #2699. It looks good; see the comments there.
> 
> Meanwhile there's no need for reverting that commit in this PR. You could just create a separate branch for the intended commit [c4d011b](https://github.com/soimort/you-get/commit/c4d011b45d970b95c60dc29d116fdfc2e64d78f5), otherwise please squash redundant commits into one.

OK, I 'll pay attention next time. 😅

**Comment by FSpark** [comment]
> Never mind, it's just an invisible U+FEFF character.

It also bothered me for a while.😓

**Comment by tecog** [comment]
我在UA上后面加了个Heicore/1.0就好了233333

**Comment by chaserw** [comment]
今天，更新到最新版之后还是403 error，看了一下代码
`headers = {'Accept': '*/*', 'Accept-Language': 'en-US,en;q=0.5', 'User-Agent': ua}`
改为
`headers = {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'Accept-Language': 'en-US,en;q=0.5', 'User-Agent': ua}`
就可以正常用了

**Comment by Satonio1** [comment]
@chaserw Thanks，it is worked.So can you tell me why the old code will get the wrong #403?

**Comment by Satonio1** [comment]
@chaserw 谢谢，改完之后就好了。小白想请问什么这样会有效果呢？

**Comment by chaserw** [comment]
> @chaserw 谢谢，改完之后就好了。小白想请问什么这样会有效果呢？

可能对Accept的内容做了反爬吧，加上浏览器的Accept头之后就可以了

**Comment by sanbaideng** [comment]
改了还是一样 

> 今天，更新到最新版之后还是403 error，看了一下代码
> `headers = {'Accept': '*/*', 'Accept-Language': 'en-US,en;q=0.5', 'User-Agent': ua}`
> 改为
> `headers = {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'Accept-Language': 'en-US,en;q=0.5', 'User-Agent': ua}`
> 就可以正常用了

**Comment by overturncat** [comment]
> 改了还是一样
> 
> > 今天，更新到最新版之后还是403 error，看了一下代码
> > `headers = {'Accept': '*/*', 'Accept-Language': 'en-US,en;q=0.5', 'User-Agent': ua}`
> > 改为
> > `headers = {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'Accept-Language': 'en-US,en;q=0.5', 'User-Agent': ua}`
> > 就可以正常用了

你可以试试改一下bilibili.py 50行处的headers的代码
        headers = {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 
        'Accept-Language': 'en-US,en;q=0.5', 
        'User-Agent': ua , 
        'Cookie': "填自己的cookie", 
        'DNT': 1, 
        'Upgrade-Insecure-Requests': 1, 
        'Sec-Fetch-User': '?1', 
        'Sec-Fetch-Site': 'same-site', 
        'Sec-Fetch-Mode': 'navigate', 
        'Referer': 'https://search.bilibili.com/'

**Comment by Wickscc** [comment]
昨天晚上同样遇到了 403 错误的问题
只需要在 bilibili.py 的 headers = {'Accept': '*/*', 'Accept-Language': 'en-US,en;q=0.5', 'User-Agent': ua} 上添加 cookie 请求头即可

cookie 需要是自己的bilibili的请求cookie!

**Comment by mukerong** [comment]
正在下一个B站的playlist, 下了一半突然就报错了, 按照上面的方法也没修好, 试了youtube也是同样的错误, 不知道有没有什么解决方法

B站
```
you-get --debug 'https://www.bilibili.com/video/BV1wE411y75h?p=23'
[DEBUG] get_content: https://www.bilibili.com/video/BV1wE411y75h?p=23
you-get: version 0.4.1432, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/BV1wE411y75h?p=23'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/you-get", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1763, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1651, in script_main
    **extra
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1307, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1754, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractors/bilibili.py", line 180, in prepare
    initial_state = json.loads(initial_state_text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

YouTube
```
you-get --debug 'https://www.youtube.com/watch?v=GnmYR7j40W4&t=3s'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=GnmYR7j40W4&eurl=https%3A%2F%2Fy
you-get: version 0.4.1432, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=GnmYR7j40W4&t=3s'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/you-get", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1763, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1651, in script_main
    **extra
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1307, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1754, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractors/youtube.py", line 205, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}&eurl=https%3A%2F%2Fy'.format(self.vid)))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 439, in get_content
    response = urlopen_with_retry(req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 408, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
```

**Comment by outofcircle0** [comment]
> 正在下一个B站的playlist, 下了一半突然就报错了, 按照上面的方法也没修好, 试了youtube也是同样的错误, 不知道有没有什么解决方法
> 
> B站
> 
> ```
> you-get --debug 'https://www.bilibili.com/video/BV1wE411y75h?p=23'
> [DEBUG] get_content: https://www.bilibili.com/video/BV1wE411y75h?p=23
> you-get: version 0.4.1432, a tiny downloader that scrapes the web.
> you-get: Namespace(URL=['https://www.bilibili.com/video/BV1wE411y75h?p=23'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/bin/you-get", line 8, in <module>
>     sys.exit(main())
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/__main__.py", line 92, in main
>     main(**kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1763, in main
>     script_main(any_download, any_download_playlist, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1651, in script_main
>     **extra
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1307, in download_main
>     download(url, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1754, in any_download
>     m.download(url, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractor.py", line 48, in download_by_url
>     self.prepare(**kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractors/bilibili.py", line 180, in prepare
>     initial_state = json.loads(initial_state_text)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
>     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
> TypeError: the JSON object must be str, bytes or bytearray, not NoneType
> ```
> 
> YouTube
> 
> ```
> you-get --debug 'https://www.youtube.com/watch?v=GnmYR7j40W4&t=3s'
> [DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=GnmYR7j40W4&eurl=https%3A%2F%2Fy
> you-get: version 0.4.1432, a tiny downloader that scrapes the web.
> you-get: Namespace(URL=['https://www.youtube.com/watch?v=GnmYR7j40W4&t=3s'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1422, in connect
>     server_hostname=server_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
>     session=session
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/bin/you-get", line 8, in <module>
>     sys.exit(main())
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/__main__.py", line 92, in main
>     main(**kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1763, in main
>     script_main(any_download, any_download_playlist, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1651, in script_main
>     **extra
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1307, in download_main
>     download(url, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1754, in any_download
>     m.download(url, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractor.py", line 48, in download_by_url
>     self.prepare(**kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractors/youtube.py", line 205, in prepare
>     video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}&eurl=https%3A%2F%2Fy'.format(self.vid)))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 439, in get_content
>     response = urlopen_with_retry(req)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 408, in urlopen_with_retry
>     return request.urlopen(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
>     '_open', req)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1362, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1321, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
> ```

open finder-application-python3.7 and double click 「Install Certificates.command」

**Pull request closed without merging**
