### PR TITLE
fix youku's bug #450 #390 translate from LiuLang  monkey-videos

### PR DESCRIPTION
**Pull request by linhua55**
翻译的 LiuLang 的monkey-videos

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/463)

### CODE REVIEW

**Comment by soimort** [comment]
Thanks.

The new code raises a `TypeError` for some videos that cannot be streamed outside mainland China:

```
$ ./you-get -u --format=hd2 http://v.youku.com/v_show/id_XNTc2NDk2MDMy
you_get: [Warning] This video can only be streamed within Mainland China!
you_get: Use '-y' to specify a proxy server for extracting stream data.

Traceback (most recent call last):
  File "./you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 887, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 784, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractor.py", line 44, in download_by_url
    self.extract(**kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/youku.py", line 236, in extract
    m3u8+='?K='+ k
TypeError: Can't convert 'int' object to str implicitly
```

While the old one can still extract the source:
```
$ you-get -u --format=hd2 http://v.youku.com/v_show/id_XNTc2NDk2MDMy 
you_get: [Warning] This video can only be streamed within Mainland China!
you_get: Use '-y' to specify a proxy server for extracting stream data.

site:                优酷 (Youku)
title:               疯狂原始人（国语）
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          841.9 MiB (882788723 bytes)
    # download-with: you-get --format=hd2 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNTc2NDk2MDMy

    - lang:          英语
      download-url:  http://v.youku.com/v_show/id_XNTc3OTU5NzI4

    - lang:          粤语
      download-url:  http://v.youku.com/v_show/id_XNjg3NzM3ODcy

Real URLs:
['http://122.143.9.207/69732D68DDF4B82B164AC15558/0300011F0051D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://221.204.199.106/6772C7BB5B03982E1CB9652715/0300011F0151D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://175.22.3.210/6973F8C2694397621F0256CC2/0300011F0251D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://218.26.231.40/6572C7BB79E3C77966F8C3D87/0300011F0351D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://218.60.102.172/6773F8C2C54327CB69DDB4144/0300011F0451D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://103.224.233.50/67745E6F96A4D8448EB9D75E5F/0300011F0551D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://113.6.235.178/6573F8C2C554C73CA871B64E3/0300011F0651D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://175.22.3.141/677529C9B4830752593BD5D90/0300011F0751D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://221.204.194.205/6574C41CCED3982E1BB70D2DB8/0300011F0851D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://122.143.9.201/657529C95A44482702E13F3306/0300011F0951D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://221.203.1.202/65758F76F704083370AE323CE9/0300011F0A51D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://61.54.96.110/6575F52357C4C811B1BA2F5403/0300011F0B51D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv', 'http://60.211.205.13/6977F184C7A3B83159993B44C0/0300011F0C51D4A19EE14405CF07DD46D1E90B-DAB6-BA76-3252-99CDEB847AFF.flv']
```

Not sure why this happens, I'll look into this later. For now, if anyone needs this feature (and doesn't care about overseas usability), you can check out the [youku-full-video](https://github.com/soimort/you-get/tree/youku-full-video) branch.

**Comment by linhua55** [comment]
This video seems to have ip limitation.It gives me the string "抱歉，因版权原因无法观看此视频".
Thus the 'k' and 'k2' from the url 'http://v.youku.com/player/getPlayList/VideoIDS/XNTc2NDk2MDMy/Pf/4/ctype/12/ev/1'  are both '-1'.While the request need the k value.
>$ proxychains bash

>$ curl 'http://v.youku.com/player/getPlayList/VideoIDS/XNTc2NDk2MDMy/Pf/4/ctype/12/ev/1' | json_pp|grep error

    "error_code" : -26,
    "error" : "抱歉，因版权原因无法观看此视频！",
>$ curl 'http://v.youku.com/player/getPlayList/VideoIDS/XNTc2NDk2MDMy/Pf/4/ctype/12/ev/1' | json_pp|grep k

**Comment by soimort** [comment]
There are a few issues left in your code: First, it's no longer able to download password-protected videos; Second, while the old m3u8 method does extract metainfo of region-limited videos for oversea users, this one does not. (I was thinking if we can merge two methods together so if the `k.youku.com` method fails, you-get will fallback to the `pl.youku.com` one)

I'll look into this further when I catch a break (can't work with code these days).

**Comment by soimort** [comment]
need to bring back the handling of password-protected videos, then it'll be perfect :shipit:

**Comment by linhua55** [comment]
Ok,I'll re-try it.But for the Second,I think we can try direct connect to obtain the url.if fail,then use 'Ublock youku''s proxy.

**Comment by soimort** [comment]
For the 2nd point: it's not important now. As quite a lot of users complain about incomplete videos, we can stick with `k.youku.com`as long as it fixes the issue. The old m3u8 method is flawed, and I haven't yet figure out a way to extract all video segments from `pl.youku.com`. For simplicity, whether to use Unblock Youku's proxy (or another proxy) should be left to users to choose, we really shouldn't bother with that in `extractors/youku.py`.

**Comment by linhua55** [comment]
I think if we want to obtain full video segments from `pl.youku.com`,we should decompile youku's android app.

**Comment by linhua55** [comment]
Some tests:
URL:http://v.youku.com/v_show/id_XMTI2NTQyOTM1Mg==.html
PASSWORD:12345

URL:http://v.youku.com/v_show/id_XNDA2NjMyNjU2.html\?from\=y1.2-2.4.5
NOPASSWORD

URL:http://v.youku.com/v_show/id_XMTI1OTg4Nzk2MA==.html?from=y1.7-1.2
NOPASSWORD
URL:http://v.youku.com/v_show/id_XMTI1OTg4ODQxNg==.html?from=y1.7-1.2
PASSWORD:12345

**Comment by soimort** [comment]
I noticed a few edge cases not covered by the new approach (don't know if it's just me, but the old method seems to reach more videos)

Using this PR:
```
$ you-get http://v.youku.com/v_show/id_XMjU1NzMxODE2.html
you_get: Error
```

Using develop branch:
```
$ you-get http://v.youku.com/v_show/id_XMjU1NzMxODE2.html
site:                优酷 (Youku)
title:               第001话 天才篮球手!诞生
stream:
    - format:        mp4
      container:     mp4
      video-profile: 高清
      size:          91.2 MiB (95653457 bytes)
    # download-with: you-get --format=mp4 [URL]

Downloading 第001话 天才篮球手!诞生.mp4 ...
  0.8% (  0.8/91.2 MB) [                                        ] 1/4^C%
```

I'll keep tracking this issue. (I do use you-get for Youku myself, that's why I'm conservative about any change...)

**Comment by linhua55** [comment]
This video has region limitation too.But the error_code doesn't be tackled.And the unblock youku's proxy "proxy.uku.im:8888"  doesn't  work.You can find some useful proxys on http://www.proxy.com.ru/

Thanks for your patient.

**Comment by soimort** [comment]
No, it's not about religion limits or proxies at all (my IP is located in mainland China) - the video is not downloadable by this PR (or can you do it on your side?),  while it should be, as the old code still does job.

**Comment by linhua55** [comment]
Yes,this PR works well on my side.And it works on my vpn with proxy.

**Comment by soimort** [comment]
It seems the video is no longer region limited anymore.

**Comment by zhangn1985** [comment]
事实上“http://v.youku.com/v_show/id_XMjU1NzMxODE2.html”， 这个url所指的视频，报告出来的就是版权问题。
所以，硬要fix，只有请出原算法了做backup了。
当 k = -1时，直接break，然后调用原算法。

**Comment by soimort** [comment]
两种算法各有限制。现有算法存在某些视频下载不完整的问题；新算法能下载完整，但是有一部分旧算法能解析的视频完全解析不了（个人推测是因为旧算法调用的是优酷移动端的接口，受到的地域限制比浏览器端的新算法更少）。因为这个原因，目前我还不能把这个branch merge进来。

screenshot from 2015-10-04 22-29-52

**Comment by sceext2** [comment]
如果 `you-get` 能够实现多种解析方法共存, 解析时让用户选择一个 (并且设置默认方法) 就好了.

**Comment by yan12125** [comment]
Use the new API first, and fallback to the old API if failed?

**Comment by linhua55** [comment]
This method is useless due to youku's change.

**Comment by soimort** [comment]
We'll see how to get things right for the new Youku API. Thanks for the PR, anyway!

**Comment by linhua55** [comment]
Thanks to @zhangn1985 .It come back.
@yan12125   It works for now.
2015-11-30

**Comment by zhangn1985** [comment]
居然能这样！！！！服了。

**Comment by zhangn1985** [comment]
https://github.com/soimort/you-get/pull/463#issuecomment-115289104 所示问题已经不存在了，因为那个视频已经404了

**Comment by soimort** [comment]
Would you mind rebasing these commits to squash them into one? It's impossible to see what changes you've made compared to the original code; the diff is almost impossible to review.

Please don't add irrelevant files to your commit; also, don't commit conflict indication lines like `<<<<<<< HEAD`. Thanks.

**Comment by linhua55** [comment]
@soimort 
Ok,Would you mind tell me how to rebase?

**Comment by soimort** [comment]
You may see https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits on how to squash your Git commits. However, I can imagine there are a lot of conflicts against the latest `develop` in your current branch. If you feel unable to resolve them, I suggest that you do it the simple way:

1. Close this PR.
2. Create a new feature branch (for example, `youku-fix`) based on the `HEAD` of the current `develop`. (It is not advisable to use your own `develop` to create PRs, unless you just want to do a one-time PR.)
3. Make necessary changes and commit them.
4. Open a new PR.

**Comment by linhua55** [comment]
What about to delete my fork linhua55/you-get.And refork yours.If so,Will these conversation in this pull request  disappear.

**Comment by soimort** [comment]
Yes, you can do that, but there is really no need to delete a fork and fork it again. `git branch -u upstream/develop` will just let you track the remote `develop` branch.

**Comment by linhua55** [comment]
Thanks.

**Pull request closed without merging**
