### PR TITLE
Bilibili video download failed

### PR DESCRIPTION
**Pull request by Ultraliyue**
you-get https://www.bilibili.com/video/av43488517 --debug

[DEBUG] url_locations: https://www.bilibili.com/video/av43488517
[DEBUG] get_content: https://www.bilibili.com/video/av43488517
[DEBUG] get_content: http://interface.bilibili.com/v2/playurl?appkey=84956560bc028eb7&cid=76212702&otype=xml&qn=116&quality=116&type=&sign=e5bc9abfdc62204b4336b7d680bda905
you-get: version 0.4.1205, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av43488517'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ultra\AppData\Local\Programs\Python\Python37-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\common.py", line 1653, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\common.py", line 1541, in script_main
    **extra
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\common.py", line 1276, in download_main
    download(url, **kwargs)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\common.py", line 1644, in any_download
    m.download(url, **kwargs)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\extractors\bilibili.py", line 167, in prepare
    self.entry(**kwargs)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\extractors\bilibili.py", line 227, in entry
    self.download_by_vid(cid, re.search('bangumi', self.url) is not None, **kwargs)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\extractors\bilibili.py", line 104, in download_by_vid
    self.parse_bili_xml(api_xml)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\extractors\bilibili.py", line 86, in parse_bili_xml
    stream_type, container = self.bilibili_stream_type(urls_list)
  File "c:\users\ultra\appdata\local\programs\python\python37-32\lib\site-packages\you_get\extractors\bilibili.py", line 47, in bilibili_stream_type
    url = urls[0]
IndexError: list index out of range

### CODE REVIEW

**Comment by xdstack** [comment]
Same problem

**Comment by wang-ye** [comment]
seems they changed the appkey. Could not come up with a working solution though

**Comment by Ultraliyue** [comment]
> 

I think so. When I downloaded Bilibili video in January, it was success.

**Comment by Ultraliyue** [comment]
> seems they changed the appkey. Could not come up with a working solution though

I think so. When I downloaded Bilibili video in January, it was success.

**Comment by soimort** [comment]
687474703a2f2f7468656361746170692e636f6d2f6170692f696d616765732f6765743f666f726d61743d73726326747970653d676966

**Comment by Giagoo** [comment]
same problem,did you solve the problem?if you did,please tell me,thanks

**Comment by Xrunes** [comment]
I pulled this request in Febrary, the reason is that Bilibili changed the appkey, soon after they update the "you-get" to solved this problem. But now can't download it anymore, the estimated reason is also appkey update. So, waiting for the update should be fine.🤔

**Comment by Xrunes** [comment]
> same problem,did you solve the problem?if you did,please tell me,thanks

I pulled this request in Febrary, the reason is that Bilibili changed the appkey, soon after they update the "you-get" to solved this problem. But now can't download it anymore, the estimated reason is also appkey update. So, waiting for the update should be fine.🤔

**Comment by codeyu7** [comment]
#it failed again
不知道咋测试，所以没有发 pr

C:\Windows\system32>you-get https://www.bilibili.com/video/av16332211?p=40 --debug
[DEBUG] get_content: https://www.bilibili.com/video/av16332211?p=40
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
you-get: version 0.4.1355, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av16332211?p=40'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\qi\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\qi\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Qi\AppData\Local\Programs\Python\Python37\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\qi\appdata\local\programs\python\python37\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\qi\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1758, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\qi\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1646, in script_main
    **extra
  File "c:\users\qi\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1302, in download_main
    download(url, **kwargs)
  File "c:\users\qi\appdata\local\programs\python\python37\lib\site-packages\you_get\common.py", line 1749, in any_download
    m.download(url, **kwargs)
  File "c:\users\qi\appdata\local\programs\python\python37\lib\site-packages\you_get\extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\qi\appdata\local\programs\python\python37\lib\site-packages\you_get\extractors\bilibili.py", line 169, in prepare
    initial_state = json.loads(initial_state_text)
  File "c:\users\qi\appdata\local\programs\python\python37\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by wangbar0133** [comment]
C:\Users\Administrator>you-get https://www.bilibili.com/video/av92152716
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\Users\Administrator>you-get https://www.bilibili.com/video/av92152716 --debug
[DEBUG] get_content: https://www.bilibili.com/video/av92152716
you-get: version 0.4.1410, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av92152716'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\common.py", line 1766, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\common.py", line 1648, in script_main
    download_main(
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\common.py", line 1310, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\common.py", line 1757, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\extractors\bilibili.py", line 171, in prepare
    initial_state = json.loads(initial_state_text)
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

系统是windows sever 2016，但在虚拟机和win10上一切正常

**Comment by zhegexiankabutaileng** [comment]
> C:\Users\Administrator>you-get https://www.bilibili.com/video/av92152716
> you-get: [error] oops, something went wrong.
> you-get: don't panic, c'est la vie. please try the following steps:
> you-get: (1) Rule out any network problem.
> you-get: (2) Make sure you-get is up-to-date.
> you-get: (3) Check if the issue is already known, on
> you-get: https://github.com/soimort/you-get/wiki/Known-Bugs
> you-get: https://github.com/soimort/you-get/issues
> you-get: (4) Run the command with '--debug' option,
> you-get: and report this issue with the full output.
> 
> C:\Users\Administrator>you-get https://www.bilibili.com/video/av92152716 --debug
> [DEBUG] get_content: https://www.bilibili.com/video/av92152716
> you-get: version 0.4.1410, a tiny downloader that scrapes the web.
> you-get: Namespace(URL=['https://www.bilibili.com/video/av92152716'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
> Traceback (most recent call last):
> File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Scripts\you-get.exe__main__.py", line 9, in File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get__main__.py", line 92, in main main(**kwargs) File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\common.py", line 1766, in main script_main(any_download, any_download_playlist, **kwargs) File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\common.py", line 1648, in script_main download_main( File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\common.py", line 1310, in download_main download(url, **kwargs) File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\common.py", line 1757, in any_download m.download(url, **kwargs) File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\extractor.py", line 48, in download_by_url self.prepare(**kwargs) File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\you_get\extractors\bilibili.py", line 171, in prepare initial_state = json.loads(initial_state_text) File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\json__init__.py", line 341, in loads
> raise TypeError(f'the JSON object must be str, bytes or bytearray, '
> TypeError: the JSON object must be str, bytes or bytearray, not NoneType
> 
> 系统是windows sever 2016，但在虚拟机和win10上一切正常

我也是在server2016上报错说 the JSON object must be str, bytes or bytearray, not NoneType。在Windows10上正常

**Comment by jrww33** [comment]
C:\WINDOWS\system32>you-get https://www.bilibili.com/video/BV1754y1n7Xe
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

C:\WINDOWS\system32>
C:\WINDOWS\system32>you-get https://www.bilibili.com/video/BV1754y1n7Xe --debug
[DEBUG] get_content: https://www.bilibili.com/video/BV1754y1n7Xe
you-get: version 0.4.1527, a tiny downloader that scrapes the web.
you-get: Namespace(version=False, help=False, info=False, url=False, json=False, no_merge=False, no_caption=False, force=False, skip_existing_file_size_check=False, format=None, output_filename=None, output_dir='.', player=None, cookies=None, timeout=600, debug=True, input_file=None, password=None, playlist=False, first=None, last=None, size=None, auto_rename=False, insecure=False, http_proxy=None, extractor_proxy=None, no_proxy=False, socks_proxy=None, stream=None, itag=None, URL=['https://www.bilibili.com/video/BV1754y1n7Xe'])
Traceback (most recent call last):
  File "c:\users\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\AppData\Local\Programs\Python\Python39\Scripts\you-get.exe\__main__.py", line 7, in <module>
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\you_get\common.py", line 1813, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\you_get\common.py", line 1695, in script_main
    download_main(
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\you_get\common.py", line 1327, in download_main
    download(url, **kwargs)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\you_get\common.py", line 1804, in any_download
    m.download(url, **kwargs)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\you_get\extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\you_get\extractors\bilibili.py", line 192, in prepare
    initial_state = json.loads(initial_state_text)
  File "c:\users\appdata\local\programs\python\python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Face this same issue again since a few days ago. Does anyone face it too?

**Review by Liuhaier — COMMENTED** [review]
【bilibili】查看画质时，DEFAULT不显示4K画质
image

**Pull request closed without merging**
