### PR TITLE
fix load_cookies local name error

### LINKED ISSUE #2351: 无法加载cookies,从0.4.900开始
Please make sure these boxes are checked before submitting your issue – thank you!

- [√] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [√] Your `you-get` is up-to-date.
- [√] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [√] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [√] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [√] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [√] 您的`you-get`为最新版.
- [√] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [√] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [√] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]
C:\Users\Administrator\Desktop>you-get -c "C:\Users\Administrator\Desktop\niconico cookies.txt" http://www.nicovideo.jp/watch/sm31910935 -i --debug
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1077, in load_cookies
    cookies = cookiejar.MozillaCookieJar(a)
NameError: name 'a' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.909', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1362, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1226, in script_main
    load_cookies(args.cookies)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1082, in load_cookies
    con = sqlite3.connect(a)
NameError: name 'a' is not defined

### PR DESCRIPTION
**Pull request by lilydjwg**
I've also run pylint so there should not be more obvious errors like this one.

fixes #2351

### CODE REVIEW

**Comment by lilydjwg** [comment]
The Python 3.2 test has errored without reason.

**Comment by soimort** [comment]
`json` is used implictly by many extractors (which do not import `json` but import `common` instead):
- `yinyuetai.py`
- `tudou.py`
- `sina.py`
- `imgur.py`
- `twitter.py`
- `dailymotion.py`
- `instagram.py`
- `douban.py`
You cannot remove this from `common.py`.

**Comment by lilydjwg** [comment]
Oh....I've removed that commit.

**Comment by lilydjwg** [comment]
Travis-CI doesn't send mails for failed pr?...

**Pull request merged**
