### PR TITLE
[bilibili] enable choozing first to download by using "--first"

### PR DESCRIPTION
**Pull request by chasemao**
Hi, I tried to use "--first" to download in bilibili from certain episode, but I found "--first" didn't work. I saw similar commit here [https://github.com/soimort/you-get/pull/2815](url). I tried to add a few lines to make it work. But I am not familiar with python, not sure if it is right or not. It would be great if it works.

### CODE REVIEW

**Comment by ljhcage** [comment]
Try you-get --playlist http://bilibiliurl?p=2, it will start from 2nd p.

**Comment by DOCCA0** [comment]
I found same wrong when I use youtube 
`you-get -l "https://www.youtube.com/watch?v=Xgp_-uwpLyc&list=PL8dwc8wQyToz8sa_1OduXSwiwqJVw7kx6&index=103" -o "E:\projects\吉他365" -x 127.0.0.1:1080 -first 103`
but it is start at episode 1

**Comment by otomn** [comment]
PR submitted #2884

**Comment by Qy20** [comment]
hi,i am able to dowload the youku video,but i can't download the bilibili video! It reported that " you-get: [error] oops, something went wrong."Can you give me a solution?

**Pull request closed without merging**
