### PR TITLE
修复西瓜视频获取不到video id和title的问题

### PR DESCRIPTION
**Pull request by xiaohutushen30**

### CODE REVIEW

**Comment by soimort** [comment]
Thanks :+1:

**Comment by wavebit** [comment]
西瓜视频无法下载的问题仍然存在
这是测试连接https://www.ixigua.com/cinema/album/80xdqPnCPdO_80YAxVmL7Ri/

**Comment by feixia5712** [comment]
我这边也是无法下载
[root@localhost ~]# you-get "https://www.ixigua.com/i6803238245686627584/"
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
Site:       ixigua.com
[root@localhost ~]#

**Comment by theThreeKingdom** [comment]
python '3.8.2'
you-get '0.4.1456'
url https://www.ixigua.com/6879740483174662158/

I got a program error，as follows:
Error
Traceback (most recent call last):
  File "D:\working\Python\Python382\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "D:\working\Python\Python382\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\working\Python\Python382\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "E:\nixin\improve\python\you-get\tests\test_ixigua.py", line 7, in test_ixigua
    ixigua.download('https://www.ixigua.com/6879740483174662158/', info_only=True)
  File "E:\nixin\improve\python\you-get\src\you_get\extractors\ixigua.py", line 93, in ixigua_download
    conf = loads(match1(html, r"window\.config = (.+);"))
  File "D:\working\Python\Python382\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by fengyun21** [comment]
我这边也是没法下载西瓜视频


you-get https://www.ixigua.com/6993139705197888031 --debug
you-get: version 0.4.1536, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.ixigua.com/6993139705197888031'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, first=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, last=None, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, size=None, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Users/twan/Library/Python/3.8/bin/you-get", line 8, in <module>
    sys.exit(main())
  File "/Users/twan/Library/Python/3.8/lib/python/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/twan/Library/Python/3.8/lib/python/site-packages/you_get/common.py", line 1831, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/Users/twan/Library/Python/3.8/lib/python/site-packages/you_get/common.py", line 1713, in script_main
    download_main(
  File "/Users/twan/Library/Python/3.8/lib/python/site-packages/you_get/common.py", line 1345, in download_main
    download(url, **kwargs)
  File "/Users/twan/Library/Python/3.8/lib/python/site-packages/you_get/common.py", line 1822, in any_download
    m.download(url, **kwargs)
  File "/Users/twan/Library/Python/3.8/lib/python/site-packages/you_get/extractors/ixigua.py", line 89, in ixigua_download
    for c in resp.getheader('Set-Cookie').split("httponly,"):
AttributeError: 'NoneType' object has no attribute 'split'

**Pull request merged**
