### PR TITLE
修复douyutv_video_download

### PR DESCRIPTION
**Pull request by OwO1**
douyutv video download failed

### CODE REVIEW

**Comment by willshion** [comment]
40140140401 烦
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by aetherwu** [comment]
When would this fix release to the Master?

**Comment by JaydenFish** [comment]
you-get.exe www.douyu.com/90016 --debug
[DEBUG] get_content: https://m.douyu.com/room/90016
[DEBUG] get_content: http://www.douyutv.com/api/v1/room/532152?aid=wp&client_sys=wp&time=1556799391&auth=47c390e6991a4b9b31fd52ecab21c4b4
[DEBUG] HTTP Error with code401
[DEBUG] HTTP Error with code401
[DEBUG] HTTP Error with code401
you-get: version 0.4.1295, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['www.douyu.com/90016'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 1733, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 1621, in script_main
    **extra
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 1284, in download_main
    download(url, **kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 1724, in any_download
    m.download(url, **kwargs)
  File "d:\anaconda3\lib\site-packages\you_get\extractors\douyutv.py", line 61, in douyutv_download
    content = get_content(json_request_url, headers)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 434, in get_content
    response = urlopen_with_retry(req)
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 412, in urlopen_with_retry
    raise http_error
  File "d:\anaconda3\lib\site-packages\you_get\common.py", line 403, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "d:\anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "d:\anaconda3\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\anaconda3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "d:\anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "d:\anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by heartaotime** [comment]
401 401

**Comment by e788b1** [comment]
https://github.com/hr3lxphr6j/bililive-go

`
bililive --native-flv-parser -o ~/Downloads/douyu -i https://www.douyu.com/12345
`

**Pull request closed without merging**
