### PR TITLE
reset url and vid when download in serial

### PR DESCRIPTION
**Pull request by zhangn1985**
you-get URL1 URL2 时，如果URL1和URL2是同一个网站，并且这个网站的解析是用VidoeExtractor来实现的。
download_by_url 不会更新vid，vid总是第一个链接的vid。
所以必须重置vid.
同理download_by_vid不会更新url。

to fix https://github.com/soimort/you-get/issues/906

**(请将本内容完整替换为PULL REQUEST的详细内容)**

when use xxx_download_by_url(url1/url2)
vid will not reset, only first url will download

Signed-off-by: Zhang Ning <zhangn1985@gmail.com>

---
This change is [Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/977)

### CODE REVIEW

**Comment by soimort** [comment]
Looks fine, not sure why you closed it.

I maybe need to look further into #906 (and #498) though, since I never succeed in reproducing that bug myself...

**Comment by zhangn1985** [comment]
I don't know why... I can explain why it is closed..

**Comment by soimort** [comment]
I'm slow on merging PRs, especially when it touches some common parts which might affect all extractors; if I don't find enough time/bandwidth to review actual code and try on real videos, I just leave it open so other people may want to test or comment on it.

So please be more patient and allow me some days to process a PR: )

**Comment by soimort** [comment]
Thanks!

**Pull request merged**
