### PR TITLE
Fix bug: unable get video title

### PR DESCRIPTION
**Pull request by Ensteinjun**
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=ZTwBlWGHRRE&eurl=https%3A%2F%2Fy
[DEBUG] STATUS: ok
you-get: version 0.4.1314, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=ZTwBlWGHRRE'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Users/mingjun.luo/anaconda3/bin/you-get", line 10, in <module>
    sys.exit(main())
  File "/Users/mingjun.luo/anaconda3/lib/python3.7/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Users/mingjun.luo/anaconda3/lib/python3.7/site-packages/you_get/common.py", line 1759, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/Users/mingjun.luo/anaconda3/lib/python3.7/site-packages/you_get/common.py", line 1647, in script_main
    **extra
  File "/Users/mingjun.luo/anaconda3/lib/python3.7/site-packages/you_get/common.py", line 1303, in download_main
    download(url, **kwargs)
  File "/Users/mingjun.luo/anaconda3/lib/python3.7/site-packages/you_get/common.py", line 1750, in any_download
    m.download(url, **kwargs)
  File "/Users/mingjun.luo/anaconda3/lib/python3.7/site-packages/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/Users/mingjun.luo/anaconda3/lib/python3.7/site-packages/you_get/extractors/youtube.py", line 210, in prepare
    self.title = parse.unquote_plus(video_info['title'][0])
KeyError: 'title'

### CODE REVIEW

**Comment by algorithmx** [comment]
same problem here:

run command
`you-get --debug https://www.youtube.com/watch?v=Ybzuya2Yc1w`

result

`
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=Ybzuya2Yc1w&eurl=https%3A%2F%2Fy
[DEBUG] STATUS: ok
you-get: version 0.4.1314, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=Ybzuya2Yc1w'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/home/dabajabaza/anaconda3/bin/you-get", line 10, in <module>
    sys.exit(main())
  File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/common.py", line 1759, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/common.py", line 1647, in script_main
    **extra
  File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/common.py", line 1303, in download_main
    download(url, **kwargs)
  File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/common.py", line 1750, in any_download
    m.download(url, **kwargs)
  File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 210, in prepare
    self.title = parse.unquote_plus(video_info['title'][0])
KeyError: 'title'
`

**Comment by Ensteinjun** [comment]
> same problem here:
> 
> run command
> `you-get --debug https://www.youtube.com/watch?v=Ybzuya2Yc1w`
> 
> result
> 
> ```
> [DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=Ybzuya2Yc1w&eurl=https%3A%2F%2Fy
> 
> [DEBUG] STATUS: ok
> you-get: version 0.4.1314, a tiny downloader that scrapes the web.
> you-get: Namespace(URL=['https://www.youtube.com/watch?v=Ybzuya2Yc1w'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
> Traceback (most recent call last):
>  
>  File "/home/dabajabaza/anaconda3/bin/you-get", line 10, in <module>
>     sys.exit(main())
>   
> File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
>     main(**kwargs)
>   
> File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/common.py", line 1759, in main
>     script_main(any_download, any_download_playlist, **kwargs)
>   
> File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/common.py", line 1647, in script_main
>     **extra
>   
> File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/common.py", line 1303, in download_main
>     download(url, **kwargs)
>   
> File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/common.py", line 1750, in any_download
>     m.download(url, **kwargs)
>   
> File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/extractor.py", line 48, in download_by_url
>     self.prepare(**kwargs)
>  
> File "/home/dabajabaza/anaconda3/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 210, in prepare
>     self.title = parse.unquote_plus(video_info['title'][0])
> 
> KeyError: 'title'
> ```

You can try this patch. it should be able to fix this bug.

**Comment by ElfSundae** [comment]
Same here, @Ensteinjun  👍 this patch works well, thanks.

**Comment by zszen** [comment]
same

**Comment by soimort** [comment]
Thanks! :+1:

**Pull request merged**
