### PR TITLE
fix issue about KeyError: 'url_encoded_fmt_stream_map'

### PR DESCRIPTION
**Pull request by chonpsk**
It looks like working well.
#2755 tested.

### CODE REVIEW

**Comment by chonpsk** [comment]
well, I don't know why I edited youtube.py but it failed on imgur.

**Comment by chonpsk** [comment]
Cuz two times failed on different environment but also imgur I think there is something wrong on imgur. Maybe the checker should be changed.

**Comment by Gelma** [comment]
Thanks a lot. Fixed the problem to me also

**Comment by soimort** [comment]
Great job. Thanks!

**Pull request merged**
