### PR TITLE
Fix Baidu Cloud support

### PR DESCRIPTION
**Pull request by liushuyu**
Can download Baidu Cloud shares.
What works in this fix:
- Can download single file (w/ or w/o password) from Baidu Cloud Disk sharing

Known limitations:
- Can't bypass CAPTCHAs
- Cookies with login information is needed when downloading videos and some special :tm: files.
- Can't batch download a folder of files (will trigger errors)

Sorry for getting this so late and somewhat incomplete, I apologize

I remembered some issues relating to this, but I can't remember now.

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1461)

### CODE REVIEW

**Comment by soimort** [comment]
Looks good. Any demo links for testing?

**Comment by liushuyu** [comment]
> Looks good. Any demo links for testing?

http://pan.baidu.com/s/1bpC8AHx
Password: j94t

**Comment by cnbeining** [comment]
Hi,

It seems that you are trying to implement 2 major refractions in one commit. (common.py & baidu.py)

I am suggesting you to commit those 2 changes in different commits so your PR can be reviewed faster, without leaving confusions to the future contributors.

Again, thanks for your work.

Cheers,

**Comment by liushuyu** [comment]
Update: Split the commit into two commits

**Comment by soimort** [comment]
That's cool. Thanks for the fix! :+1:

**Comment by Edenharder** [comment]
Baidu Cloud下载失效了

```
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```

**Pull request merged**
