### PR TITLE
add heighlight print API

### PR DESCRIPTION
**Pull request by minghu6**
**Provide Color Support for all kinds of shell Stdout**
*(include cmd ,powershll in Windows and sh, bash in Linux)*
 main API :

     color.color_dict    color- function dictionary
     color.print_map    map print(as follow) to color

     color.print_info                         print Common Information
     color.print_ok                           print Succeed Information
     color.print_warn or print_warning        print Warinng Information
     color.print_err or print_error           print Error Information

     You can also configure them with color_dict and print_map

[Exp1 in cmd ](http://photo.163.com/a19678zy/#m=2&aid=302654401&pid=9604961012)
[Exp2 in bash](http://photo.163.com/a19678zy/#m=2&aid=302654401&pid=9604961012)

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1177)

### CODE REVIEW

**Comment by minghu6** [comment]
失误，说明文档还没写完就提交了

**Comment by soimort** [comment]
Thanks for your contribution, but I wonder why it is worth spending so much effort on coloring output; that's not even the focus of this project. More importantly: too many rich colors will sometimes make the text hard to read, since different users may have quite different terminal backgrounds. A set of colors that looks good on dark background may look unreadable on light background, et vice versa.  That's why I'm conservative on this.

Also, please: No Chinese in the source code. **All comments should be written in simple, easy-to-read English.** (unless it's a proper noun refers to non-English name, e.g. `优酷`)

Furthermore, if you have doubts about some pieces of code, or if you think something in the existing code might have a mistake, such like:

```diff
+#恕我愚昧，看不懂上面的语句，极度怀疑是：
+sys.path.insert(1, _filepath)
+sys.path.insert(1, _srcdir)
```

Please always open an issue to ask us first (for example #1135) or a **separate PR** to explain why this should be changed, instead of inserting these questioning words in the source code and sending them as a pull request. We can't merge these things.

**Comment by minghu6** [comment]
Explain Why I need pay attention to 'heighlight':

First, plain text are ugly especially in cmd of my windows
(You Don't Know ,When you use your deal zesh)

Second, about issue "A set of colors that looks good on dark background may look unreadable on light background" , We can pre-establish all kind of Theme,such as all-blank-theame to solve it.

Third, actually only four kind of soft color can be used.But I understand that you get bored with too much code,even there is only 4 api

actually, "but I wonder why it is worth spending so much effort on coloring output; that's not even the focus of this project." irritate me.

I don't know what is the project focus on,Maybe Hack's Tecnology? :(
 
I wonder why you should said It's a waste of time, other than give reason and reject directly.

 The latter is professional response and the former is a slap

Anyway ,It's Your Code, you can do anything.But Do NOT behave as there is a team to Supply Support ,Please. Only you have ssh-key didnt you?

**Comment by cnbeining** [comment]
I also have the SSH key.

Your pull request shall be denied due to the following reasons:

- This PR is not following the code style of the project.

- This PR is polluting the commit log

- This PR is not directly related to its original objection

- This PR does not respect the fact that it is an international project

- This PR is unfinished

More importantly,

- You are insulting us the project collaborators. 

Thus your PR shall not be merged.

**Comment by soimort** [comment]
**(TL;DR just read the last two paragraphs.)**

> First, plain text are ugly especially in cmd of my windows

Fair enough, and I *know* it looks ugly on Windows' cmd, because I had to package this software and test it on a Windows box from time to time. But essentially, *everything looks ugly* on `cmd`.

> We can pre-establish all kind of Theme,such as all-blank-theame to solve it.

Theming is beyond the current scope of this project. Personally I like your idea of implementing themes (I have other open-source project that involves some form of theming, e.g. [translate-shell](https://github.com/soimort/translate-shell/wiki/Themes)), but I would rather not to do it in `you-get` prematurely.

> But I understand that you get bored with too much code,even there is only 4 api

More code means we are obliged to **maintain them**. So it's not just about the API.

Making a one-time, big patch is easy for any trained programmer to do, but no one can guarantee they are perfect in the first place, and chasing bugs caused by someone else's code is not really a nice experience. You'll understand it someday: Simplicity of maintenance is much, much more important than just adding fancy, unnecessary stuff infinitely.

> actually, "but I wonder why it is worth spending so much effort on coloring output; that's not even the focus of this project." irritate me.

I'm sorry if it irritated you, but let me stress this advice again: (also to future contributors) **If you wish to make a significant change to the project (perhaps to any well-known open-source project), always ask the maintainers and discuss about it first.** If you know what kind of changes should be allowed, you won't feel bad after spending a lot of time, only working on something the project owner doesn't want.

> I don't know what is the project focus on

This project mainly focuses on pulling videos (sometimes other interesting stuff) from the web, I assume you already knew that. If you can pick one of [existing issues](https://github.com/soimort/you-get/issues) and fix that, you're more than welcome! (we have a hell lot of extractors broken at this moment)

Actually I would suggest you to publish your code here on PyPI as an individual library, so anyone who wants to use these coloring functions in their project can add your library as a dependency. That could benefit the whole Python community, and we are free of the overhead to maintain them in `you-get`. What do you think?

> Anyway ,It's Your Code, you can do anything.But Do NOT behave as there is a team to Supply Support ,Please.

Yes, it is **our** code (all 70 contributors'), although I wrote the most part and have the final say (simply because I own this repository). And you're also right, there is no team to supply support, because nobody is getting paid to do that. Everyone (even myself) is volunteering their free time to contribute to this project.

> Only you have ssh-key didnt you?

Then I'm not sure what that means. Technically everyone has "an SSH-key" on GitHub.

If you mean "_write access_", then [Top 3 contributors on the list](https://github.com/soimort/you-get/graphs/contributors) are all project collaborators who can push to this repository. They helped me a lot on explaining things, fixing issues I'm not able (or don't care) to fix, reviewing other peoples' Pull Requests and merging commits by their own judgment. Please, DO NOT ignore them.

---

I understand that it is bitter to get your first Pull Request rejected, but this is just how things work (in open source). I have code that I've written then thrown away myself (because they're too complicated, unnecessary, I have no intent to maintain...), so it's not really a big deal, and there's no point to overreact on the denial of a pull request at all.

Again, thank you for taking your time. You're very welcome if you want to start by contributing something small (which doesn't take you too much time, but still helpful to everyone). And I hope our words didn't hurt your feelings anyway. We are harsh sometimes, that's because we want to keep the right things on track.

Cheers!

**Pull request closed without merging**
