### PR TITLE
fix acfun(letv cloud src)

### PR DESCRIPTION
**Pull request by jackyzy823**
for #525

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/528)

### CODE REVIEW

**Comment by zhjawe** [comment]
这个问题修复了么？可是我更新了git发现问题依旧啊

**Comment by zhjawe** [comment]
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "C:\Users\Administrator\you-get\src\you_get\__main__.py", line 91, in mai
n
    main()
  File "C:\Users\Administrator\you-get\src\you_get\common.py", line 1001, in mai
n
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Users\Administrator\you-get\src\you_get\common.py", line 893, in scri
pt_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "C:\Users\Administrator\you-get\src\you_get\common.py", line 785, in down
load_main
    download(url, **kwargs)
  File "C:\Users\Administrator\you-get\src\you_get\common.py", line 994, in any_
download
    m.download(url, **kwargs)
  File "C:\Users\Administrator\you-get\src\you_get\extractors\acfun.py", line 12
6, in acfun_download
    acfun_download_by_vid(p_vid, p_title, output_dir=output_dir, merge=merge, in
fo_only=info_only ,**kwargs)
  File "C:\Users\Administrator\you-get\src\you_get\extractors\acfun.py", line 67
, in acfun_download_by_vid
    info = json.loads(get_content("http://jiexi.acfun.info/index.php?vid={}".for
mat(vid)))
  File "C:\Users\Administrator\you-get\src\you_get\common.py", line 177, in get_
content
    response = request.urlopen(req)
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by zhjawe** [comment]
感觉换了个错法

**Comment by jackyzy823** [comment]
@zhjawe . since this pr have not been merged,you may try `git clone -b fix-acfun-letvcloud https://github.com/jackyzy823/you-get/` to test.

**Comment by cnbeining** [comment]
The ```uu``` of Letvcloud from Acfun & Bilibili (and some other sites) have to be used with its own site now.

This should require one more argument(```uu```) beed added to the function of Letvcloud(in letv.py), which would lead to greater changes.

I would suggest that a estimation beed done before this change.

P.S: There's no chance that ```jiexi.acfun.info``` be avalable again. We can remove those junk code.

**Comment by jackyzy823** [comment]
#534 is better. `uu` should be belong to sites using letvcloud api. so i close this pr.

**Pull request closed without merging**
