### PR TITLE
ixigua.com : Title Extract Failure

### PR DESCRIPTION
**Pull request by fy8207345**
Title Extract Failure

### CODE REVIEW

**Comment by theThreeKingdom** [comment]
python 3.8.2
you-get 0.4.1456
test url  https://www.ixigua.com/6879740483174662158/

I got a program error , as follows:
Error
Traceback (most recent call last):
  File "D:\working\Python\Python382\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "D:\working\Python\Python382\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "D:\working\Python\Python382\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "E:\nixin\improve\python\you-get\tests\test_ixigua.py", line 7, in test_ixigua
    ixigua.download('https://www.ixigua.com/6879740483174662158/', info_only=True)
  File "E:\nixin\improve\python\you-get\src\you_get\extractors\ixigua.py", line 93, in ixigua_download
    conf = loads(match1(html, r"window\.config = (.+);"))
  File "D:\working\Python\Python382\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by fy8207345** [comment]
> python 3.8.2
> you-get 0.4.1456
> test url https://www.ixigua.com/6879740483174662158/
> 
> I got a program error , as follows:
> Error
> Traceback (most recent call last):
> File "D:\working\Python\Python382\lib\unittest\case.py", line 60, in testPartExecutor
> yield
> File "D:\working\Python\Python382\lib\unittest\case.py", line 676, in run
> self._callTestMethod(testMethod)
> File "D:\working\Python\Python382\lib\unittest\case.py", line 633, in _callTestMethod method() File "E:\nixin\improve\python\you-get\tests\test_ixigua.py", line 7, in test_ixigua ixigua.download('https://www.ixigua.com/6879740483174662158/', info_only=True) File "E:\nixin\improve\python\you-get\src\you_get\extractors\ixigua.py", line 93, in ixigua_download conf = loads(match1(html, r"window.config = (.+);")) File "D:\working\Python\Python382\lib\json__init__.py", line 341, in loads
> raise TypeError(f'the JSON object must be str, bytes or bytearray, '
> TypeError: the JSON object must be str, bytes or bytearray, not NoneType

The website changed the source code, you may extract if yourself. sorry.

**Comment by ouy160** [comment]
python 3.8.3
you-get 0.4.1488
test url https://www.ixigua.com/6879740483174662158/

I got a program error , as follows:
you-get https://www.ixigua.com/6879740483174662158/ --debug

you-get: version 0.4.1488, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.ixigua.com/6879740483174662158/'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "e:\path\anaconda_x64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\path\anaconda_x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Path\anaconda_x64\Scripts\you-get.exe\__main__.py", line 7, in <module>
  File "e:\path\anaconda_x64\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "e:\path\anaconda_x64\lib\site-packages\you_get\common.py", line 1799, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "e:\path\anaconda_x64\lib\site-packages\you_get\common.py", line 1681, in script_main
    download_main(
  File "e:\path\anaconda_x64\lib\site-packages\you_get\common.py", line 1328, in download_main
    download(url, **kwargs)
  File "e:\path\anaconda_x64\lib\site-packages\you_get\common.py", line 1790, in any_download
    m.download(url, **kwargs)
  File "e:\path\anaconda_x64\lib\site-packages\you_get\extractors\ixigua.py", line 89, in ixigua_download
    for c in resp.getheader('Set-Cookie').split("httponly,"):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by hoangduyloc** [comment]
@fy8207345 @ouy160 @theThreeKingdom 
Hello there, are you able to download the video from ixigua now? if yes, kindly help me to figure out the problem.
Thankyou!.

**Pull request closed without merging**
