### PR TITLE
Bar finetune

### PR DESCRIPTION
**Pull request by lilydjwg**
see the commits for more info.

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/898)

### CODE REVIEW

**Comment by soimort** [comment]
1. I'm not quite sure what this PR achieves. Can you please elaborate this a little bit by attaching a screenshot?
2. Your solution overflows the bar near the end of the downloading progress. (`bar_size` should be kept consistent)

screenshot from 2016-01-24 03-45-06

**Comment by soimort** [comment]
Shrinking 42 to 38 doesn't look good, too.

**42** was chosen because it's the answer given by the following calculation:

```console
100.0% (999.9/999.9MB) ├████████████████████████████████████████┤[99/99] 1000 MB/s
|0                   24|                                        |0             18|
```

`24 + 18 = 42`.

Of course it won't fit videos larger than 1GB or that consist of more than 99 pieces, or even net speed faster than 9999MBps. But in practice, 42 is the best number we'd have. :satisfied:

**Comment by lilydjwg** [comment]
The link in the first commit has over 300 pieces so it behaves like the buggy "eta" version of wget. It shouldn't overflow, or change during the process. I'll look into why shortly.

**Comment by lilydjwg** [comment]
Here's the screenshot you asked for:


I've fixed the issue you've seen. I forgot about `self.bar_size` in other places.

**Comment by soimort** [comment]
Well, I did not expect Letv could have a 3-digit number of pieces (#606 needs to be solved); in that case it all makes sense then.

**Comment by soimort** [comment]
Thanks!

**Comment by soimort** [comment]
I had to revert this (temporarily), as I'm still seeing the overflowing bar everywhere on large-sized videos (> 1GB). 

screenshot from 2016-02-04 19-39-39

Please free free to reopen.

**Comment by soimort** [comment]
Will changing `38` simply to a bigger value work for you? (your solution works better for Letv videos with 100+ pieces, though)

**Comment by lilydjwg** [comment]
I'll come up with a patch ensuring all variable-size parts don't get too
large later.
2016年2月5日 上午8:08，"Mort Yao" <notifications@github.com>写道：

**Pull request merged**
