### PR TITLE
[real PR not issue] fixing the problem for some of bilibili videos: best quality lost

### PR DESCRIPTION
**Pull request by mo-han**
It's a real PR with contributing code. Please don't simply close it.
This PR is tested on my side already.
The description and explanation are in the modified code already.
It's just a temporary fix but the cause is found and confirmed, you can do some improvements instead of my code, if you want.

### CODE REVIEW

**Comment by mo-han** [comment]
@Qiuchi0918 
Hi, thanks for the review.
I'm a little bit familiar with python, but very unfamiliar with this project, even just the bilibili module.
The difficulty came from two side: first, this project has messy code (well, but hell mess but still hard to understand, especially those long method such like `prepare_by_url`); second, the web site and API of bilibili is not managed by us, nor controlled by us.
I have made a self-using modified version, it works pretty good, you can try it if you like:
https://github.com/mo-han/mo-han-toolbox/blob/master/mylib/bilibili.py

**Comment by Qiuchi0918** [comment]
@mo-han Ahh thanks.  I was forced to read outstream from you-get in my downloader to acquire source of actual best quality. With your modification, this might no longer be necessary. I’ll give it a try later.
感谢 :D

**Comment by soimort** [comment]
@soimort-bot test this https://www.bilibili.com/video/BV1Wv411678n

**Comment by soimort** [comment]
@mo-han I'm not sure which best quality is missing here (the output from the current `develop` is as shown above). Could you provide a more specific case?

**Comment by mo-han** [comment]
@soimort 
sry, but really couldn't.
it was long before, details and related URLs are faded in memory.
code modification in this commit is not perfect.
maybe it's not good idea to merge this one.

however, still prefer my own [modified version](https://github.com/mo-han/mo-han-toolbox/blob/master/mylib/bilibili.py), which gets rid of the following issues:
- streams sorted by size rather than resolution, while sometimes bilibili produces videos with size of 720p bigger than 1080p (it may be bilibili's fault but i have to change the code)
- sometimes the condition line `if current_quality is None or qn < current_quality:` cause 1080p60 1080p+ streams lost, i don't know why but after bypassing this if code, issue gone

**Comment by NoNova7** [comment]
@mo-han 
Hello, have you  fixed the issue that bilibili api do not return the [1080P+ 高码率] option? I notice that this particularly  happened to some old videos that initially only support 1080P and Bilibili add the 1080P+ option later. The modified one from you can detect [dash-hdflv2 高清 1080P+] with -i but still unable to download. 
Also notice that: the 1080P+ with newest videos have H265 encoding, while the old videos that added 1080P+ later have the H264 encoding. The link you mentioned above is invalid and I cannot access it. 
感谢.

**Comment by mo-han** [comment]
@NoNova7 
the link is out-dated because i changed repo files' names occasionally
the repo path is `mo-han/mo-han-toolbox`
the bilibili lib file path is `mylib/site_bilibili.py`
for now won't edit that link url in last comment because maybe someday it will be invalid again

i simply replaced a "if" line from `if current_quality is None or qn < current_quality:` to `if True:`
which makes VIP quality streams always detectable (didn't notice any fail until now)
since it's detected then it's able to download, unless the target stream is not selected by default
by default you-get choose the "best" stream, which is stream with largest size actually
however sometimes the highest level "quality" stream is not the biggest sized one
i personally met few videos with 720p as the biggest size stream (1080p{60,+} is smaller)
in such cases, you-get sort streams by size from large to small, resulting into lower quality stream sorted on top and downloaded by default
i changed its sort method from "size first" to "quality/resolution/stream_id first"
i hadn't come across aforesaid issues since then (but i'm not 100% sure if this is your case)

you-get choose HEVC stream over AVC ones
i like this feature and didn't touch its code (never dig into that)

there's another bilibili downloader (not developed by me) which is promising:
http://github.com/lifegpc/bili
its author has done great job on parsing almost all kinds of resouces on bilibili site, and succeeds to provide all kinds of downloading features
i don't use it because i don't need it yet

hope this helps

**Pull request closed without merging**
