### PR TITLE
解决QQ部份解析，有些vid获取到了undefined

### PR DESCRIPTION
**Pull request by chenxiangfang**
https://v.qq.com/x/page/d0552xbadkl.html 这一类QQ源
解析出来的vid是undefined

### CODE REVIEW

**Comment by liuhuancom** [comment]
有的链接可以下载有的不能 比如下面这个就报错
you-get https://v.qq.com/x/page/j053249gxyw.html --debug
[DEBUG] get_content: https://v.qq.com/x/page/j053249gxyw.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=j053249gxyw
[DEBUG] get_content: http://vv.video.qq.com/getkey?otype=json&platform=11&format=2&vid=j053249gxyw&filename=j053249gxyw.p2.1.mp4&appver=3.2.19.333
you-get: check vid&filename failed

**Comment by chenxiangfang** [comment]
@liuhuancom # 这个问题是另外一个bug了，这个pull request解决的是拿到vid是错误的。

**Comment by Carson126** [comment]
download speed so slowly， any tips？

**Comment by wangxianjing** [comment]
@chenxiangfang "@liuhuancom # 这个问题是另外一个bug了，这个pull request解决的是拿到vid是错误的。"请问下这个另外的问题现在确定是啥问题了吗？有解码？

**Comment by seahog004** [comment]
似乎腾讯视频都解析不了了

C:\Users\Administrator>you-get -i https://v.qq.com/x/page/j053249gxyw.html --deb
ug
[DEBUG] get_content: https://v.qq.com/x/page/j053249gxyw.html
[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333
&platform=11&defnpayver=1&vid=undefined
you-get: version 0.4.1040, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://v.qq.com/x/page/j053249gxyw.html'], auto_rename
=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None
, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False
, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filen
ame=None, password=None, player=None, playlist=False, socks_proxy=None, stream=N
one, timeout=600, url=False, version=False)
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts
\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.1040', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1617, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1506, in script_main
    **extra
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1241, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\common.py", line 1608, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\qq.py", line 161, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\sit
e-packages\you_get\extractors\qq.py", line 16, in qq_download_by_vid
    fn_pre = video_json['vl']['vi'][0]['lnk']
KeyError: 'vl'

C:\Users\Administrator>

**Comment by seahog004** [comment]
`if 'mp.weixin.qq.com/s' in url:
        content = get_content(url)
        vids = matchall(content, [r'\?vid=(\w+)'])
        for vid in vids:
            qq_download_by_vid(vid, vid, output_dir, merge, info_only)
        return
`
后面加一段
`    if 'v.qq.com/x/page' in url:
        vids = matchall(url, [r'page/(\w+).html'])
        for vid in vids:
            qq_download_by_vid(vid, vid, output_dir, merge, info_only)
        return
`
暂时解决问题

**Comment by LittleRed-YXC** [comment]
@liuhuancom 看看 #2595 ，能否解决你的问题

**Comment by LittleRed-YXC** [comment]
@liuhuancom @wangxianjing @chenxiangfang "you-get: check vid&filename failed" 这类问题已经解决，参考这里： #2595

**Comment by suertang** [comment]
下载腾讯视频分段，能否下载指定段？比如 加一个参数 sections=1-20。如果不加就全部下载。

**Pull request closed without merging**
