### PR TITLE
[douyu]use new api

### PR DESCRIPTION
**Pull request by steven7851**
from https://gist.github.com/spacemeowx2/629b1d131bd7e240a7d28742048e80fc
#1720

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1734)

### CODE REVIEW

**Comment by zhangn1985** [comment]
it works

**Comment by qzane** [comment]
@steven7851 
line 44: `server_status = data.get('error',0)` should be changed to `data = server_status.loads(content).get('error',0)`

**Comment by qzane** [comment]
travis-ci的测试看不懂啊，为什么挂在了youtube的测试用例上...

**Comment by soimort** [comment]
Thanks! 👍

**Pull request merged**
