### PR TITLE
del \t symbol of youku title

### PR DESCRIPTION
**Pull request by xyuanmu**
Sometimes youku video with \t symbol in title, such as this http://v.youku.com/v_show/id_XNzA5ODMxMzY0.html
```
you-get -c yk.txt http://v.youku.com/v_show/id_XNzA5ODMxMzY0.html

It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
you-get: Found cna in imported cookies. Use it
site:                优酷 (Youku)
title:               第四集 家常        地道泡菜鱼搭配泡菜的专属美味
stream:
    - format:        mp4hd3
      container:     mp4
      video-profile: 1080P
      size:          1097.0 MiB (1150336001 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNzA5ODMxMzY0&type=mp4hd3v3&ups_client_netip=78ef1e87&utid=f8UgFN
m1QwUCAXjvHpl1RBOF&ccode=0502&psid=e1274aee11e234d95cd45f2a5fb85fb1&ups_userid=1543367023&ups_ytid=1543367023&duration=2879&expi
re=18000&drm_type=1&drm_device=7&ups_ts=1538973785&onOff=0&encr=0&ups_key=ef05286120117fd61607778974b1c098
    # download-with: you-get --format=mp4hd3 [URL]

Downloading 第四集 家常         地道泡菜鱼搭配泡菜的专属美味.mp4 ...
 0.0% (   0.0/1097.0MB) ├────────────────────────────────────┤[ 1/21] you-get: [error] oop
s, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```

### CODE REVIEW

**Comment by soimort** [comment]
I believe the issue has nothing to do with `\t`.

**Comment by xyuanmu** [comment]
@soimort 
```
you-get -d -c yk.txt http://v.youku.com/v_show/id_XNzA5ODMxMzY0.html

t seems that your ffmpeg is a nightly build.
lease switch to the latest stable if merging failed.
ou-get: Found cna in imported cookies. Use it
DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XNzA5ODMxMzY0&ccode=0519&client_ip=192.168.1.1&utid=f8UgFNm1QwUCA
jvHpl1RBOF&client_ts=1539409092
ite:                优酷 (Youku)
itle:               第四集 家常        地道泡菜鱼搭配泡菜的专属美味
tream:
   - format:        mp4hd3
     container:     mp4
     video-profile: 1080P
     size:          1097.0 MiB (1150336001 bytes)
     m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XNzA5ODMxMzY0&type=mp4hd3v3&ups_client_netip=78ef1ebf&utid=f8U
FNm1QwUCAXjvHpl1RBOF&ccode=0519&psid=04e53490d4c78dc40e2afaafb4a5c9ef&ups_userid=1543367023&ups_ytid=1543367023&duration=287
&expire=18000&drm_type=1&drm_device=0&ups_ts=1539409085&onOff=0&encr=0&ups_key=0d1ca1255a74ef68740d611e682a1bdd
   # download-with: you-get --format=mp4hd3 [URL]

ownloading 第四集 家常         地道泡菜鱼搭配泡菜的专属美味.mp4 ...
0.0% (   0.0/1097.0MB) ├────────────────────────────────────┤[ 1/21] you-get: version
.4.1011, a tiny downloader that scrapes the web.
ou-get: Namespace(URL=['http://v.youku.com/v_show/id_XNzA5ODMxMzY0.html'], cookies='yk.txt', debug=True, extractor_proxy=Non
, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=Fals
, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_pr
xy=None, stream=None, timeout=600, url=False, version=False)
raceback (most recent call last):
 File "E:\Documents\GitHub\you-get\you-get", line 11, in <module>
   you_get.main(repo_path=_filepath)
 File "E:\Documents\GitHub\you-get/src\you_get\__main__.py", line 92, in main
   main(**kwargs)
 File "E:\Documents\GitHub\you-get/src\you_get\common.py", line 1583, in main
   script_main(any_download, any_download_playlist, **kwargs)
 File "E:\Documents\GitHub\you-get/src\you_get\common.py", line 1472, in script_main
   **extra
 File "E:\Documents\GitHub\you-get/src\you_get\common.py", line 1216, in download_main
   download(url, **kwargs)
 File "E:\Documents\GitHub\you-get/src\you_get\common.py", line 1574, in any_download
   m.download(url, **kwargs)
 File "E:\Documents\GitHub\you-get/src\you_get\extractors\youku.py", line 308, in youku_download_by_url
   Youku().download_by_url(url, **kwargs)
 File "E:\Documents\GitHub\you-get/src\you_get\extractor.py", line 59, in download_by_url
   self.download(**kwargs)
 File "E:\Documents\GitHub\you-get/src\you_get\extractor.py", line 228, in download
   av=stream_id in self.dash_streams)
 File "E:\Documents\GitHub\you-get/src\you_get\common.py", line 911, in download_urls
   headers=headers, **kwargs
 File "E:\Documents\GitHub\you-get/src\you_get\common.py", line 680, in url_save
   with open(temp_filepath, open_mode) as output:
SError: [Errno 22] Invalid argument: '.\\第四集 家常 \t地道泡菜鱼搭配泡菜的专属美味[00].mp4.download'
```

**Comment by soimort** [comment]
Is your `E:` on FAT32 or exFAT? The character `\t` should be well supported by NTFS, by specification.

If so, we'd better add it to [`legitimize` in `util.fs`](https://github.com/soimort/you-get/blob/develop/src/you_get/util/fs.py#L5) as a general solution instead.

**Comment by xyuanmu** [comment]
@soimort file system is NTFS, Windows, doesn't support \t in filename

**Comment by soimort** [comment]
I was able to reproduce the exception on a mounted FAT disk, but not on NTFS : (

The issue should be fixed now. Thanks for reporting this.

**Comment by tian-yuyang** [comment]
How to download the cookies like your yk.txt? @xyuanmu

**Comment by xyuanmu** [comment]
> How to download the cookies like your yk.txt? @xyuanmu

export by Get cookies.txt extension

**Pull request closed without merging**
