### PR TITLE
Youtube HTTP Error with code404

### PR DESCRIPTION
**Pull request by CLY88**
`I:\YoutuDown>you-get -x 127.0.0.1:10809 -o 暮らしの道具店_VFbsp_lRJk4 https://www.youtube.com/watch?v=VFbsp_lRJk4 --debug
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=VFbsp_lRJk4&eurl=https%3A%2F%2Fy
[DEBUG] HTTP Error with code404
[DEBUG] HTTP Error with code404
[DEBUG] HTTP Error with code404
you-get: version 0.4.1520, a tiny downloader that scrapes the web.
you-get: Namespace(version=False, help=False, info=False, url=False, json=False, no_merge=False, no_caption=False, force=False, skip_existing_file_size_check=False, format=None, output_filename=None, output_dir='暮らしの道具店_VFbsp_lRJk4', player=None, cookies=None, timeout=600, debug=True, input_file=None, password=None, playlist=False, first=None, last=None, size=None, auto_rename=False, insecure=False, http_proxy='127.0.0.1:10809', extractor_proxy=None, no_proxy=False, socks_proxy=None, stream=None, itag=None, URL=['https://www.youtube.com/watch?v=VFbsp_lRJk4'])
Traceback (most recent call last):
  File "d:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python39\Scripts\you-get.exe\__main__.py", line 7, in <module>
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\common.py", line 1813, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\common.py", line 1695, in script_main
    download_main(
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\common.py", line 1327, in download_main
    download(url, **kwargs)
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\common.py", line 1804, in any_download
    m.download(url, **kwargs)
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\extractors\youtube.py", line 198, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}&eurl=https%3A%2F%2Fy'.format(self.vid)))
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\common.py", line 439, in get_content
    response = urlopen_with_retry(req)
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\common.py", line 417, in urlopen_with_retry
    raise http_error
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\you_get\common.py", line 408, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\program files\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "d:\program files\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "d:\program files\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "d:\program files\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "d:\program files\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "d:\program files\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

**Proxy checked ,works fine, can vist youtube and google.**
Success downloaded at May 16th.

### CODE REVIEW

**Comment by elalemanyo** [comment]
@CLY88  I am also getting the same error, did you find a solution?

**Comment by songds** [comment]
C:\Users\songds>you-get -i 'https://www.youtube.com/watch?v=jNQXAC9IVRw' --debug
[DEBUG] get_location: http://'https://www.youtube.com/watch?v=jNQXAC9IVRw'
[DEBUG] get_location: http://'https://www.youtube.com/watch?v=jNQXAC9IVRw'
you-get: version 0.4.1520, a tiny downloader that scrapes the web.
you-get: Namespace(version=False, help=False, info=True, url=False, json=False, no_merge=False, no_caption=False, force=False, skip_existing_file_size_check=False, format=None, output_filename=None, output_dir='.', player=None, cookies=None, timeout=600, debug=True, input_file=None, password=None, playlist=False, first=None, last=None, size=None, auto_rename=False, insecure=False, http_proxy=None, extractor_proxy=None, no_proxy=False, socks_proxy=None, stream=None, itag=None, URL=["'https://www.youtube.com/watch?v=jNQXAC9IVRw'"])
Traceback (most recent call last):
  File "d:\programs\python\python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "d:\programs\python\python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\programs\python\python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\programs\python\python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\programs\python\python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "d:\programs\python\python39\lib\http\client.py", line 948, in send
    self.connect()
  File "d:\programs\python\python39\lib\http\client.py", line 919, in connect
    self.sock = self._create_connection(
  File "d:\programs\python\python39\lib\socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "d:\programs\python\python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 1792, in url_to_module
    location = get_location(url) # t.co isn't happy with fake_headers
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 393, in get_location
    res = urlopen_with_retry(req)
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 408, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\programs\python\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "d:\programs\python\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "d:\programs\python\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "d:\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "d:\programs\python\python39\lib\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "d:\programs\python\python39\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programs\python\python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "d:\programs\python\python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\programs\python\python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\programs\python\python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\programs\python\python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "d:\programs\python\python39\lib\http\client.py", line 948, in send
    self.connect()
  File "d:\programs\python\python39\lib\http\client.py", line 919, in connect
    self.sock = self._create_connection(
  File "d:\programs\python\python39\lib\socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "d:\programs\python\python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Python\Python39\Scripts\you-get.exe\__main__.py", line 7, in <module>
  File "d:\programs\python\python39\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 1813, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 1695, in script_main
    download_main(
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 1327, in download_main
    download(url, **kwargs)
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 1803, in any_download
    m, url = url_to_module(url)
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 1794, in url_to_module
    location = get_location(url, headers=fake_headers)
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 393, in get_location
    res = urlopen_with_retry(req)
  File "d:\programs\python\python39\lib\site-packages\you_get\common.py", line 408, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "d:\programs\python\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "d:\programs\python\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "d:\programs\python\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "d:\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "d:\programs\python\python39\lib\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "d:\programs\python\python39\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by liangqi** [comment]
Looks like same here with both 0.4.1500 and 0.4.1520 which installed via homebrew on macOS 11.3.1

**Comment by therestone** [comment]
run 'pip install youtube-dl'  then everything gona beokay

**Comment by songds** [comment]
Why did you suddenly fail on YouTube? I can still use it a few days ago&nbsp; &nbsp;


thanks!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "soimort/you-get"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [soimort/you-get] Youtube HTTP Error with code404 (#2890)





 
run 'pip install youtube-dl'  then everything gona beokay

**Comment by CLY88** [comment]
> run 'pip install youtube-dl' then everything gona beokay

i am a believer ~

**Comment by therestone** [comment]
> > run 'pip install youtube-dl' then everything gona beokay
> 
> i am a believ

> > run 'pip install youtube-dl' then everything gona beokay
> 
> i am a believer ~
ummmm ahahhah

**Comment by therestone** [comment]
Ummm hahhah

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: CLY88 ***@***.***>
发送时间: Monday, May 24, 2021 12:15:59 PM
收件人: soimort/you-get ***@***.***>
抄送: therestone ***@***.***>; Comment ***@***.***>
主题: Re: [soimort/you-get] Youtube HTTP Error with code404 (#2890)


run 'pip install youtube-dl' then everything gona beokay

i am a believer ~

―

**Comment by hkc177** [comment]
I got the same problem, I tried running 'pip install you-dl' as other commenter suggested here but still cannot solved it.

**Comment by therestone** [comment]
> I got the same problem, I tried running 'pip install you-dl' as other commenter suggested here but still cannot solved it.

youtube-dl   https://www.youtube.com/watch?v=VFbsp_lRJk4

**Comment by hkc177** [comment]
> youtube-d

Thank you. My bad, after pip installed the you-dl, I still type "you-get", my fault, real sorry and thanks again.

**Pull request closed without merging**
