### PR TITLE
Add -bsf:a aac_adtstoasc when merging

### PR DESCRIPTION
**Pull request by cnbeining**
As in #813 , #499  , #899 .

The question is: is this **harmless**?

@nareix

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1041)

### CODE REVIEW

**Comment by yan12125** [comment]
> is this **harmless**?

ffmpeg spams if the source stream is not in adts format. An example is rg3/youtube-dl#5591.

**Comment by nareix** [comment]
tudou is ok after modified (not-adts aac flv -> mp4)

2016-04-08 12:19 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
I was wrong. ffmpeg warns for non-AAC streams. For non-ADTS AAC streams, it just does nothing. The example above has an MP3 audio stream.

**Comment by soimort** [comment]
> is this harmless?

I'm not sure either. `ffmpeg_concat_mp4_to_mp4()` could be extended so that each extractor (e.g. `tudou.py`) can pass its own arguments for merging. Some sites were known to send malformed streams, so the options might be better to be handled on an individual basis (to prevent unintended effects on others).

A side note: don't change permissions for the file (644 -> 755).

**Comment by cnbeining** [comment]
With ```youtube-dl```, they just put this on by default:

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/postprocessor/ffmpeg.py#L270-L273

**Comment by soimort** [comment]
Just restore the file permission to default 644.

**Comment by cnbeining** [comment]
I will probably redo this PR later.

**Comment by redstoneleo** [comment]
根据我的测试，还有这位的确认https://github.com/soimort/you-get/issues/813#issuecomment-293594575，高版本FFmpeg的不需要这个参数也能行

**Pull request closed without merging**
