### PR TITLE
[QQ] update the url of get video info

### PR DESCRIPTION
**Pull request by jiemoon**
Update the url of get  QQ video info, for fix the old url can't download some videos. eg:
```
$ you-get -d -i 'http://v.qq.com/cover/o/omcczahf3t2sye4/l0019czh4pr.html'
you-get: version 0.4.293, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/o/omcczahf3t2sye4/l0019czh4pr.html']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1250, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1171, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1019, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1243, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/qq.py", line 31, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/qq.py", line 11, in qq_download_by_vid
    url = output_json['vd']['vi'][0]['url']
KeyError: 'vd'
```

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/932)

### CODE REVIEW

**Comment by cnbeining** [comment]
Thanks for your contribution. Please allow some time before your PR being processed.

**Comment by soimort** [comment]
Looks good to me, thanks.

@cnbeining you may merge this -- if it passes all your testing URLs.

**Comment by cnbeining** [comment]
Yeah you have it.

@jiemoon Again thanks for your PR.

**Comment by jiemoon** [comment]
My pleasure :smile:

**Comment by yygcom** [comment]
>you-get --debug http://v.qq.com/cover/t/tj6kt1cg2tzzi6s/k0019hflneb.html
you-get: version 0.4.293, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/t/tj6kt1cg2tzzi6s/k0019hflneb.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1250, in main
  File "src\you_get\common.py", line 1171, in script_main
  File "src\you_get\common.py", line 1019, in download_main
  File "src\you_get\common.py", line 1243, in any_download
  File "src\you_get\extractors\qq.py", line 31, in qq_download
  File "src\you_get\extractors\qq.py", line 11, in qq_download_by_vid
KeyError: 'vd'
you-get returned -1

**Pull request merged**
