### PR TITLE
Update douyin.py

### PR DESCRIPTION
**Pull request by pyx**
Updated the extractor for the latest www.douyin.com

### CODE REVIEW

**Comment by soimort** [comment]
Thanks for the fix!

**Comment by zsrl** [comment]
@pyx 

The update is work ? I get fail result

```
you-get 'https://www.douyin.com/video/6930090637240831239' --debug
```

image

**Comment by pyx** [comment]
> @pyx
> 
> The update is work ? I get fail result
> 
> ```
> you-get 'https://www.douyin.com/video/6930090637240831239' --debug
> ```
> 
> image

Yesterday, right after the new release of you-get 0.4.1536, the website employed some way to prevent clients other than web browser to download the html source, both you-get's downloader and wget will receive 0 (zero) size file while web browser can load the html without problem.

The extractor still work if you-get is able to download the html source (using save page in browser and feed that to you-get, for example), since the fix will probably outside the extractor, I have yet find the time to take a deep look at that.

**Comment by pyx** [comment]
@soimort do you have any idea what might be the cause? I tried with the latest google-chrome UA, and it failed too, so the browser sniffing technique they are using is quite intelligent?

**Comment by pyx** [comment]
For example, `wget 'https://www.douyin.com/video/6982497745948921092'` will save a zero length file, while open https://www.douyin.com/video/6982497745948921092 in browser is okay.

**Comment by zsrl** [comment]
@pyx 
Thanks for answer me. I see the same problem. when I debug by source, variable `page_content` get empty string.

image
image

**Comment by pyx** [comment]
@zsrl It's working now, they probably had back-end bug back then.
yg

**Comment by zsrl** [comment]
@pyx It's really work, thank you very much

**Comment by wwwfzt** [comment]
> @pyx It's really work, thank you very much

is that worked? I see the same problem in version 0.4.1602.
image

**Pull request merged**
