### PR TITLE
add extractors for yicai.com / video.cnfol.com / video.eastmoney.com

### PR DESCRIPTION
**Pull request by VitoVan**
For Test:

东方财富   <http://video.eastmoney.com/>  

```bash
./you-get -i http://video.eastmoney.com/news/1609,20160408612456177.html
Site:       video.eastmoney.com
Title:      婷婷创立：Fit Time――Hold住你的人生，从Hold住身体开始！
Type:       MPEG-4 video (video/mp4)
Size:       72.65 MiB (76178903 Bytes)
```

中金在线   <http://video.cnfol.com/>      
(It will fail on some weird page from this site, the problem and solution is here: https://github.com/soimort/you-get/pull/1116)

```bash
./you-get --debug -i http://video.cnfol.com/anxinshiye/20160505/22700157.shtml
[DEBUG] get_content: http://video.cnfol.com/anxinshiye/20160505/22700157.shtml
Site:       video.cnfol.com
Title:      朱力解盘：隔夜外围再跌 A股面临选择
Type:       MPEG-4 video (video/mp4)
Size:       26.78 MiB (28075962 Bytes)
```

第一财经  <http://www.yicai.com/video/>   

```bash
./you-get --debug -i http://www.yicai.com/video/5011500.html
[DEBUG] get_content: http://m.yicai.com/video/5011500.html
Site:       *.yicai.com/video
Title:      【首席对策】吴敬琏：证券市场的繁荣不是靠“放水”
Type:       MPEG-4 video (video/mp4)
Size:       65.04 MiB (68195260 Bytes)
```

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1117)

### CODE REVIEW

**Comment by cnbeining** [comment]
Thank you very much for your PR.

May I have you split this PR into different commits, one site each? This
would greatly help us with future debugging should required.

2016年5月10日星期二，Mort the Bot <notifications@github.com> 写道：

**Comment by VitoVan** [comment]
@cnbeining Done.

**Comment by soimort** [comment]
Not sure if we can extend our set of extractors too far beyond the current scope. Plus, all of them seem trivial in implementation, so we should instead improve our `universal.py` or `embed.py` (I can see that eastmoney.com hosts their videos on http://www.kankanews.com/, so why do we need a separate extractor for that?)

**Comment by VitoVan** [comment]
OK, as you say.

**Pull request closed without merging**
