### PR TITLE
bilibili无法正常下载及解决办法

### PR DESCRIPTION
**Pull request by GuanFoxyier**
bilibili downloading is not working, it shows
you-get -d https://www.bilibili.com/video/av46679537/?p=2
[DEBUG] get_content: https://www.bilibili.com/video/av46679537/?p=2
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
you-get: version 0.4.1328, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/av46679537/?p=2'], auto_
rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, forma
t=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False
, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, outpu
t_dir='.', output_filename=None, password=None, player=None, playlist=False, ski
p_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, ur
l=False, version=False)
Traceback (most recent call last):
  File "e:\ruanjian2\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\ruanjian2\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ruanjian2\python37\Scripts\you-get.exe\__main__.py", line 9, in <modu
le>
  File "e:\ruanjian2\python37\lib\site-packages\you_get\__main__.py", line 92, i
n main
    main(**kwargs)
  File "e:\ruanjian2\python37\lib\site-packages\you_get\common.py", line 1759, i
n main
    script_main(any_download, any_download_playlist, **kwargs)
  File "e:\ruanjian2\python37\lib\site-packages\you_get\common.py", line 1647, i
n script_main
    **extra
  File "e:\ruanjian2\python37\lib\site-packages\you_get\common.py", line 1303, i
n download_main
    download(url, **kwargs)
  File "e:\ruanjian2\python37\lib\site-packages\you_get\common.py", line 1750, i
n any_download
    m.download(url, **kwargs)
  File "e:\ruanjian2\python37\lib\site-packages\you_get\extractor.py", line 48,
in download_by_url
    self.prepare(**kwargs)
  File "e:\ruanjian2\python37\lib\site-packages\you_get\extractors\bilibili.py",
 line 173, in prepare
    initial_state = json.loads(initial_state_text)
  File "e:\ruanjian2\python37\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

解决方法及作出的修改:
 原代码中User-Agent疑似被封, 修改User-Agent后恢复正常

经测试修改后已经可以正常下载

### CODE REVIEW

**Comment by 347GHQ** [comment]
It worked well.
Very efficient!

**Comment by kpwd** [comment]
不行,还是和谐掉了,看样子UA用固定值是不可以的,建议用户可以自定义UA!!!!
    @staticmethod
    def bilibili_headers(referer=None, cookie=None):
        # a reasonable UA
        ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) fuck you bilibili Chrome/63.0.3239.84 Safari/537.36'
        headers = {'User-Agent': ua}
        if referer is not None:
            headers.update({'Referer': referer})
        if cookie is not None:
            headers.update({'Cookie': cookie})
        return headers

我又改了一次UA,加了个 fuck you bilibili ,诶就成了....
所以给UA加个随机数你看怎么样????

**Comment by kpwd** [comment]
> 不行,还是和谐掉了,看样子UA用固定值是不可以的,建议用户可以自定义UA!!!!
> @staticmethod
> def bilibili_headers(referer=None, cookie=None):
> # a reasonable UA
> ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) fuck you bilibili Chrome/63.0.3239.84 Safari/537.36'
> headers = {'User-Agent': ua}
> if referer is not None:
> headers.update({'Referer': referer})
> if cookie is not None:
> headers.update({'Cookie': cookie})
> return headers
> 
> 我又改了一次UA,加了个 fuck you bilibili ,诶就成了....
> 所以给UA加个随机数你看怎么样????

UA随机化了,这样或许可以一劳永逸?
https://github.com/soimort/you-get/pull/2736

bilibili: 我从未见过如此恶心的代码!

**Comment by FSpark** [comment]
现在暂时还没碰到这样的问题，继续跟进

**Comment by DW2993706602** [comment]
thanks

**Comment by redkaoliang** [comment]
Add cookies you can solve it. 
Try :
you-get -c cookies.txt -l https://www.bilibili.com/video/av46679537

**Comment by overturncat** [comment]
> Add cookies you can solve it.
> Try :
> you-get -c cookies.txt -l https://www.bilibili.com/video/av46679537

请问cookies.txt的格式是什么, chrome导出的的cookies不能用

**Comment by FSpark** [comment]
> > Add cookies you can solve it.
> > Try :
> > you-get -c cookies.txt -l https://www.bilibili.com/video/av46679537
> 
> 请问cookies.txt的格式是什么, chrome导出的的cookies不能用

Netscape cookies，在Chrome上可使用cookies.txt扩展获取，但感觉问题并不在这

**Comment by FSpark** [comment]
已解决
https://github.com/soimort/you-get/pull/2737

**Comment by wingschen** [comment]
user_agent_list = [ \
            "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/22.0.1207.1 Safari/537.1" \
            "Mozilla/5.0 (X11; CrOS i686 2268.111.0) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11", \
            "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.6 (KHTML, like Gecko) Chrome/20.0.1092.0 Safari/536.6", \
            "Mozilla/5.0 (Windows NT 6.2) AppleWebKit/536.6 (KHTML, like Gecko) Chrome/20.0.1090.0 Safari/536.6", \
            "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/19.77.34.5 Safari/537.1", \
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.9 Safari/536.5", \
            "Mozilla/5.0 (Windows NT 6.0) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.36 Safari/536.5", \
            "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1063.0 Safari/536.3", \
            "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1063.0 Safari/536.3", \
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1063.0 Safari/536.3", \
            "Mozilla/5.0 (Windows NT 6.2) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1062.0 Safari/536.3", \
            "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1062.0 Safari/536.3", \
            "Mozilla/5.0 (Windows NT 6.2) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1061.1 Safari/536.3", \
            "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1061.1 Safari/536.3", \
            "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1061.1 Safari/536.3", \
            "Mozilla/5.0 (Windows NT 6.2) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1061.0 Safari/536.3", \
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.24 (KHTML, like Gecko) Chrome/19.0.1055.1 Safari/535.24", \
            "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/535.24 (KHTML, like Gecko) Chrome/19.0.1055.1 Safari/535.24"
        ]
        UserAgent = random.choice(user_agent_list)
        headers = {'User-Agent': UserAgent}

**Comment by soimort** [comment]
Thanks for the PR. (fixed by #2737)

**Comment by pusvFish** [comment]
wow ,really thanks!谢谢老哥，嘻嘻嘻！

**Comment by NocturnalJ** [comment]
Cookies seem to be the right way to go, part of the reason being authorization issue as 403 indicates(given that highest res video from bilibili requires user login)?
@redkaoliang It worked for me as of now. Thanks!

**Comment by bo-er** [comment]
As for me, I didn't get a 403 error,but the rest of the debug info was exactly the same as @GuanFoxyier's, and it really bugged me for a long time!  After uninstall and reinstall, I got an different error which said "unable to get local issuer certificate (_ssl.c:1108)>", after googling I opened finder-application-python3.8 and double clicked 「Install Certificates.command」and then magically you-get finally worked! I just can't live without you-get! Doing all the learning stuff with bilibili.com!

**Pull request closed without merging**
