### PR TITLE
[.github] Add FAQ to issue

### PR DESCRIPTION
**Pull request by cnbeining**
Add FAQ to issue

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/960)

### CODE REVIEW

**Comment by soimort** [comment]
Better to separate it out as an individual item, FAQ is not anything about issues, but common problems regarding general usage.

**Comment by cnbeining** [comment]
Title misleading...

What I am trying to do is I want all users who want to raise any issue to **READ THE DAMNED FAQ** before asking any questions. I even drawn them a picture.

**Comment by soimort** [comment]
I meant something like this:

- [x] Make sure you have read <https://github.com/soimort/you-get/wiki/FAQ> before reporting any issue.
- [ ] The issue is not yet reported on blabla ...

Sadly I doubt whether people are actually reading our ISSUE_TEMPLATE, leave alone all these extra links. (Well, this might the best we could do.)

Personally I consider "having to read the FAQ" as bad user experience. I must say It's not users' fault, but that Microsoft really needs to fix their **DAMNED `cmd.exe`**. Even I myself had a hard time doing testing and packaging for `you-get` under Windows.

**Comment by cnbeining** [comment]
I really cannot stop myself from add up something like 

> failure to do so will result in public humiliation and disgrace

at the end of the issue template...

**Comment by soimort** [comment]
> I really cannot stop myself from add up something like

You may not do so. Feel free to ignore any issues that are too "noob" for you to reply, and I'll handle the rest. (by copy and pasting the link to them)

**Comment by cnbeining** [comment]
Well, no. Just saying.

**Comment by cnbeining** [comment]
Close and make a real one.

**Pull request closed without merging**
