### PR TITLE
Fix douyin download failed.

### PR DESCRIPTION
**Pull request by savvym**
Due to the old method and API being unable to download Douyin videos, a new method has been developed to download them.

befor fix:
```
# you-get 'https://v.douyin.com/iRfsLb5' -c douyin_cookies.txt
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```
after:
```
# you-get 'https://v.douyin.com/iRfsLb5' -c douyin_cookies.txt
Site:       douyin.com
Title:      小小转一下 m0NESY 你们觉得今年会是top几呢？
#csgo #m0NESY #G2 #niko #m0nesy名场面
Type:       MPEG-4 video (video/mp4)
Size:       85.64 MiB (89801608 Bytes)

Downloading 小小转一下 m0NESY 你们觉得今年会是top几呢？
#csgo #m0NESY #G2 #niko #m0nesy名场面.mp4 ...
 100% ( 85.6/ 85.6MB) ├███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]   17 MB/s
```
---  
**In addtion, when obtain Douyin cookies through Chrome extensions (such as `Get Cookies.txt locally`), I suggest modifying the expire time of `__ac_nonce` to be the same as that of `__ac_signature`. Otherwise, the cookies will expire quickly.**

### CODE REVIEW

**Comment by savvym** [comment]
befor fix:
```
# you-get 'https://v.douyin.com/iRfsLb5' -c douyin_cookies.txt
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```
after:
```
# you-get 'https://v.douyin.com/iRfsLb5' -c douyin_cookies.txt
Site:       douyin.com
Title:      小小转一下 m0NESY 你们觉得今年会是top几呢？
#csgo #m0NESY #G2 #niko #m0nesy名场面
Type:       MPEG-4 video (video/mp4)
Size:       85.64 MiB (89801608 Bytes)

Downloading 小小转一下 m0NESY 你们觉得今年会是top几呢？
#csgo #m0NESY #G2 #niko #m0nesy名场面.mp4 ...
 100% ( 85.6/ 85.6MB) ├███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]   17 MB/s
```

**Comment by HamiguaLu** [comment]
By the way, is there any tools to export the cookies from chrome or firefox automaticallly?  I know there are chrome extensions can do this but I want to get it from python or command line
Thanks in advance

**Comment by savvym** [comment]
@HamiguaLu I also use chrome extension to export. In addtion, when obtain Douyin cookies through Chrome extensions (such as Get Cookies.txt locally), I suggest modifying the expire time of __ac_nonce to be the same as that of __ac_signature. Otherwise, the cookies will expire quickly.

**Comment by HamiguaLu** [comment]
> @HamiguaLu I also use chrome extension to export. In addtion, when obtain Douyin cookies through Chrome extensions (such as Get Cookies.txt locally), I suggest modifying the expire time of __ac_nonce to be the same as that of __ac_signature. Otherwise, the cookies will expire quickly.

Thanks very much for the hint,

**Comment by kongratana21** [comment]
> > Due to the old method and API being unable to download Douyin videos, a new method has been developed to download them.
> > befor fix:
> > ```
> > # you-get 'https://v.douyin.com/iRfsLb5' -c douyin_cookies.txt
> > you-get: [error] oops, something went wrong.
> > you-get: don't panic, c'est la vie. please try the following steps:
> > you-get:   (1) Rule out any network problem.
> > you-get:   (2) Make sure you-get is up-to-date.
> > you-get:   (3) Check if the issue is already known, on
> > you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
> > you-get:         https://github.com/soimort/you-get/issues
> > you-get:   (4) Run the command with '--debug' option,
> > you-get:       and report this issue with the full output.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after:
> > ```
> > # you-get 'https://v.douyin.com/iRfsLb5' -c douyin_cookies.txt
> > Site:       douyin.com
> > Title:      小小转一下 m0NESY 你们觉得今年会是top几呢？
> > #csgo #m0NESY #G2 #niko #m0nesy名场面
> > Type:       MPEG-4 video (video/mp4)
> > Size:       85.64 MiB (89801608 Bytes)
> > 
> > Downloading 小小转一下 m0NESY 你们觉得今年会是top几呢？
> > #csgo #m0NESY #G2 #niko #m0nesy名场面.mp4 ...
> >  100% ( 85.6/ 85.6MB) ├███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]   17 MB/s
> > ```
> 
> Thanks very much, it works for me

Hi sir. this you-get can download from kuaishou?

**Comment by kongratana21** [comment]
> h for the hint,

hello sir, how to download from kuaishou?

**Comment by RallyQ** [comment]
Use this [fix douyin.py] yesterday was normal download, today is not good, please check and confirm,thank you!

**Comment by RallyQ** [comment]
Did the you-get author give up? It hasn't been updated in almost a year

**Comment by 54514382** [comment]
how to get douyin_cookies.txt ? thanks !

**Comment by 54514382** [comment]
image
douyin always failed , why ?

**Comment by savvym** [comment]
@54514382 Now douyin uses msToken and X-Bogus parameters to prevent web crawlers, which is currently quite troublesome.

**Comment by 54514382** [comment]
> @54514382 Now douyin uses msToken and X-Bogus parameters to prevent web crawlers, which is currently quite troublesome.

so, currently you-get not work for douyin, right ? thanks for your reply!

**Comment by RallyQ** [comment]
> @54514382 Now douyin uses msToken and X-Bogus parameters to prevent web crawlers, which is currently quite troublesome.

TikTokDownloader can be downloaded, I wonder if it is helpful
Still want to download douyin with you-get

**Pull request closed without merging**
