### PR TITLE
Update youku.py

### PR DESCRIPTION
**Pull request by 9yw**
ccode=0512会报错 客户端无权播放,201 改成0513可以下载
got error 201 when ccode=0512

### CODE REVIEW

**Comment by nodejh** [comment]
我改为了 5013 提示 `you-get: ccode参数错误`，改为 0513 可以下载

**Comment by Jason5Lee** [comment]
亲测有效

**Comment by 9yw** [comment]
描述写错了……是改成0513。

**Comment by StLym** [comment]
0513可以下载了

**Comment by iamggs** [comment]
Tks...

```
-        self.ccode = '0512'
+        self.ccode = '0513'
```

**Comment by jyuan15** [comment]
0513没有1080P

**Comment by tulip33** [comment]
改成0513依然客户端无权播放201
是改AppData\Local\Programs\Python\Python35\Scripts\extractors\youku.py吗？有两处0512，都改成0513，还是上面的提示无法下载，
求教！

**Comment by huangjunp** [comment]
今天0502也没用了，貌似加了参数，各位大兄弟有人把优酷的爬出来的吗？

**Comment by nodejh** [comment]
@huangjunp  我最终用 youtube-dl 下载的

**Comment by jyuan15** [comment]
0513不行就改0508

**Comment by seahog004** [comment]
改成0514即可

**Comment by huangjunp** [comment]
都不行啊。你们都试过自己的可以了？为啥都说改了即可

**Comment by huangjunp** [comment]
兄弟们，版主有留下什么交流群么？谁能拉我进去围观一下？

**Comment by China1035** [comment]
[DEBU
G] HTTP Error with code403
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
you-get: version 0.4.1011, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://v.youku.com/v_show/id_XMzI2NTUyOTIxMg==.html?spm
=a2h0k.8191407.0.0'], cookies=None, debug=True, extractor_proxy=None, force=Fals
e, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=N
one, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.
', output_filename=None, password=None, player=None, playlist=False, socks_proxy
=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\Scripts
\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.1011', 'console_scripts', 'you-get')()
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 1583, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 1472, in script_main
    **extra
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 1216, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 1574, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\extractors\youku.py", line 305, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\extractor.py", line 59, in download_by_url
    self.download(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\extractor.py", line 228, in download
    av=stream_id in self.dash_streams)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 911, in download_urls
    headers=headers, **kwargs
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 599, in url_save
    file_size = url_size(url, faker=faker, headers=tmp_headers)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 484, in url_size
    response = urlopen_with_retry(request.Request(url, headers=headers))
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 391, in urlopen_with_retry
    raise http_error
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\sit
e-packages\you_get\common.py", line 382, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\url
lib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\url
lib\request.py", line 471, in open
    response = meth(req, response)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\url
lib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\url
lib\request.py", line 509, in error
    return self._call_chain(*args)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\url
lib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\users\administrator\appdata\local\programs\python\python35-32\lib\url
lib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by China1035** [comment]
youku 目前不能下载了debug错误回显如上一条回复 求助！

**Comment by pukarziu** [comment]
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Skipping .\爸爸去哪儿 第五季.mkv: file already exists

**Comment by huangjunp** [comment]
@pukarziu  It's not very clear what you say, Can youku.py continue to work?

**Comment by jyuan15** [comment]
@China1035 可以下载啊

➡ cd you-get
you-get|develop⚡🔅 ➡ python you-get -o /sdcard1/movies http://v.youku.com/v_show/id_XMzI2NTUyOTIxMg\=\=.html
site:                优酷 (Youku)
title:               梅林路考一号线
stream:
    - format:        mp4sd
      container:     mp4
      video-profile: 标清
      size:          20.2 MiB (21224519 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzI2NTUyOTIxMg%3D%3D&type=flv&ups_client_netip=75b0fca1&ups_ts=1516181502&utid=%2BwXmEt2MJ1UCAXWw%2FKF1ALRo&ccode=0508&psid=82e3db59ce1fbbc1e78469034565a052&duration=552&expire=18000&ups_key=047a9c069a303ebf61f56dc406b46b3d
    # download-with: you-get --format=mp4sd [URL]

Downloading 梅林路考一号线.mp4 ...
 100% ( 20.2/ 20.2MB) ├████████████████┤[2/2]   10 MB/s
Merging video parts... Merged into 梅林路考一号线.mp4

**Comment by huangjunp** [comment]
@jyuan15 你的youku.py，ccode是多少啊

**Comment by China1035** [comment]
@jyuan15 您也是这个 You-Get VERSION 0.4.1011 这个版本的吗？

**Comment by jyuan15** [comment]
@China1035 视频地址里面可以看到ccode，是0508，版本当然是最新的。
0507、0513、0514都可以解析，但这几个ccode都没有1080P。

**Comment by China1035** [comment]
@jyuan15 原来如此 谢谢解答

**Comment by huangjunp** [comment]
@jyuan15 原来如此 谢谢您的解答

**Comment by wangxiusen** [comment]
验证ssl证书失败的问题怎么解决了 找了网上没有一个答案。。。。

**Comment by wangxiusen** [comment]
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

**Comment by thaisday** [comment]
@wangxiusen  我也是遇到了这个问题,不知道咋解决

**Comment by thaisday** [comment]
@wangxiusen 找到解决方案了,是我们本地证书库的问题.如果你和我一样是MAC的话.运行这个命令更新下本地的证书库 /Applications/Python\ 3.6/Install\ Certificates.command , 就可以了

**Comment by elespec** [comment]
优酷这次变更有点儿大....ups那个接口添加了验证,而且验证还有时间限制,我临时写了个简单的用来下载优土视频.....话说我只是想下载我自己以前上传的视频啊..都不行啊...

**Comment by elespec** [comment]
@huangjunp 用PC浏览器请求,调试窗口里找ups 的请求,我就是这么找的地址,然后写了个临时的,现在ccode都是050F了,但是现在修改ccode不能解决问题;

**Comment by soimort** [comment]
Thanks!

**Comment by ceekay1991** [comment]
https://ups.youku.com/ups/get.json?vid=XMzQ3MDI5NTQzMg%3D%3D&ccode=0590&client_ip=192.168.1.1&utid=s8U4E%2B4a7BsCAT2HqUlCGf0R&client_ts=1521604534

**Comment by ceekay1991** [comment]
cccode 改成0590可以用

**Comment by archwolf118** [comment]
@ceekay1991  您好！有没有什么办法找到这个ccode码，难道要一遍一遍试吗？

**Comment by ceekay1991** [comment]
没有研究过，我用谷歌搜索ups.youku.com/ups/get.json这个字符串，挨个文章看的，

**Comment by iamggs** [comment]
-        self.ccode = '0507'
+       self.ccode = '0590'

tks @ceekay1991

**Comment by huangjunp** [comment]
youget --json 返回来的m3u8真是地址只有十分钟，经查明优酷H5端只能播放十分钟，有办法解决这个问题吗？大神们！

**Comment by huangjunp** [comment]
youget --json 返回来的m3u8真实地址只有十分钟，经查明优酷H5端只能播放十分钟，有办法解决这个问题吗？大神们！

**Pull request merged**
