### PR TITLE
B站视频下载错误

### PR DESCRIPTION
**Pull request by qcymkxyc**
Error
Traceback (most recent call last):
  File "/home/ylc/PycharmProjects/you-get/tests/test.py", line 44, in test_bilibili
    bilibili.download("https://www.bilibili.com/video/BV1Nx411f7MT/?spm_id_from=autoNext", info=True)
  File "/home/ylc/PycharmProjects/you-get/src/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/home/ylc/PycharmProjects/you-get/src/you_get/extractors/bilibili.py", line 220, in prepare
    current_quality = playinfo['data']['quality'] or None  # 0 indicates an error, fallback to None
KeyError: 'data'

### CODE REVIEW

**Comment by xuxy211** [comment]
Help me !

**Comment by GSRLW** [comment]
found this problem again。。。 help me
image
you-get: version 0.4.1545, a tiny downloader that scrapes the web.
you-get: Namespace(version=False, help=False, info=True, url=False, json=False, no_merge=False, no_caption=False, force=False, skip_existing_file_size_check=False, format=None, output_filename=None, output_dir='.', player=None, cookies=None, timeout=600, debug=True, input_file=None, password=None, playlist=True, first=None, last=None, size=None, auto_rename=False, insecure=False, http_proxy=None, extractor_proxy=None, no_proxy=False, socks_proxy=None, stream=None, itag=None, URL=['https://www.bilibili.com/video/BV1Ny4y1D7gc'])
Traceback (most recent call last):
  File "/home/xzw/conda/envs/you-get/bin/you-get", line 10, in <module>
    sys.exit(main())
  File "/home/xzw/conda/envs/you-get/lib/python3.9/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/xzw/conda/envs/you-get/lib/python3.9/site-packages/you_get/common.py", line 1831, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/home/xzw/conda/envs/you-get/lib/python3.9/site-packages/you_get/common.py", line 1713, in script_main
    download_main(
  File "/home/xzw/conda/envs/you-get/lib/python3.9/site-packages/you_get/common.py", line 1343, in download_main
    download_playlist(url, **kwargs)
  File "/home/xzw/conda/envs/you-get/lib/python3.9/site-packages/you_get/common.py", line 1827, in any_download_playlist
    m.download_playlist(url, **kwargs)
  File "/home/xzw/conda/envs/you-get/lib/python3.9/site-packages/you_get/extractors/bilibili.py", line 620, in download_playlist_by_url
    self.__class__().download_by_url(purl, **kwargs)
  File "/home/xzw/conda/envs/you-get/lib/python3.9/site-packages/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/home/xzw/conda/envs/you-get/lib/python3.9/site-packages/you_get/extractors/bilibili.py", line 220, in prepare
    current_quality = playinfo['data']['quality'] or None  # 0 indicates an error, fallback to None
KeyError: 'data'

**Comment by venshu** [comment]
help me !!!

**Comment by saltfish13** [comment]
wandering how to apply the fix for home-brew version I can't find that exact file

> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

**Comment by jjlinghu** [comment]
> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

请问这个是在哪里更改呀

**Comment by kaze114** [comment]
> > 我这么改改好像能用。。。有兴趣就试试。。
> > https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py
> 
> 请问这个是在哪里更改呀

/找到C:\Python\py3.10.0\Lib\site-packages\you_get\extractors
直接在python的文件夹中搜索bilibili.py
一般是那个30kb到40kb的.py文件
然后把大佬的代码覆盖到这个.py文件
Then oka
idle bilibili
y

**Comment by venshu** [comment]
> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

Thank you all so much!!

**Comment by jjlinghu** [comment]
> > > 我这么改改好像能用。。。有兴趣就试试。。
> > > https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py
> > 
> > 
> > 请问这个是在哪里更改呀
> 
> /找到C:\Python\py3.10.0\Lib\site-packages\you_get\extractors 直接在python的文件夹中搜索bilibili.py 一般是那个30kb到40kb的.py文件 然后把大佬的代码覆盖到这个.py文件 Then oka idle bilibili y

谢谢！！！

**Comment by SHMoney2021** [comment]
> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

COOL! IT WORKS! THANKS!

**Comment by ANYLNK** [comment]
同样的问题，我试试看修改过后的吧

**Comment by xuxy211** [comment]
Thank you  
it works !

**Comment by flyingdance0** [comment]
https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py
这个链接我打不开，有什么办法吗

**Comment by Jing-Jianfeng** [comment]
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py 这个链接我打不开，有什么办法吗
这个网站可以，https://ghproxy.com/
https://ghproxy.com/https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

**Comment by flyingdance0** [comment]
> > https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py 这个链接我打不开，有什么办法吗
> > 这个网站可以，https://ghproxy.com/
> > https://ghproxy.com/https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

谢谢，拿到了，有时间研究一下

**Comment by symant233** [comment]
> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

可以用，请问能否提交一个PR

**Comment by GSRLW** [comment]
学习了[https://github.com/soimort/you-get/pull/2933#issuecomment-955196706]各位的修改，有效果,谢谢大佬们。

**Comment by kobetomes** [comment]
替换了那个40KB的文件，俺还是用不了呀

**Comment by kobetomes** [comment]
谢谢大佬，各位注意一下，替换的是“bilibili.py”文件，而不是替换“_bilibili.py”文件，
VX：1450372543

**Comment by hellowangsir** [comment]
发现除了BiliBili，还有别的视频网站，也都不能使用 you-get 进行下载了。

**Comment by mo-han** [comment]
> 
> 
> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

https://github.com/rfiacne/you-get
帮贴个分支URL，方便点击

**Comment by hagane233** [comment]
THX！！

**Comment by GSRLW** [comment]
image

**Comment by huntagain2008** [comment]
@rfiacne 感谢您。

**Comment by worst001** [comment]
> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

兄弟你很帅

**Comment by KAHO-TONG** [comment]
> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

Cool you fix the problem， Thanks！

**Comment by Qy20** [comment]
> > > 我这么改改好像能用。。。有兴趣就试试。。
> > > https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py
> > 
> > 
> > 请问这个是在哪里更改呀
> 
> /找到C:\Python\py3.10.0\Lib\site-packages\you_get\extractors 直接在python的文件夹中搜索bilibili.py 一般是那个30kb到40kb的.py文件 然后把大佬的代码覆盖到这个.py文件 Then oka 闲置的哔哩哔哩 y
谢谢

**Comment by dragonandy** [comment]
can't find the fix commit anymore, anyone can help?

**Comment by knnq11** [comment]
> 我这么改改好像能用。。。有兴趣就试试。。
> 
> https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

兄弟，you-get好像又不能下载b站1080P以上的视频了，能再次出山吗？感激啊

**Comment by y1993** [comment]
您好，邮件已经收到

**Comment by 5258** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Pull request closed without merging**
