### PR TITLE
fix bilibili and bug #353

### PR DESCRIPTION
**Pull request by pastebt**
[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/489)

### CODE REVIEW

**Comment by soimort** [comment]
Doesn't fix #353 for me:

```
./you-get -i http://tv.sohu.com/20140629/n401523369.shtml\?txid\=8254069965286abe9ee523a73c256ea7
Traceback (most recent call last):
  File "./you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 999, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 893, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 785, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 992, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/sohu.py", line 27, in sohu_download
    hqvid = data['data'][qtyp]
TypeError: 'NoneType' object is not subscriptable
```

ps. I'm afraid we can't switch to any other UA than `Biligrab`; see the discussion [here](https://github.com/soimort/you-get/issues/376).

**Comment by soimort** [comment]
I guess it should work with a `-y` proxy; will try it later...

**Comment by pastebt** [comment]
for bug #353, have to add proxy, I used 
python3 you-get -y 211.155.86.25:8888 -i http://tv.sohu.com/20140629/n401523369.shtml\?txid\=8254069965286abe9ee523a73c256ea7
Video Site: Sohu.com
Title:      水手服僵尸第10集
Type:       MPEG-4 video (video/mp4)
Size:       172.96 MiB (181358830 Bytes)

**Comment by pastebt** [comment]
For bilibili, I don't know what happen from other place, but from my site, the UA 'Biligrab /0.8 (cnbeining@gmail.com)' looks be blocked, especially for the video I listed as sample. But not for all video, Interesting.

**Comment by soimort** [comment]
Good to know the old UA is blocking someone else (so it's not just me #423). I'll see if we can figure this out; before that let's keep using the working one...

**Pull request merged**
