### PR TITLE
bilibili urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### PR DESCRIPTION
**Pull request by q629988171**
C:\Users\Allen>you-get --debug https://www.bilibili.com/video/BV1oC4y1w7do
[DEBUG] get_content: https://www.bilibili.com/video/BV1oC4y1w7do
[DEBUG] get_content: https://www.bilibili.com/video/BV1oC4y1w7do
you-get: You will need login cookies for 720p formats or above. (use --cookies to load cookies.txt.)
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=1349898517&otype=json&qn=112&quality=112&type=&sign=2f1174f7babe041913db31eed27eecf0
[DEBUG] HTTP Error with code504
[DEBUG] HTTP Error with code429
[DEBUG] HTTP Error with code429
you-get: version 0.4.1650, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.bilibili.com/video/BV1oC4y1w7do'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, first=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, last=None, m3u8=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, postfix=False, prefix=None, size=None, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\Scripts\you-get-script.py", line 33, in <module>
    sys.exit(load_entry_point('you-get==0.4.1650', 'console_scripts', 'you-get')())
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\__main__.py", line 92, in main
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\common.py", line 1879, in main
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\common.py", line 1771, in script_main
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\common.py", line 1385, in download_main
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\common.py", line 1870, in any_download
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\extractor.py", line 48, in download_by_url
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\extractors\bilibili.py", line 282, in prepare
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\common.py", line 478, in get_content
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\common.py", line 447, in urlopen_with_retry
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\site-packages\you_get-0.4.1650-py3.8.egg\you_get\common.py", line 438, in urlopen_with_retry
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### CODE REVIEW

**Comment by alphaply** [comment]
I also have the same problem

**Comment by alphaply** [comment]
Besides 429, there will also be 504

**Comment by ywh939** [comment]
the same error when intend to download multi-videos

`Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/you_get/common.py", line 1870, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/you_get/common.py", line 1762, in script_main
    download_main(
  File "/usr/local/lib/python3.8/dist-packages/you_get/common.py", line 1382, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/you_get/common.py", line 1861, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/you_get/extractors/bilibili.py", line 276, in prepare
    api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
  File "/usr/local/lib/python3.8/dist-packages/you_get/common.py", line 477, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/lib/python3.8/dist-packages/you_get/common.py", line 446, in urlopen_with_retry
    raise http_error
  File "/usr/local/lib/python3.8/dist-packages/you_get/common.py", line 437, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests`

**Comment by eavesz** [comment]
it seems bilibili changed something just yesterday...

**Comment by NoonLeu** [comment]
Waiting for a solution,I have the same problem,it seems that a new change had been done with bilibili video website.

**Comment by ftakanashi** [comment]
Same problem encountered. Bilibili may have changed something in this interface: https://interface.bilibili.com/v2/playurl

```
[DEBUG] get_content: https://www.bilibili.com/video/BV1WM411d7My/
[DEBUG] get_content: https://www.bilibili.com/video/BV1WM411d7My/
[DEBUG] get_content: https://api.bilibili.com/x/player/playurl?avid=536754940&cid=1354241482&qn=80&type=&otype=json&fnver=0&fnval=16&fourk=1
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=1354241482&otype=json&qn=80&quality=80&type=&sign=27711e2faf182b3a7a5fa2d31f625099
[DEBUG] HTTP Error with code504
[DEBUG] HTTP Error with code429
[DEBUG] HTTP Error with code429
you-get: version 0.4.1520, a tiny downloader that scrapes the web.
you-get: Namespace(version=False, help=False, info=False, url=False, json=True, no_merge=False, no_caption=False, force=False, skip_existing_file_size_check=False, format=None, output_filename=None, output_dir='.', player=None, cookies='/app/cookies.txt', timeout=600, debug=True, input_file=None, password=None, playlist=True, first=None, last=None, size=None, auto_rename=False, insecure=False, http_proxy=None, extractor_proxy=None, no_proxy=False, socks_proxy=None, stream=None, itag=None, URL=['https://www.bilibili.com/video/BV1WM411d7My/'])
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/you_get/common.py", line 1813, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/you_get/common.py", line 1695, in script_main
    download_main(
  File "/usr/local/lib/python3.10/site-packages/you_get/common.py", line 1325, in download_main
    download_playlist(url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/you_get/common.py", line 1809, in any_download_playlist
    m.download_playlist(url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/you_get/extractors/bilibili.py", line 670, in download_playlist_by_url
    self.prepare_by_cid(aid,initial_state['videoData']['pages'][pi]['cid'],'%s (P%s. %s)' % (initial_state['videoData']['title'], pi+1, initial_state['videoData']['pages'][pi]['part']),html_content,playinfo,playinfo_,url)
  File "/usr/local/lib/python3.10/site-packages/you_get/extractors/bilibili.py", line 497, in prepare_by_cid
    api_content = get_content(api_url, headers=self.bilibili_headers())
  File "/usr/local/lib/python3.10/site-packages/you_get/common.py", line 439, in get_content
    response = urlopen_with_retry(req)
  File "/usr/local/lib/python3.10/site-packages/you_get/common.py", line 417, in urlopen_with_retry
    raise http_error
  File "/usr/local/lib/python3.10/site-packages/you_get/common.py", line 408, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

**Comment by jacklyh-lvy** [comment]
me too, me have meet someting solition in bilibili

**Comment by jacklyh-lvy** [comment]
me too, me have meet someting question in bilibili.

**Comment by jacklyh-lvy** [comment]
Me too, I'm having some of the same issues at Bilibili

**Comment by sorfans1** [comment]
I meet the same issue, and get the same msg: 
urllib.error.HTTPError: HTTP Error 504: Gateway Time-out

But there is a websit can still find the real URL of bilibili's video from the URL of bilibili's page. The websit is bili.iiilab.com.

**Comment by NoonLeu** [comment]
> I meet the same issue, and get the same msg: 
> urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
> 
> But there is a websit can still find the real URL of bilibili's video from the URL of bilibili's page. The websit is bili.iiilab.com.

Actually,Downkyi is still working,but I just like the feeling using you-get in cmd window.It's cooler than using Downkyi,just my individual opinion:)

**Comment by sorfans1** [comment]
> > I meet the same issue, and get the same msg:
> > urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
> > But there is a websit can still find the real URL of bilibili's video from the URL of bilibili's page. The websit is bili.iiilab.com.
> 
> Actually,Downkyi is still working,but I just like the feeling using you-get in cmd window.It's cooler than using Downkyi,just my individual opinion:)
Yes, it feels like you-get is more free.

**Comment by sorfans1** [comment]
> > I meet the same issue, and get the same msg:
> > urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
> > But there is a websit can still find the real URL of bilibili's video from the URL of bilibili's page. The websit is bili.iiilab.com.
> 
> Actually,Downkyi is still working,but I just like the feeling using you-get in cmd window.It's cooler than using Downkyi,just my individual opinion:)

Yes, it feels like you-get is more free.

**Comment by ljhcage** [comment]
可以只是简单地将报错的那几行注释规避一下，现在所需要的音视频链接B站已经直接放到html里面了，不用再通过ajax获取
```git
diff --git a/src/you_get/extractors/bilibili.py b/src/you_get/extractors/bilibili.py
index 6335e6d..160b713 100644
--- a/src/you_get/extractors/bilibili.py
+++ b/src/you_get/extractors/bilibili.py
@@ -279,10 +279,10 @@ class Bilibili(VideoExtractor):
                         message = api_playinfo['data']['message']
                 if best_quality is None or qn <= best_quality:
                     api_url = self.bilibili_interface_api(cid, qn=qn)
-                    api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
-                    api_playinfo_data = json.loads(api_content)
-                    if api_playinfo_data.get('quality'):
-                        playinfos.append({'code': 0, 'message': '0', 'ttl': 1, 'data': api_playinfo_data})
+                    # api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
+                    # api_playinfo_data = json.loads(api_content)
+                    # if api_playinfo_data.get('quality'):
+                    #     playinfos.append({'code': 0, 'message': '0', 'ttl': 1, 'data': api_playinfo_data})
             if not playinfos:
                 log.w(message)
                 # use bilibili error video instead
```

**Comment by q629988171** [comment]
> 可以只是简单地将报错的那几行注释规避一下，现在所需要的音视频链接B站已经直接放到html里面了，不用再通过ajax获取
> 
> ```
> diff --git a/src/you_get/extractors/bilibili.py b/src/you_get/extractors/bilibili.py
> index 6335e6d..160b713 100644
> --- a/src/you_get/extractors/bilibili.py
> +++ b/src/you_get/extractors/bilibili.py
> @@ -279,10 +279,10 @@ class Bilibili(VideoExtractor):
>                          message = api_playinfo['data']['message']
>                  if best_quality is None or qn <= best_quality:
>                      api_url = self.bilibili_interface_api(cid, qn=qn)
> -                    api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
> -                    api_playinfo_data = json.loads(api_content)
> -                    if api_playinfo_data.get('quality'):
> -                        playinfos.append({'code': 0, 'message': '0', 'ttl': 1, 'data': api_playinfo_data})
> +                    # api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
> +                    # api_playinfo_data = json.loads(api_content)
> +                    # if api_playinfo_data.get('quality'):
> +                    #     playinfos.append({'code': 0, 'message': '0', 'ttl': 1, 'data': api_playinfo_data})
>              if not playinfos:
>                  log.w(message)
>                  # use bilibili error video instead
> ```

**Comment by NaicihLiou** [comment]
> -                    api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
> -                    api_playinfo_data = json.loads(api_content)
> -                    if api_playinfo_data.get('quality'):
> -                        playinfos.appen

Hi It's working but there is a problem that the higher video quality is failed to fetched. Do you have the same issue after commenting those lines?

**Comment by q629988171** [comment]
> Hi It's working but there is a problem that the higher video quality is failed to fetch. Do you have the same issue after commenting those lines?

you-get via the --cookies/-c option.

**Comment by NaicihLiou** [comment]
Thank you for the reply. Updating the cookies file works!

**Comment by sorfans1** [comment]
> 可以只是简单地将报错的那几行注释规避一下，现在所需要的音视频链接B站已经直接放到html里面了，不用再通过ajax获取
> 
> ```
> diff --git a/src/you_get/extractors/bilibili.py b/src/you_get/extractors/bilibili.py
> index 6335e6d..160b713 100644
> --- a/src/you_get/extractors/bilibili.py
> +++ b/src/you_get/extractors/bilibili.py
> @@ -279,10 +279,10 @@ class Bilibili(VideoExtractor):
>                          message = api_playinfo['data']['message']
>                  if best_quality is None or qn <= best_quality:
>                      api_url = self.bilibili_interface_api(cid, qn=qn)
> -                    api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
> -                    api_playinfo_data = json.loads(api_content)
> -                    if api_playinfo_data.get('quality'):
> -                        playinfos.append({'code': 0, 'message': '0', 'ttl': 1, 'data': api_playinfo_data})
> +                    # api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
> +                    # api_playinfo_data = json.loads(api_content)
> +                    # if api_playinfo_data.get('quality'):
> +                    #     playinfos.append({'code': 0, 'message': '0', 'ttl': 1, 'data': api_playinfo_data})
>              if not playinfos:
>                  log.w(message)
>                  # use bilibili error video instead
> ```

管用！！！

**Comment by whu-feng** [comment]
> > 可以只是简单地将报错的那几行注释规避一下，现在所需要的音视频链接B站已经直接放到html里面了，不用再通过ajax获取
> > ```
> > diff --git a/src/you_get/extractors/bilibili.py b/src/you_get/extractors/bilibili.py
> > index 6335e6d..160b713 100644
> > --- a/src/you_get/extractors/bilibili.py
> > +++ b/src/you_get/extractors/bilibili.py
> > @@ -279,10 +279,10 @@ class Bilibili(VideoExtractor):
> >                          message = api_playinfo['data']['message']
> >                  if best_quality is None or qn <= best_quality:
> >                      api_url = self.bilibili_interface_api(cid, qn=qn)
> > -                    api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
> > -                    api_playinfo_data = json.loads(api_content)
> > -                    if api_playinfo_data.get('quality'):
> > -                        playinfos.append({'code': 0, 'message': '0', 'ttl': 1, 'data': api_playinfo_data})
> > +                    # api_content = get_content(api_url, headers=self.bilibili_headers(referer=self.url))
> > +                    # api_playinfo_data = json.loads(api_content)
> > +                    # if api_playinfo_data.get('quality'):
> > +                    #     playinfos.append({'code': 0, 'message': '0', 'ttl': 1, 'data': api_playinfo_data})
> >              if not playinfos:
> >                  log.w(message)
> >                  # use bilibili error video instead
> > ```

有点儿意思，能用了，大神！

**Comment by jingedawang** [comment]
Why is it closed rather than open to merge? Is this repo abandoned?

**Pull request closed without merging**
