### PR TITLE
Fixed tiktok extraction

### PR DESCRIPTION
**Pull request by dougbenham**
Cookie needed to be updated for the final video grab

### CODE REVIEW

**Comment by dougbenham** [comment]
It appears they also just added captcha.

**Comment by soimort** [comment]
> It appears they also just added captcha.

Does the current `develop` branch work for you?

**Comment by soimort** [comment]
@soimort-bot test this: https://www.tiktok.com/@davidbeckham/video/6773212038953979141

**Comment by dougbenham** [comment]
> 
> 
> > It appears they also just added captcha.
> 
> Does the current `develop` branch work for you?

Yes it works.

**Pull request closed without merging**
