### PR TITLE
Refactoring of Bilibili extractor

### PR DESCRIPTION
**Pull request by soimort**
This PR entails a complete rewrite of the `bilibili.py` extractor. The following features are supported by the new extractor. (some URL patterns were already supported by the old extractor, some are new)

1. DASH/m4s streams support. Downloading DASH streams are generally faster than legacy FLV files, and they provide more choices of formats. Relevant format codes are:
    * `dash-flv` (1080P)
    * `dash-flv720`
    * `dash-flv480`
    * `dash-flv360`
   Note that only relatively newly uploaded videos come with DASH streams, though.
2. Regular Bilibili av videos. If a video page contains multiple parts, you-get will show a warning so that you won't miss any part. Use `-l` to download them all.
Example patterns:
    * https://www.bilibili.com/video/av43599036
    * https://www.bilibili.com/video/av22195308/?p=3
3. "watchlater" URLs. Example patterns:
    * https://www.bilibili.com/watchlater/#/av39902744/p1
4. Bilibili bangumi. Use `-l` to download all available episodes. Example patterns:
    * https://www.bilibili.com/bangumi/play/ss835
    * https://www.bilibili.com/bangumi/play/ep15014
    * https://bangumi.bilibili.com/anime/1660/play
    * https://bangumi.bilibili.com/movie/12044
5. Bilibili bangumi playlists. Example patterns:
    * https://www.bilibili.com/bangumi/media/md1660
    * https://bangumi.bilibili.com/anime/1660
6. User channels, fav lists, and uploads. Example patterns:
    * https://space.bilibili.com/64169458/channel/detail?cid=58383
    * https://space.bilibili.com/64169458/favlist?fid=1840043
    * https://space.bilibili.com/64169458/video
7. Bilibili 小视频. Example patterns:
    * https://vc.bilibili.com/video/1230491
8. Bilibili live streams. Example patterns:
    * https://live.bilibili.com/425
    * https://live.bilibili.com/1329719
9. Bilibili audios and playlists. Example patterns:
    * https://www.bilibili.com/audio/au639116
    * https://www.bilibili.com/audio/am28769204

In case there are problematic URLs or other patterns not supported yet, you may simply comment on this thread.

### CODE REVIEW

**Comment by simonfire007** [comment]
download is working,but `use you-get -p vlc url `play is failed.

` you-get -p vlc https://www.bilibili.com/video/av44429269 --debug
[DEBUG] get_content: https://www.bilibili.com/video/av44429269
[DEBUG] get_content: https://www.bilibili.com/video/av44429269
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=77840547&otype=json&qn=80&quality=80&type=&sign=913d040419c10bdc1bd7590c63abf76b
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=77840547&otype=json&qn=64&quality=64&type=&sign=6c002c6802f5e99c4000c7fa91994963
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=77840547&otype=json&qn=32&quality=32&type=&sign=1fdb5f7b6975b5c45bd1afc251fc845d
[DEBUG] get_content: https://api.bilibili.com/x/player/playurl?avid=44429269&cid=77840547&qn=16&type=&otype=json&fnver=0&fnval=16
[DEBUG] get_content: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=77840547&otype=json&qn=16&quality=16&type=&sign=87435b8faad235a2c67c9cb96e26fb94
[DEBUG] get_content: http://comment.bilibili.com/77840547.xml
site:                Bilibili
title:               2018最强神展开动画！结局出乎意料！观众看完直接疯狂了！
stream:
    - format:        flv
      container:     flv
      quality:       高清 1080P
      size:          149.1 MiB (156365474 bytes)
    # download-with: you-get --format=flv [URL]

VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332)
[0000557d67fb2580] main libvlc: 正在以默认界面运行 vlc。使用“cvlc”可以无界面模式使用 vlc。
[00007f21800019f0] access stream error: HTTP 453 error
[00007f21800019f0] http stream error: error: HTTP/1.1 453 

`

**Comment by soimort** [comment]
@simonfire007 You need to pass the HTTP referer to the player. This can't be implemented in you-get since the required argument varies for different players. For `mpv` it's

```
$ you-get -p "mpv --http-header-fields='Referer: https://www.bilibili.com/video/av44429269'" https://www.bilibili.com/video/av44429269
```

I don't know about vlc though.

**Comment by simonfire007** [comment]
@soimort  I got it,thank you  for your reply。

**Comment by BraveDrXuTF** [comment]
How do i download audio only, not video content from website?

**Pull request merged**
