### PR TITLE
Update douyutv.py

### PR DESCRIPTION
**Pull request by Justsoos**
douyu update

### CODE REVIEW

**Comment by asdyjd** [comment]
It still doesn't work

**Comment by Justsoos** [comment]
works very well, for me:

```
# you-get -du https://www.douyu.com/kpc
[DEBUG] get_content: https://m.douyu.com/room/kpc
[DEBUG] get_content: http://www.douyutv.com/api/v1/room/252802?aid=wp&client_sys=wp&time=1529996750&auth=3e22bea42f4391fdf921af5c111a991f
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Site:       douyu.com
Title:      【贝爷影厅】经典 科幻 动作 巨兽 灾难
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

User Agent: Python-urllib/3.5
Real URL:
['http://hdla.douyucdn.cn/live/252802rbQGaZXUQi.flv?wsAuth=140d2bae6f8b887db02aed76b48af1ed&token=app-wp-0-252802-8692a32f732113a364fd0973e1a72a56&logo=0&expire=0&pt=1'] 
```

**Comment by asdyjd** [comment]
Why I always got this?
`E:\Downloads>you-get -du https://www.douyu.com/kpc
[DEBUG] get_content: https://m.douyu.com/kpc
[DEBUG] get_content: http://www.douyutv.com/api/v1/room/None?aid=wp&client_sys=wp&time=1530003759&auth=c2dec12c2aa08470aa4985b929daf434
[DEBUG] HTTP Error with code404
[DEBUG] HTTP Error with code404
[DEBUG] HTTP Error with code404
you-get: version 0.4.1077, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.douyu.com/kpc'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=True, version=False)
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.1077', 'console_scripts', 'you-get')()
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\__main__.py", line 92, in main
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\common.py", line 1623, in main
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\common.py", line 1507, in script_main
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\common.py", line 1242, in download_main
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\common.py", line 1614, in any_download
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\extractors\douyutv.py", line 61, in douyutv_download
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\common.py", line 416, in get_content
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\common.py", line 394, in urlopen_with_retry
  File "d:\anaconda3\lib\site-packages\you_get-0.4.1077-py3.6.egg\you_get\common.py", line 385, in urlopen_with_retry
  File "D:\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "D:\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "D:\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\Anaconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by asdyjd** [comment]
I know where the problem is right now.
Thank you!

**Comment by soimort** [comment]
:ok_hand:

**Comment by willshion** [comment]
you-get https://www.douyu.com/4903479 -d
[DEBUG] get_content: https://m.douyu.com/room/4903479
[DEBUG] get_content: http://www.douyutv.com/api/v1/room/4903479?aid=wp&client_sys=wp&time=1555057234&auth=112a8edcb822b755554d8f20837fdc8a
[DEBUG] HTTP Error with code401
[DEBUG] HTTP Error with code401
[DEBUG] HTTP Error with code401
you-get: version 0.4.1270, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.douyu.com/4903479'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1733, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1621, in script_main
    **extra
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1284, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1724, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\douyutv.py", line 61, in douyutv_download
    content = get_content(json_request_url, headers)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 434, in get_content
    response = urlopen_with_retry(req)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 412, in urlopen_with_retry
    raise http_error
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 403, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Pull request merged**
