### PR TITLE
[common] url_info should not ignore refer when called in url_save

### PR DESCRIPTION
**Pull request by rosynirvana**
#1942

details are in the following discussion.

### CODE REVIEW

**Comment by soimort** [comment]
Why not:

```py
if refer:
    headers['referer'] = refer
file_size = url_size(url, faker = faker, headers = headers)
```

If `refer` is specified, it will be preferred rather than `headers['referer']` anyway. There's no need to keep the old value.

**Comment by rosynirvana** [comment]
keys in headers are case insenstive by RFC so it can be Referer, REFERER.

**Comment by soimort** [comment]
`headers` are provided by our side. Sticking with one convention (say, `headers['Referer']`) is fair enough. Moreover, `headers` will be used over and over again ([common.py#L529-534](https://github.com/soimort/you-get/blob/058d2797c5a8e1221cbe30e2a7240918b5b01c38/src/you_get/common.py#L529_L534)), while `new_headers` is just a one-time hack (simply works for `url_size()`).

**Comment by rosynirvana** [comment]
I see.

**Comment by soimort** [comment]
👌

**Pull request merged**
