### PR TITLE
download endless

### PR DESCRIPTION
**Pull request by ljj038**
you-get -s 127.0.0.1:1080 'https://youtu.be/zakvqx-BVeo' --debug
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=zakvqx-BVeo&eurl=https%3A%2F%2Fy
[DEBUG] STATUS: ok
[DEBUG] get_content: https://www.youtube.com/watch?v=zakvqx-BVeo
[DEBUG] get_content: https://www.youtube.com/api/timedtext?v=zakvqx-BVeo&asr_langs=de,en,es,fr,it,ja,ko,nl,pt,ru&caps=asr&xorp=true&hl=zh-HK&ip=0.0.0.0&ipbits=0&expire=1579277148&sparams=ip,ipbits,expire,v,asr_langs,caps,xorp&signature=C862AF697CFA8D17B246B1532851C09580D7BC3C.1BDD5580107189F777EB5F32CA499B76ECBD2E8D&key=yt8&kind=asr&lang=en
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player_ias-vflmIM8j8/zh_HK/base.js
site:                YouTube
title:               Pushing Pixels with Lisp - Episode 32 - Daft 2D Engine (Part 5)
stream:
    - itag:          248
      container:     webm
      quality:       1920x1080 (1080p)
      size:          851.0 MiB (892335088 bytes)
    # download-with: you-get --itag=248 [URL]

Downloading Pushing Pixels with Lisp - Episode 32 - Daft 2D Engine (Part 5).webm ...
 100% (**852.3**/_851.0MB_) ├███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/2]  807 kB/s

### CODE REVIEW

**Comment by soimort** [comment]
This is most likely because the proxy (i.e. Shadowsocks) does not return a proper Content-Length field. I encountered the same problem last year, but never managed to find the cause.

**Comment by ljj038** [comment]
@soimort thanks for your explain. sometimes when I try download the same video again. it will be OK.
but this video is too big, I tried many times and still download endless. so I pulled this request.

maybe it is because of the proxy, not you-get.

**Comment by soimort** [comment]
Ideally you-get should terminate whenever it received the expected amount of bytes, but there is no guarantee for the integrity of received data, I guess.

**Comment by ljj038** [comment]
- title:         Pushing Pixels with Lisp - Episode 49 - Normal Mapping
       size:         1656.7 MiB (1737151977 bytes)
        url:         https://youtu.be/MxSHmQuuW60

Downloading Pushing Pixels with Lisp - Episode 49 - Normal Mapping.mp4 ...
92.0% (1524.2/1656.7MB) ├███████████████████████████████████───┤[1/2]  696 kB/s


```bash
ls -lh *49*
-rw-r--r-- 1 king king 1.5G Jan 19 10:42 'Pushing Pixels with Lisp - Episode 49 - Normal Mapping[00].mp4'
-rw-r--r-- 1 king king 3.4M Jan 19 10:53 'Pushing Pixels with Lisp - Episode 49 - Normal Mapping[01].mp4.download'
```


@soimort  it stack at the second part of the video. if I Ctrl+C. and then start again, will it start over or just download the second part?  

I think I tried before, it will start over.

can we test if the first part is totally downloaded, and just download the not finished part?

**Comment by ljj038** [comment]
```bash
 - title:         Pushing Pixels with Lisp - Episode 49 - Normal Mapping
       size:         1656.7 MiB (1737151977 bytes)
        url:         https://youtu.be/MxSHmQuuW60

Downloading Pushing Pixels with Lisp - Episode 49 - Normal Mapping.mp4 ...
92.0% (1524.2/1656.7MB) ├███████████████████████████████████───┤[1/2]  696 kB/s
96.2% (1594.3/1656.7MB) ├█████████████████████████████████████─┤[2/2]    2 MB/s
 100% (1698.1/1656.7MB) ├██████████████████████████████████████┤[2/2]   92 kB/s
```

```bash
-rw-r--r-- 1 king king 1.5G Jan 19 10:42 'Pushing Pixels with Lisp - Episode 49 - Normal Mapping[00].mp4'
-rw-r--r-- 1 king king 174M Jan 19 11:08 'Pushing Pixels with Lisp - Episode 49 - Normal Mapping[01].mp4.download'
```

it endless again

**Pull request closed without merging**
