### PR TITLE
Support for tumblr-hosted videos.

### PR DESCRIPTION
**Pull request by sleaze**
Support for tumblr-hosted videos.

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/942)

### CODE REVIEW

**Comment by soimort** [comment]
Any examples for testing? thanks!

**Comment by sleaze** [comment]
Unfortunately all I can find are pornographic accounts hosting these videos.

I'm not sure an example link would be welcome here on GH..

**Comment by sleaze** [comment]
Oh well, I am sleaze.

Here's a good example:

http://rolepay.tumblr.com/post/139933149818/this-is-fucking-insane-wait-till-the-end-i

**Comment by soimort** [comment]
Enough. You may use NSFW links as examples, as long as you gives a warning in advance.

Thanks for the contribution.

**Pull request merged**
