### PR TITLE
[pptv]refactor

### LINKED ISSUE #1439: PPTV只能解析最低清晰度
Please make sure these boxes are checked before submitting your issue – thank you!
- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read https://github.com/soimort/you-get/wiki/FAQ and tried to do so.
- [x] The issue is not yet reported on https://github.com/soimort/you-get/issues or  https://github.com/soimort/you-get/wiki/Known-Bugs. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!
- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 https://github.com/soimort/you-get/wiki/FAQ 中的指引进行了操作.
- [x] 您的问题没有在https://github.com/soimort/you-get/issues , https://github.com/soimort/you-get/wiki/FAQ 或 https://github.com/soimort/you-get/wiki/Known-Bugs 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
root@SDS:~# you-get -y 124.88.67.32:81 -i --debug http://v.pptv.com/show/9UebGK2icpuRHxS0.html
Site:       PPTV.com
Title:      我太受欢迎了该怎么办(第01集)
Type:       MPEG-4 video (video/mp4)
Size:       84.780000000000001 MiB (88895350 Bytes)
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> 在 http://www.flvurl.cn/ 这个网站可以解析全部清晰度，但you-get只能解析到最低的清晰度

### PR DESCRIPTION
**Pull request by rosynirvana**
```
$  ./you-get -d -i http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2
[DEBUG] get_content: http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2
[DEBUG] get_content: http://web-play.pptv.com/webplay3-0-17285316.xml?type=web.fpp&version=4
site:                PPTV
title:               金玉良缘(第01集)
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        4
      container:     mp4
      video-profile: 1920x1072@6038kbps
      size:          1964.8 MiB (2060200621 bytes)
    # download-with: you-get --format=4 [URL]

    - format:        3
      container:     mp4
      video-profile: 1920x1072@2329kbps
      size:          757.9 MiB (794703362 bytes)
    # download-with: you-get --format=3 [URL]

    - format:        2
      container:     mp4
      video-profile: 1280x712@1054kbps
      size:          343.3 MiB (359971308 bytes)
    # download-with: you-get --format=2 [URL]

    - format:        1
      container:     mp4
      video-profile: 720x400@450kbps
      size:          146.7 MiB (153830232 bytes)
    # download-with: you-get --format=1 [URL]

    - format:        0
      container:     mp4
      video-profile: 480x268@330kbps
      size:          107.4 MiB (112652120 bytes)
    # download-with: you-get --format=0 [URL]
```

fix #1439 #1611 #1695 #1831 #1957 #2024

### CODE REVIEW

**Comment by skywang00** [comment]
为什么只能解析到480P的？就算是网页播放都可以直接720P的呀

**Comment by Realmyname** [comment]
get_html('http://web-play.pptv.com/webplay3-0-%s.xml?type=web.fpp' % id)改为
get_html('http://web-play.pptv.com/webplay3-0-%s.xml?type=web.fpp&version=4' % id)
应该就能获取到其他码率了

**Comment by skywang00** [comment]
@Realmyname 

version=3 或者 version=4 都会得到错误的版本，无法下载，正常应该是大概2G的版本

> PS C:\Users\XXX> you-get -d -i http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2
> [DEBUG] get_response: http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2
> [DEBUG] get_response: http://web-play.pptv.com/webplay3-0-17285316.xml?type=web.fpp&version=3
> Site:       PPTV.com
> Title:      金玉良缘(第01集)
> Type:       MPEG-4 video (video/mp4)
> Size:       3344.12 MiB (3506562861 Bytes)

**Comment by Realmyname** [comment]
http://web-play.pptv.com/webplay3-0-17285316.xml?type=atv&version=4
主要信息：
<file cur="1">
<item rid="b91c747539bb3b49f8c17f3918daa5a2.mp4" bitrate="330" vip="0" ft="0" filesize="112652120" width="480" height="268" format="h264"/>
<item rid="176df833d366d8c1e8c7683564df8fab.mp4" bitrate="450" vip="0" ft="1" filesize="153830232" width="720" height="400" format="h264"/>
<item rid="f7d75bf6c39a3c9cb233afb48c7bc6dc.mp4" bitrate="1054" vip="0" ft="2" filesize="359971308" width="1280" height="712" format="h264"/>
<item rid="6c191ecebe2b8b1bd4f8b48260bbc13d.mp4" bitrate="2329" vip="1" ft="3" filesize="794703362" width="1920" height="1072" format="h264"/>
<item rid="1ed4f7f14099cff6a291a966871883bf.mp4" bitrate="6038" vip="1" ft="4" filesize="2060200621" width="1920" height="1072" format="h264"/>
</file>

<dt ft="0">
<sh>111.7.164.196</sh>
<st>Fri May 26 10:28:49 2017 UTC</st>
<id>fd6023497bbfebe750101795dc8eb6cb</id>
<bwt>0</bwt>
<bh>122.72.27.248</bh>
<key expire="Fri May 26 14:29:49 2017 UTC">
1fc75e6729c6825115043f7659658f7f-ad82-1495808989%26bppcataid%3D9
</key>


<dt ft="1">
<sh>111.7.164.200</sh>
<st>Fri May 26 10:28:49 2017 UTC</st>
<id>a9b82c7913804216ad35b470eb6a72e1</id>
<bwt>0</bwt>
<bh>122.72.27.250</bh>
<key expire="Fri May 26 14:29:49 2017 UTC">
a1ae62b33d1878bf34b8a7e522b3f429-ad82-1495808989%26bppcataid%3D9
</key>

<dt ft="2">
<sh>111.7.164.196</sh>
<st>Fri May 26 10:28:49 2017 UTC</st>
<id>cabddefb00f60e30c4774ca30f19bf20</id>
<bwt>0</bwt>
<bh>122.72.27.249</bh>
<key expire="Fri May 26 14:29:49 2017 UTC">
ef95cf614f9501d6cbe3527f7ee7c06b-ad82-1495808989%26bppcataid%3D9
</key>

<dt ft="3">
<sh>111.7.164.202</sh>
<st>Fri May 26 10:28:49 2017 UTC</st>
<id>71dd03e310fd16cfd89afdbeab9c65b6</id>
<bwt>0</bwt>
<bh>122.72.27.248</bh>
<key expire="Fri May 26 14:29:49 2017 UTC">
7d4c479b1d129ba0996148cd4369d944-ad82-1495808989%26bppcataid%3D9
</key>

<dt ft="4">
<sh>111.7.164.201</sh>
<st>Fri May 26 10:28:49 2017 UTC</st>
<id>14a52d1c34dbfb3f6936a526cac14040</id>
<bwt>0</bwt>
<bh>122.72.27.248</bh>
<key expire="Fri May 26 14:29:49 2017 UTC">
d1964acaa84d494d41cb78586af54474-ad82-1495808989%26bppcataid%3D9
</key>
<kernel>

{
    "title": "金玉良缘(第01集)",
    "code": "200",
    "url": [
        "http://111.7.164.204/b91c747539bb3b49f8c17f3918daa5a2.mp4?type=atv&w=1&k=723b88418dd26db9f05cec18a2029cd2-e273-1495809245%26bppcataid%3D9",
        "http://111.7.164.196/176df833d366d8c1e8c7683564df8fab.mp4?type=atv&w=1&k=e52c8e5b51c47404cbf54c88d6d83143-e273-1495809245%26bppcataid%3D9",
        "http://111.7.164.202/f7d75bf6c39a3c9cb233afb48c7bc6dc.mp4?type=atv&w=1&k=1640b1a850c406a18a0983fd6497c413-e273-1495809245%26bppcataid%3D9",
        "http://111.7.164.203/6c191ecebe2b8b1bd4f8b48260bbc13d.mp4?type=atv&w=1&k=d6a5efdd9947e0ed9f228fb3a3df39c0-e273-1495809245%26bppcataid%3D9",
        "http://111.7.164.201/1ed4f7f14099cff6a291a966871883bf.mp4?type=atv&w=1&k=0af85f91b889a27204d34f68155f4feb-e273-1495809245%26bppcataid%3D9"
    ]
}

python 不知道该咋写

**Comment by Realmyname** [comment]
或者：
http://web-play.pptv.com/webplay3-0-17285316.xml?type=&version=4

url = ......mp4?type=&w=1&k=

**Comment by rosynirvana** [comment]
为啥不去issue下面讨论
这个pull request是为了修那个明显错误的正则

**Comment by Realmyname** [comment]
才玩github，不太懂

**Comment by rosynirvana** [comment]
@skywang00
现在可以了
麻烦把已经过期的回复删掉吧

**Comment by soimort** [comment]
:+1:

**Comment by junges521** [comment]
pptv 还是不行

**Pull request merged**
