### PR TITLE
Fix the problem "urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>"

### PR DESCRIPTION
**Pull request by SMILEORIGIN**
## Fix Problem
I found this problem when i using this command `you-get -i 'https://www.youtube.com/watch?v=jNQXAC9IVRw' --debug` 
Here is the wrong information:
```python
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
```
## Solution
Close the global SSL certificate verify in `/you-get/src/you_get/__main__.py`

### CODE REVIEW

**Comment by soimort** [comment]
Disabling certificate verification globally would be a backward move in terms of security (on Python 3.4 and above), since it brings in potential vulnerability when users pass cookies or passwords over HTTPS -- they won't be secure anymore.

I understand that sometimes people want to have untrusted certificates for obscure reasons (like bypassing firewalls via HTTP proxies); but a more proper solution is to make that optional (with some option like `--no-check-certificate`).

**Comment by jaszou** [comment]
Youtube Music Premium 无法下载
you-get -x 127.0.0.1:1080 -c  "D:\cookies.sqlite" -i https://www.youtube.com/watch?v=-MIOABwKSpE
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by zingwin** [comment]
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzk3OTExMDU3Mg==&ccode=0590&client_ip=192.168.1.1&utid=xnS0FPpe6H0CAa8GFwc4IAQZ&client_ts=1546487496&ckey=DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd%2BWOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3%2Bnb0v72gZ6b0td%2BWOZsHHWxysSo/0y9D2K42SaB8Y/%2BaD2K42SaB8Y/%2BahU%2BWOZsHcrxysooUeND
you-get: version 0.4.1193, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://v.youku.com/v_show/id_XMzk3OTExMDU3Mg==.html?spm=a2h0j.11185381.listitem_page2.5~A&&s=131b1cefbfbdefbfbd73'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1645, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1533, in script_main
    **extra
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1268, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 1636, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractors/youku.py", line 309, in youku_download_by_url
    Youku().download_by_url(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractor.py", line 46, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractors/youku.py", line 169, in prepare
    self.youku_ups()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/extractors/youku.py", line 97, in youku_ups
    api_meta = json.loads(get_content(url, headers=headers))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 421, in get_content
    response = urlopen_with_retry(req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/you_get/common.py", line 390, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
zingwindeMBP:Desktop zingwin$ you-get 'https://v.youku.com/v_show/id_XMzk3OTExMDU3Mg==.html?spm=a2h0j.11185381.listitem_page2.5~A&&s=131b1cefbfbdefbfbd73'

**Comment by Rhythmicc** [comment]
add following code in file “__main__.py” to solve CERTIFICATE_VERIFY_FAILED problem:
`
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
`

**Comment by onelizi** [comment]
> add following code in file '**main**.py' to solve CERTIFICATE_VERIFY_FAILED problem: `import ssl; ssl._create_default_https_context = ssl._create_unverified_context`

Thanks Bro

**Pull request closed without merging**
