### PR TITLE
Test on Python 3.10

### PR DESCRIPTION
**Pull request by cclauss**
“3.10” must be quoted or yaml will treat it as 3.1.

### CODE REVIEW

**Comment by onlyoneyouyi** [comment]
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

how can solve the problem,thanks you

**Comment by nohavana** [comment]
> you-get: don't panic, c'est la vie. please try the following steps: you-get: (1) Rule out any network problem. you-get: (2) Make sure you-get is up-to-date. you-get: (3) Check if the issue is already known, on you-get: https://github.com/soimort/you-get/wiki/Known-Bugs you-get: https://github.com/soimort/you-get/issues you-get: (4) Run the command with '--debug' option, you-get: and report this issue with the full output.
> 
> how can solve the problem,thanks you

臣附议。Same To Me. On Download from BiliBili

**Comment by soimort** [comment]
Cool, thanks :+1:

**Comment by Inc0n** [comment]
you-get does not work on 3.10, see https://github.com/aio-libs/aiohttp/issues/6327.

It complains about ssl with `--debug`:
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

This comment https://github.com/aio-libs/aiohttp/issues/6327#issuecomment-974337338 has an explanation for this, a solution is suggested here https://github.com/aio-libs/aiohttp/issues/955#issuecomment-568425975.

**Comment by cclauss** [comment]
@Inc0n Given that all the issues mentioned in your comment were closed three years ago, please add a failing test to this repo's [GitHub Actions](https://github.com/soimort/you-get/actions) so that we can all see what you are seeing.

**Comment by Inc0n** [comment]
Thanks for a hasty respond, however, the issue in question https://github.com/aio-libs/aiohttp/issues/6327, is from Nov 2021.

I am do not know how to use github actions. So I am afraid your specific request cannot be made happen.

Since I manage to get ahold someone, the FAQ actually do have my issue covered, however, link #1710 is dead:
 
> Q: I got ````ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed```?
> A: Kindly refer to #1710 .

**Comment by cclauss** [comment]
> @[Dreamsorcerer](https://github.com/Dreamsorcerer) Dreamsorcerer closed this as [completed](https://github.com/aio-libs/aiohttp/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [on 19 Nov 2021](https://github.com/aio-libs/aiohttp/issues/6327#event-5647255853)

Closed as complete in 2021.  Sorry for my mistake.

**Pull request merged**
