### PR TITLE
更新斗鱼api

### PR DESCRIPTION
**Pull request by simonfire007**
我的英语不好，所以就不写英语了，还有就是对gihub也不熟悉，完全是一个新手，所以，不当之处，大家海涵。
代码是根据

> https://github.com/xjbeta/iina-plus/blob/master/iina+/Utils/VideoGet.swift

改写而来，目前是可用的，需要用到requests_html库来执行js函数获取sign，期间要下载Chromium ，国内用户需要代理或自行想其他办法。
我的Python也是新手水平，代码很烂，所以没有更好的办法，最好是有人把代码改写一下，更好地实现。

sign获取是ub98484234(room_id,did,time)这个js函数,在斗鱼页面源码里就有，高手看看能不能用Python来实现。
这个函数在https://www.douyu.com/swf_api/homeH5Enc?rids=(roomID)页面也能获取

最后，感谢you-get这个项目，让我等可以方便的观看、下载视频。

### CODE REVIEW

**Comment by wordlesswind** [comment]
请问“期间要下载Chromium”是什么意思？

**Comment by wordlesswind** [comment]
此方法不适用于 ARM 设备，因为Chromium Team没有直接提供ARM的Chromium。

**Comment by Justsoos** [comment]
用浏览器模拟等于对斗鱼算法投降了，只能算暂时的。
arm也能上浏览器，但相当多问题，谷歌的开发貌似因商业竞争性的不给arm作dev版本…
这里在集中破解算法，有兴趣去围观：
https://github.com/streamlink/streamlink/issues/2328#issuecomment-469005188
另外，给猫吃巧克力冰棍，有毒，猫会死 😂
screenshot_20190304042438

**Comment by simonfire007** [comment]
> 这soimort态度真牛逼，关了issues，我Pull requests发帖反馈问题，直接关贴完全不理会，我又问他为啥，他直接封人。做个youget就飘上天了？

兄弟，这就是你的不对了。你可以反馈，但人家不是非得回复解决呀，可能你反馈的那块正好是不再维护的部分，或者根本是你使用的问题，而不是项目本身的问题。总之，你这不依不饶的风格需要改一下了，你现在又在这回复完全不相关的问题，说不定人家关issues就是这种情况碰到太多，没办法才关的，做人不要只想着自己。

**Comment by willshion** [comment]
you-get https://www.douyu.com/4903479 -d
[DEBUG] get_content: https://m.douyu.com/room/4903479
[DEBUG] get_content: http://www.douyutv.com/api/v1/room/4903479?aid=wp&client_sys=wp&time=1555057234&auth=112a8edcb822b755554d8f20837fdc8a
[DEBUG] HTTP Error with code401
[DEBUG] HTTP Error with code401
[DEBUG] HTTP Error with code401
you-get: version 0.4.1270, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.douyu.com/4903479'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1733, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1621, in script_main
    **extra
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1284, in download_main
    download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1724, in any_download
    m.download(url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\douyutv.py", line 61, in douyutv_download
    content = get_content(json_request_url, headers)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 434, in get_content
    response = urlopen_with_retry(req)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 412, in urlopen_with_retry
    raise http_error
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 403, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by Tobyzgj** [comment]
Youku 201 does not have the right to play how to solve the problem？

**Comment by e788b1** [comment]
https://github.com/hr3lxphr6j/bililive-go
`
bililive --native-flv-parser -o ~/Downloads/douyu -i https://www.douyu.com/12345
`

**Pull request closed without merging**
