### PR TITLE
[Bilibili] download specified P according to the link

### PR DESCRIPTION
**Pull request by smart-techs**
I think the current behavior does not make sense. Sometimes I only want to download or play the specified P ,such as movie collection.

Can we do that according the link?
like that:
for http://www.bilibili.com/video/av3278560/index_1.html  , only download the first
for http://www.bilibili.com/video/av3278560/ ,download all parts
i'm a newcomer to python :)

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1192)

### CODE REVIEW

**Comment by soimort** [comment]
Looks good :+1: 

Would you mind amending the commit message to make it a more meaningful one?

**Comment by smart-techs** [comment]
@soimort Of course not!

**Comment by smart-techs** [comment]
@soimort Done.

**Comment by soimort** [comment]
Thanks for the contribution!

**Pull request merged**
