### PR TITLE
[youku] Update cccode

### PR DESCRIPTION
**Pull request by RogerFederer03**
Update cccode to 0510 for youku.py

Get from:

http://g.alicdn.com/player/ykplayer/0.5.28/youku-player.min.js

{"0505":"interior","050F":"interior","0501":"interior","0502":"interior","0503":"interior","0510":"adshow","0512":"BDskin","0590":"BDskin"}

Before the fix:
```
you-get --debug http://v.youku.com/v_show/id_XMzU5NjkxNTM1Ng==.html?spm=a2h0z.8244218.2371631.5
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzU5NjkxNTM1Ng==&ccode=0502&client_ip=192.168.1.1&utid=%2BoR%2BE7ve%2BDsCARi5QmohYOQw&client_ts=1526175486&ckey=DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd%2BWOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3%2Bnb0v72gZ6b0td%2BWOZsHHWxysSo/0y9D2K42SaB8Y/%2BaD2K42SaB8Y/%2BahU%2BWOZsHcrxysooUeND
you-get: 用户账户异常、请重新登录
```

After the fix:

```
you-get --debug http://v.youku.com/v_show/id_XMzU5NjkxNTM1Ng==.html?spm=a2h0z.8244218.2371631.5
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzU5NjkxNTM1Ng==&ccode=0510&client_ip=192.168.1.1&utid=IYV%2BE0QbrVcCARi5Qmqd6hjL&client_ts=1526175525&ckey=DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd%2BWOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3%2Bnb0v72gZ6b0td%2BWOZsHHWxysSo/0y9D2K42SaB8Y/%2BaD2K42SaB8Y/%2BahU%2BWOZsHcrxysooUeND
site:                优酷 (Youku)
title:               货币战争（下）：头号玩家
stream:
    - format:        mp4hd3v2
      container:     mp4
      video-profile: 1080P
      size:          567.0 MiB (594580265 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzU5NjkxNTM1Ng%3D%3D&type=hd3&ups_client_netip=18b9426a&utid=IYV%2BE0QbrVcCARi5Qmqd6hjL&ccode=0510&psid=b336626aa0973701c5248c01cfa2f3f8&duration=3071&expire=18000&drm_type=1&drm_device=7&ups_ts=1526175526&onOff=0&encr=0&ups_key=bcfaf87bad590f7a77bfa4ac5ffc8793
    # download-with: you-get --format=mp4hd3v2 [URL]
```

### CODE REVIEW

**Comment by RogerFederer03** [comment]
@edwardfang  Sounds good. Thanks for trying.

**Comment by soimort** [comment]
Thanks :+1:

**Comment by scegg** [comment]
not working here.

**Comment by scegg** [comment]
you-get --debug http://v.youku.com/v_show/id_XMzU5NjkxNTM1Ng==.html?spm=a2h0z.8244218.2371631.5 -i
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzU5NjkxNTM1Ng==&ccode=0502&client_ip=192.168.1.1&utid=7k2EE0W6ji4CAXQZ8yYyqOKV&client_ts=1526554617&ckey=DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd%2BWOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3%2Bnb0v72gZ6b0td%2BWOZsHHWxysSo/0y9D2K42SaB8Y/%2BaD2K42SaB8Y/%2BahU%2BWOZsHcrxysooUeND
you-get: 用户账户异常、请重新登录

**Comment by RogerFederer03** [comment]
@scegg , I double checked, it works for me.

```
you-get --debug http://v.youku.com/v_show/id_XMzU5NjkxNTM1Ng==.html?spm=a2h0z.8244218.2371631.5 -i
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzU5NjkxNTM1Ng==&ccode=0510&client_ip=192.168.1.1&utid=JlyEExxDk2MCARi5QmrlaaA9&client_ts=1526558249&ckey=DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd%2BWOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3%2Bnb0v72gZ6b0td%2BWOZsHHWxysSo/0y9D2K42SaB8Y/%2BaD2K42SaB8Y/%2BahU%2BWOZsHcrxysooUeND
site:                优酷 (Youku)
title:               货币战争（下）：头号玩家
streams:             # Available quality and codecs
    [ DEFAULT ] _________________________________
    - format:        mp4hd3v2
      container:     mp4
      video-profile: 1080P
      size:          567.0 MiB (594580265 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzU5NjkxNTM1Ng%3D%3D&type=hd3&ups_client_netip=18b9426a&utid=JlyEExxDk2MCARi5QmrlaaA9&ccode=0510&psid=fe9d0c9612e39807adb2ff40160d8630&duration=3071&expire=18000&drm_type=1&drm_device=7&ups_ts=1526558250&onOff=0&encr=0&ups_key=4515d563fff0897e61d5de2ac33bdcf2
    # download-with: you-get --format=mp4hd3v2 [URL]

    - format:        mp4hd2v2
      container:     mp4
      video-profile: 超清
      size:          313.3 MiB (328519347 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzU5NjkxNTM1Ng%3D%3D&type=hd2&ups_client_netip=18b9426a&utid=JlyEExxDk2MCARi5QmrlaaA9&ccode=0510&psid=fe9d0c9612e39807adb2ff40160d8630&duration=3071&expire=18000&drm_type=1&drm_device=7&ups_ts=1526558250&onOff=0&encr=0&ups_key=4515d563fff0897e61d5de2ac33bdcf2
    # download-with: you-get --format=mp4hd2v2 [URL]

   ...
```

**Comment by soimort** [comment]
@soimort-bot test this: http://v.youku.com/v_show/id_XMzU5NjkxNTM1Ng==.html?spm=a2h0z.8244218.2371631.5

**Comment by soimort** [comment]
@soimort-bot test this: http://v.youku.com/v_show/id_XMzU5NjkxNTM1Ng==.html

**Comment by scegg** [comment]
@RogerFederer03 Strange. I've pull the whole source to the latest. Youku is set to 0510 by default. Problem still. Maybe it's limited by IP area?

**Comment by RogerFederer03** [comment]
@scegg Maybe it is the IP region problem. I guess you can try some other values in 
```
{"0505":"interior","050F":"interior","0501":"interior","0502":"interior","0503":"interior","0510":"adshow","0512":"BDskin","0590":"BDskin"}
```

**Comment by scegg** [comment]
@RogerFederer03 
All tested. None works...

**Comment by scegg** [comment]
@RogerFederer03 
It's working on my Ubuntu system but not on Windows. Maybe something related to source cache of python.

**Pull request merged**
