### PR TITLE
Simplify logic via ternary if

### PR DESCRIPTION
**Pull request by cclauss**
Simplify logic via ternary if...  The () were required!!  Now passes tests.

---

This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1028)

### CODE REVIEW

**Comment by soimort** [comment]
1. Could you please remove all the instruction message, and add a short explanation why your patch should take place, instead?
2. From Travis, I can see that this change will break Python 3.2, 3.3 and 3.4 compatibility, syntactically.

**Comment by soimort** [comment]
Well, from what I (shallowly) understand, this patch shall make use of the [PEP 448](https://www.python.org/dev/peps/pep-0448/) implementation in **Python 3.5**. It is purely a syntactic addition, and it breaks compatibility with all previous Python versions. `you-get` is yet meant to be working across all major Python 3 versions, so we can't sacrifice all those *just for* a syntax sugar.

**Comment by cnbeining** [comment]
We are seeing lots of aggressive changes in Python 3.4 and 3.5. Let's wait until Python 3.4 dies...

**Comment by cclauss** [comment]
The () were required!! Now passes tests.

**Pull request closed without merging**
