### PR TITLE
mac下无法使用

### PR DESCRIPTION
**Pull request by zifeicsy**
mac下以前可以使用，现在无法使用。
在终端窗口输入一下命令
you-get 'https://www.bilibili.com/video/BV1Jg4y1Q74C/?spm_id_from=333.1007.tianma.1-2-2.click&vd_source=5dde80c3ed81d20cbf5260524061a1c7'

提示一下错误

you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

### CODE REVIEW

**Comment by pokeslog** [comment]
you-get -i https://www.bilibili.com/video/BV19N4y187oz?p=1
you-get: This is a multipart video. (use --playlist to download all parts.)
you-get: [error] oops, something went wrong.

I get the same errors.

**Comment by zifeicsy** [comment]
you have solved it ?

**Comment by pokeslog** [comment]
No I gave up since this hasn’t been updated in a year.   am using yt-get now.



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by zifeicsy** [comment]
> http://aka.ms/weboutlook
yt-get？ can you share a site to me？ 
Thanks

**Comment by UncoDong** [comment]
I believe that the solution is here https://github.com/soimort/you-get/pull/3017

**Pull request closed without merging**
