### PR TITLE
mgtv videos download failed

### PR DESCRIPTION
**Pull request by MC-dusk**
芒果TV http://www.mgtv.com 视频下载失败

--debug信息位于

- mgtv - debug1.txt
- mgtv - debug2.txt

### CODE REVIEW

**Comment by sinofool** [comment]
试一下最新的更改。

**Comment by MC-dusk** [comment]
I'm sorry, but it still doesn't work.
The debug info is almost the same, except the line number of code.

**Comment by HermanZzz** [comment]
doesn't work either

**Comment by HermanZzz** [comment]
`you-get --json 'https://www.mgtv.com/b/52389/669722.html' --debug
[DEBUG] get_content: http://pcweb.api.mgtv.com/player/video?video_id=669722
you-get: version 0.4.1500, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.mgtv.com/b/52389/669722.html'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=True, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/you-get", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1798, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1686, in script_main
    **extra
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1327, in download_main
    download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/common.py", line 1789, in any_download
    m.download(url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/mgtv.py", line 68, in prepare
    self.title = content['data']['info']['title']
KeyError: 'info'`

**Comment by sinofool** [comment]
Created another PR #2863 trying to fix both cases.

**Pull request closed without merging**
