### PR TITLE
[common zhanqi]m3u8 code in common; rewrite zhanqi

### PR DESCRIPTION
**Pull request by rosynirvana**
```
$ ./you-get -d 'https://www.zhanqi.tv/edmunddzhang'
[DEBUG] get_content: https://www.zhanqi.tv/api/static/v2.1/room/domain/edmunddzhang.json
Site:       www.zhanqi.tv
Title:      EdmundDZhang: 【老E】今晚可能休息？！
Type:       M3U8 Master m3u8
M3U8 Url:   http://dlhls.cdn.zhanqi.tv/zqlive/9469_lNZYA.m3u8

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://dlhls.cdn.zhanqi.tv/zqlive/9469_lNZYA.m3u8 -c copy -bsf:a aac_adtstoasc EdmundDZhang- 【老E】今晚可能休息？！.mp4
ffmpeg version 3.3.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, hls,applehttp, from 'http://dlhls.cdn.zhanqi.tv/zqlive/9469_lNZYA.m3u8':
  Duration: N/A, start: 3575.057333, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 10240
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709/bt709/iec61966-2-1), 1280x720, 45 tbr, 90k tbn, 2k tbc
    Metadata:
      variant_bitrate : 10240
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 10240
Output #0, mp4, to 'EdmundDZhang- 【老E】今晚可能休息？！.mp4':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(tv, bt709/bt709/iec61966-2-1), 1280x720, q=2-31, 45 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 10240
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 10240
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   19 fps=0.0 q=-1.0 size=     402kB time=00:00:00.53 bitrate=6206.8kbits/s speframe=   31 fps= 24 q=-1.0 size=     461kB time=00:00:00.79 bitrate=4735.2kbits/s speframe=   39 fps= 16 q=-1.0 size=     513kB time=00:00:00.97 bitrate=4309.5kbits/s spe
```

```
$ ./you-get -di 'https://www.zhanqi.tv/videos/zjyx/2017/06/207420.html'
[DEBUG] get_content: https://www.zhanqi.tv/api/static/v2.1/video/207420.json
[DEBUG] get_content: http://dlvod.cdn.zhanqi.tv/BjABYgE6WGsLMV0wBzQFaA1r_2017_06_27_BjMBYgE9WGwLNV02
Site:       www.zhanqi.tv
Title:      【老E】灵魂画师的艺术造纸！
Type:       M3U8 Playlist m3u8
```

### CODE REVIEW

**Comment by soimort** [comment]
Is there is reason to parse M3U in our code instead of calling `ffmpeg` directly?

**Comment by rosynirvana** [comment]
Someone does not have a ffmpeg binary on his ```PATH```  so it's better to parse the m3u8 in the python code. Video segments in ```ts``` container are trivial to concat.

For a live stream it's much more tricky(polling the URI of playlist) so using ffmpeg will involve less bugs.

**Comment by soimort** [comment]
I don't know about Zhanqi, so you can merge this if it fixes relevant issues.

The official MIME type for "M3U8 Master" is `application/vnd.apple.mpegurl`, other M3U8 playlists can be `application/mpegurl` (so you don't need to pass an extra argument). Otherwise it's fine.

**Comment by rosynirvana** [comment]
In apple's document it's advised to use ```application/vnd.apple.mpegurl``` or ```application/x-mpegurl```
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/DeployingHTTPLiveStreaming/DeployingHTTPLiveStreaming.html

I'm not sure what does it mean but it seems master or playlist cannot be telled from the ```Content-Type```

Zhanqi use ```application/x-mpegurl``` for both master and playlist
```
curl http://dlhls.cdn.zhanqi.tv/zqlive/300_lemHa.m3u8 -I
HTTP/1.1 200 OK
Server: DnionOS/1.11.2.1.10
Date: Sat, 22 Jul 2017 10:53:00 GMT
Content-Type: application/x-mpegURL
```

```
curl 'http://dlhls.cdn.zhanqi.tv/zqlive/300_lemHa_480p/index.m3u8?Dnion_vsnae=300_lemHa&stream=300_lemHa_480p&application=zqlivehls&data_type=child_m3u8&process_slot=0&suffix=_480p&original=300_lemHa' -I
HTTP/1.1 200 OK
Server: DnionOS/1.11.2.1.10
Date: Sat, 22 Jul 2017 10:52:42 GMT
Content-Type: application/x-mpegURL
```

So perhaps we need some tricks to tell ```print_info``` it's a master m3u8 or playlist, not necessarily a parameter.

**Pull request merged**
