### PR TITLE
Support ignore ssl when connecting through vpn by adding option -k

### PR DESCRIPTION
**Pull request by gaoxingliang**
**Problem:** 
When downloading a youtube video from VPN, it will fail because of ssl error:

`
you-get: Namespace(URL=['https://www.youtube.com/watch?v=JQDHz72OA3c&feature=youtu.be'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, in_secure=False, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
.....
....
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:` 

**Solution**
I added an option same with curl "-k"/ "--in-secure" to not verify the certs.

**Test**
Run with "-k --debug https://www.youtube.com/watch?v=JQDHz72OA3c&feature=youtu.be"
and the output is:
title:               URL shortener system design | tinyurl system design | bitly system design
stream:
    - itag:          22
      container:     mp4
      quality:       hd720
      size:          221.4 MiB (232157178 bytes)
    # download-with: you-get --itag=22 [URL]

Downloading URL shortener system design - tinyurl system design - bitly system design.mp4 ...
99.8% (221.0/221.4MB) ├████████████████████████████████████████┤[1/1]  756 kB/s99.9% (221.2/221.4MB) ├████████████████████████████████████████┤[1/1]    2 MB/s 100% (221.4/221.4MB) ├████████████████████████████████████████┤[1/1]    2 MB/s

Saving URL shortener system design - tinyurl system design - bitly system design.en.srt ... Done.

### CODE REVIEW

**Comment by gaoxingliang** [comment]
@soimort Please help to review this PR and any comments please let me know

**Comment by soimort** [comment]
Thanks for the PR. It looks good in general, but could you please `s/in_secure/insecure/g`?

"insecure" is a standalone word; the meaning of "in secure" is quite the opposite, which misleads users to think "it is secure", while it is not.

**Comment by gaoxingliang** [comment]
Thanks @soimort  it's fixed

**Comment by soimort** [comment]
Nice. Thanks!

**Comment by Cathy-t** [comment]
Sorry to bother you.I meet some problems recently:
___________________________________________________________________________________________________________
1:you-get https://www.youtube.com/watch?v=cJEHBnJgnf0 -o /cJEHBnJgnf0 --debug
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=cJEHBnJgnf0&eurl=https%3A%2F%2Fy
[DEBUG] STATUS: ok
you-get: version 0.4.1388, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=cJEHBnJgnf0'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=
False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=F
alse, no_proxy=False, output_dir='cJEHBnJgnf0', output_filename='cJEHBnJgnf0', password=None, player=None, playlist=False,
 skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "\venv\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.1388', 'console_scripts', 'you-get')()
  File "\venv\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1766, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1654, in script_main
    **extra
  File "\venv\lib\site-packages\you_get\common.py", line 1310, in download_main
    download(url, **kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1757, in any_download
    m.download(url, **kwargs)
  File "\venv\lib\site-packages\you_get\extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "\venv\lib\site-packages\you_get\extractors\youtube.py", line 213, in prepare
    self.title = parse.unquote_plus(json.loads(video_info["player_response"][0])["videoDetails"]["title"])
KeyError: 'videoDetails'
__________________________________________________________________________________________________________
2:you-get: Namespace(URL=['https://www.youtube.com/watch?v=QOYJmWzXmRc'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=
False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=F
alse, no_proxy=False, output_dir='QOYJmWzXmRc', output_filename=None, password=None, player=None, playlist=False, skip_exi
sting_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "\Python\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "\Python\Python37\lib\http\client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\venv\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.1388', 'console_scripts', 'you-get')()
  File "\venv\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1766, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1654, in script_main
    **extra
  File "e\venv\lib\site-packages\you_get\common.py", line 1310, in download_main
    download(url, **kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1757, in any_download
    m.download(url, **kwargs)
  File "\venv\lib\site-packages\you_get\extractor.py", line 61, in download_by_url
    self.download(**kwargs)
  File "\venv\lib\site-packages\you_get\extractor.py", line 241, in download
    av=stream_id in self.dash_streams)
  File "\venv\lib\site-packages\you_get\common.py", line 1003, in download_urls
    headers=headers, **kwargs
  File "\venv\lib\site-packages\you_get\common.py", line 724, in url_save
    request.Request(url, headers=tmp_headers)
  File "\venv\lib\site-packages\you_get\common.py", line 411, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "\Python\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "\Python\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

Can you help me ? Thanks.

**Comment by Cathy-t** [comment]
Sorry to bother you.I meet some problems recently:

1:you-get: Namespace(URL=['https://www.youtube.com/watch?v=QOYJmWzXmRc'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=
False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=F
alse, no_proxy=False, output_dir='QOYJmWzXmRc', output_filename=None, password=None, player=None, playlist=False, skip_exi
sting_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "\Python\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "\Python\Python37\lib\http\client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\venv\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.1388', 'console_scripts', 'you-get')()
  File "\venv\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1766, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1654, in script_main
    **extra
  File "e\venv\lib\site-packages\you_get\common.py", line 1310, in download_main
    download(url, **kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1757, in any_download
    m.download(url, **kwargs)
  File "\venv\lib\site-packages\you_get\extractor.py", line 61, in download_by_url
    self.download(**kwargs)
  File "\venv\lib\site-packages\you_get\extractor.py", line 241, in download
    av=stream_id in self.dash_streams)
  File "\venv\lib\site-packages\you_get\common.py", line 1003, in download_urls
    headers=headers, **kwargs
  File "\venv\lib\site-packages\you_get\common.py", line 724, in url_save
    request.Request(url, headers=tmp_headers)
  File "\venv\lib\site-packages\you_get\common.py", line 411, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "\Python\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "\Python\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

—————————————————————————————————————————
2：cmd: you-get https://www.youtube.com/watch?v=U3PzNp5bSPg -o /U3PzNp5bSPg --debug
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=U3PzNp5bSPg&eurl=https%3A%2F%2Fy
[DEBUG] STATUS: ok
[DEBUG] get_content: https://www.youtube.com/watch?v=U3PzNp5bSPg
you-get: version 0.4.1388, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=U3PzNp5bSPg'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='/U3PzNp5bSPg', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "\venv\lib\site-packages\you_get\extractors\youtube.py", line 217, in prepare
    ytplayer_config = json.loads(re.search('ytplayer.config\s*=\s*([^\n]+?});', video_page).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\venv\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.1388', 'console_scripts', 'you-get')()
  File "\venv\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1766, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1654, in script_main
    **extra
  File "\venv\lib\site-packages\you_get\common.py", line 1310, in download_main
    download(url, **kwargs)
  File "\venv\lib\site-packages\you_get\common.py", line 1757, in any_download
    m.download(url, **kwargs)
  File "\venv\lib\site-packages\you_get\extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "\venv\lib\site-packages\you_get\extractors\youtube.py", line 224, in prepare
    stream_list = json.loads(video_info['player_response'][0])['streamingData']['formats']
KeyError: 'streamingData'

Can you help me ? Thanks.

**Comment by caoshangua** [comment]
A similar issue also happened here.
I am also using **vpn**(shadowsocks) to download videos:
I can successfully download videos from https://www.bilibili.com, but failed from Youtube.

I checked the debug message, it seemed that, socket connection was wrong.

File "c:\program files\python37\lib\socket.py",

Can someone help?
Thank you.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Below is the Error Info:

PS D:\Temp> you-get --debug https://www.youtube.com/watch?v=3z49lWjCS_s
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=3z49lWjCS_s&eurl=https%3A%2F%2Fy
you-get: version 0.4.1403, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=3z49lWjCS_s'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "c:\program files\python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\program files\python37\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\program files\python37\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\program files\python37\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\program files\python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\program files\python37\lib\http\client.py", line 966, in send
    self.connect()
  File "c:\program files\python37\lib\http\client.py", line 1406, in connect
    super().connect()
  File "c:\program files\python37\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\program files\python37\lib\socket.py", line 727, in create_connection
    raise err
  File "c:\program files\python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\you-get.exe\__main__.py", line 7, in <module>
  File "c:\program files\python37\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\program files\python37\lib\site-packages\you_get\common.py", line 1766, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "c:\program files\python37\lib\site-packages\you_get\common.py", line 1654, in script_main
    **extra
  File "c:\program files\python37\lib\site-packages\you_get\common.py", line 1310, in download_main
    download(url, **kwargs)
  File "c:\program files\python37\lib\site-packages\you_get\common.py", line 1757, in any_download
    m.download(url, **kwargs)
  File "c:\program files\python37\lib\site-packages\you_get\extractor.py", line 48, in download_by_url
    self.prepare(**kwargs)
  File "c:\program files\python37\lib\site-packages\you_get\extractors\youtube.py", line 205, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}&eurl=https%3A%2F%2Fy'.format(self.vid)))
  File "c:\program files\python37\lib\site-packages\you_get\common.py", line 442, in get_content
    response = urlopen_with_retry(req)
  File "c:\program files\python37\lib\site-packages\you_get\common.py", line 411, in urlopen_with_retry
    return request.urlopen(*args, **kwargs)
  File "c:\program files\python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files\python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\program files\python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "c:\program files\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\program files\python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\program files\python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
PS D:\Temp>

**Comment by soimort** [comment]
> A similar issue also happened here.
> I am also using **vpn**(shadowsocks) to download videos:
> I can successfully download videos from https://www.bilibili.com, but failed from Youtube.
> 
> I checked the debug message, it seemed that, socket connection was wrong.
> 
> File "c:\program files\python37\lib\socket.py",
> 
> Can someone help?
> Thank you.
> 
> ```
> Below is the Error Info:
> 
> PS D:\Temp> you-get --debug https://www.youtube.com/watch?v=3z49lWjCS_s
> [DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=3z49lWjCS_s&eurl=https%3A%2F%2Fy
> you-get: version 0.4.1403, a tiny downloader that scrapes the web.
> you-get: Namespace(URL=['https://www.youtube.com/watch?v=3z49lWjCS_s'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
> Traceback (most recent call last):
>   File "c:\program files\python37\lib\urllib\request.py", line 1317, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "c:\program files\python37\lib\http\client.py", line 1244, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "c:\program files\python37\lib\http\client.py", line 1290, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "c:\program files\python37\lib\http\client.py", line 1239, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "c:\program files\python37\lib\http\client.py", line 1026, in _send_output
>     self.send(msg)
>   File "c:\program files\python37\lib\http\client.py", line 966, in send
>     self.connect()
>   File "c:\program files\python37\lib\http\client.py", line 1406, in connect
>     super().connect()
>   File "c:\program files\python37\lib\http\client.py", line 938, in connect
>     (self.host,self.port), self.timeout, self.source_address)
>   File "c:\program files\python37\lib\socket.py", line 727, in create_connection
>     raise err
>   File "c:\program files\python37\lib\socket.py", line 716, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Program Files\Python37\Scripts\you-get.exe\__main__.py", line 7, in <module>
>   File "c:\program files\python37\lib\site-packages\you_get\__main__.py", line 92, in main
>     main(**kwargs)
>   File "c:\program files\python37\lib\site-packages\you_get\common.py", line 1766, in main
>     script_main(any_download, any_download_playlist, **kwargs)
>   File "c:\program files\python37\lib\site-packages\you_get\common.py", line 1654, in script_main
>     **extra
>   File "c:\program files\python37\lib\site-packages\you_get\common.py", line 1310, in download_main
>     download(url, **kwargs)
>   File "c:\program files\python37\lib\site-packages\you_get\common.py", line 1757, in any_download
>     m.download(url, **kwargs)
>   File "c:\program files\python37\lib\site-packages\you_get\extractor.py", line 48, in download_by_url
>     self.prepare(**kwargs)
>   File "c:\program files\python37\lib\site-packages\you_get\extractors\youtube.py", line 205, in prepare
>     video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}&eurl=https%3A%2F%2Fy'.format(self.vid)))
>   File "c:\program files\python37\lib\site-packages\you_get\common.py", line 442, in get_content
>     response = urlopen_with_retry(req)
>   File "c:\program files\python37\lib\site-packages\you_get\common.py", line 411, in urlopen_with_retry
>     return request.urlopen(*args, **kwargs)
>   File "c:\program files\python37\lib\urllib\request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "c:\program files\python37\lib\urllib\request.py", line 525, in open
>     response = self._open(req, data)
>   File "c:\program files\python37\lib\urllib\request.py", line 543, in _open
>     '_open', req)
>   File "c:\program files\python37\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "c:\program files\python37\lib\urllib\request.py", line 1360, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "c:\program files\python37\lib\urllib\request.py", line 1319, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
> PS D:\Temp>
> ```

If you're using you-get through shadowsocks, make sure to add something like `-s 127.0.0.1:1080` (replace with your own ip address & port).

**Pull request merged**
