### PR TITLE
qq

### PR DESCRIPTION
**Pull request by Yohohaha**
**(PLEASE DELETE ALL THESE AFTER READING)**

Thank you for the pull request! `you-get` is a growing open source project, which would not have been possible without contributors like you.

Here are some simple rules to follow, please recheck them before sending the pull request:

- [ ] If you want to propose two or more unrelated patches, please open separate pull requests for them, instead of one;
- [ ] All pull requests should be based upon the latest `develop` branch;
- [ ] Name your branch (from which you will send the pull request) properly; use a meaningful name like `add-this-shining-feature` rather than just `develop`;
- [ ] All commit messages, as well as comments in code, should be written in understandable English.

As a contributor, you must be aware that

- [ ] You agree to contribute your code to this project, under the terms of the MIT license, so that any person may freely use or redistribute them; of course, you will still reserve the copyright for your own authorship.
- [ ] You may not contribute any code not authored by yourself, unless they are licensed under either public domain or the MIT license, literally.

Not all pull requests can eventually be merged. I consider merged / unmerged patches as equally important for the community: as long as you think a patch would be helpful, someone else might find it helpful, too, therefore they could take your fork and benefit in some way. In any case, I would like to thank you in advance for taking your time to contribute to this project.

Cheers,
Mort

**(PLEASE REPLACE ALL ABOVE WITH A DETAILED DESCRIPTION OF YOUR PULL REQUEST)**

汉语翻译最后日期：2016年02月26日

**(阅读后请删除所有内容)**

感谢您的pull request! `you-get`是稳健成长的开源项目，感谢您的贡献.

以下简单检查项目望您复查:

- [ ] 如果您预计提出两个或更多不相关补丁，请为每个使用不同的pull requests，而不是单一;
- [ ] 所有的pull requests应基于最新的`develop`分支;
- [ ] 您预计提出pull requests的分支应有有意义名称，例如`add-this-shining-feature`而不是`develop`;
- [ ] 所有的提交信息与代码中注释应使用可理解的英语.

作为贡献者，您需要知悉

- [ ] 您同意在MIT协议下贡献代码，以便任何人自由使用或分发;当然，你仍旧保留代码的著作权
- [ ] 你不得贡献非自己编写的代码，除非其属于公有领域或使用MIT协议.

不是所有的pull requests都会被合并,然而我认为合并/不合并的补丁一样重要：如果您认为补丁重要，其他人也有可能这么认为，那么他们可以从你的fork中提取工作并获益。无论如何，感谢您费心对本项目贡献.

祝好,
Mort

**(请将本内容完整替换为PULL REQUEST的详细内容)**

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1379)

### CODE REVIEW

**Comment by soimort** [comment]
Thanks for the pull request. Could you please give some more explanation on this PR? (e.g. What problem does it fix? Any URLs for testing, if applicable?)

**Comment by Yohohaha** [comment]
qq can't download this url "http://v.qq.com/x/page/j0322dvvhpq.html"; baomihua changed its messages returned, and we can't get the real download url, but after adding the param "devicetype=phone_app", we can get it.

**Comment by Yohohaha** [comment]
baomihua can download 180p videos, it can download 480p by adding this "&devicetype=phone_app".

**Comment by soimort** [comment]
Looks good :+1:. Please do separate commits for different changes in the future; also remember to rebase your branch.

**Comment by Yohohaha** [comment]
ok, thanks

**Pull request closed without merging**
