### PR TITLE
fix qq support

### PR DESCRIPTION
**Pull request by pikeszfish**
使用了@lvqier  https://github.com/lvqier/crawlers/blob/master/txsp/txsp.py 的算法来解析，将其从p2移植到p3

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/470)

### CODE REVIEW

**Comment by soimort** [comment]
@radaiming If you have any time, you might want to have a look at this fix for QQ support (since I'm not familiar with this part of code...)

@pikeszfish @lvqier 多谢。
暂时没有时间细看，不过那个特定的`User-Agent`是必须的吗？

**Comment by lvqier** [comment]
@soimort Sorry, 我随手取了自己电脑的 UA，没有尝试过其它的。

**Comment by radaiming** [comment]
@soimort I don't think I have enough time to do that, and it's not easy for me to understand some of his code since I'm new to coding. Not sure if we must set User-Agent, but it should be easy to test it.

**Comment by soimort** [comment]
@radaiming Sure, I just wanted to confirm if it is ok with you before I merge this, since this PR has overwritten most of your old code.
I'll test this myself later.

**Pull request merged**
