### PR TITLE
rewrit iqiyi using VideoExtractor class

### PR DESCRIPTION
**Pull request by zhangn1985**
Signed-off-by: Zhang Ning <zhangn1985@gmail.com>

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/630)

### CODE REVIEW

**Comment by soimort** [comment]
Doesn't look good to me.

```console
 you-get-develop git:(zhangn1985-for-upstream) ./you-get -i 'http://www.iqiyi.com/common/qplay.html?cnid=5&tvid=4087092609&vid=049fe2ee97bf72f4ef7c30b85ae2c251'
Traceback (most recent call last):
  File "./you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get-develop/src/you_get/__main__.py", line 91, in main
    main()
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1046, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 933, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 825, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1039, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractor.py", line 35, in download_by_url
    self.prepare(**kwargs)
  File "/home/soimort/Projects/you-get-develop/src/you_get/extractors/iqiyi.py", line 125, in prepare
    tvid = r1(r'data-player-tvid="([^"]+)"', html) or r1(r'tvid=([^&]+)', url)
NameError: name 'url' is not defined
```

The old code works fine.

**Comment by zhangn1985** [comment]
still has some issue http 405

**Comment by zhangn1985** [comment]
fixed and reopen

**Comment by soimort** [comment]
Looks fine to me. @jackyzy823

**Comment by jackyzy823** [comment]
awesome! thanks @zhangn1985

**Comment by soimort** [comment]
:shipit:

**Pull request merged**
