### PR TITLE
[Bilibili] add support for BVID

### PR DESCRIPTION
**Pull request by brainbush**
ref https://www.bilibili.com/blackboard/activity-BV-PC.html

### CODE REVIEW

**Comment by ZonaChen** [comment]
Yep,you-get cannot resolve the BVID of bilibili now.

**Comment by Ravenclaw-OIer** [comment]
Support it! you-get cannot work with bvid right now. ~~And the bvid really prevented me from scraping all videos :(~~

**Comment by eatenid** [comment]
Maybe we can convert BVID into AID with this API: 
https://api.bilibili.com/x/web-interface/archive/stat?bvid=

But it seems that the signature algorithm of some api has been changed,such as:"https://interface.bilibili.com/v2/playurl".

**Comment by FSpark** [comment]
Hope to support it quickly! Quite disappointed with BVID, it really wants to be the next Youtube:-(

**Comment by soimort** [comment]
Thanks :ok_hand:

**Comment by brainbush** [comment]
https://www.zhihu.com/question/381784377/answer/1099438784
另一种实现方式，应该可以在aid失效后作为替代方式

**Pull request merged**
