### PR TITLE
Tencent Video use best quality

### PR DESCRIPTION
**Pull request by sinofool**
Prefer 1080p and 720p if available

---
This change is [Reviewable](https://reviewable.io/reviews/soimort/you-get/1428)

### CODE REVIEW

**Comment by sinofool** [comment]
This work is based on discussions from @lamlam123tld3 and @zmwangx under Issue 1298

**Comment by sinofool** [comment]
Issue #1354 also related.

**Comment by sinofool** [comment]
Issue #1071 is related.

**Comment by sinofool** [comment]
This protentially be a workaround for issue #1395 
But this is not a fix. For 480p only videos, the issue may still exists.

**Comment by soimort** [comment]
Looks good. Thanks for the fix!

**Pull request merged**
