### PR TITLE
now get iqiyi enc key automatically

### PR DESCRIPTION
**Pull request by jackyzy823**
iQiyi changes it's swf version frequently,so enc key changes too.
So before downloading,get swf from video page and extract the key.

[Review on Reviewable](https://reviewable.io/reviews/soimort/you-get/523)

### CODE REVIEW

**Comment by PeterDing** [comment]
@jackyzy823 @soimort 
I has seen this commit, I alse write a script for [rg3/youtube-dl](https://github.com/rg3/youtube-dl) using your finding algorithms.
I commit to [this](https://github.com/rg3/youtube-dl/compare/master...PeterDing:iqiyi).
So, I ask the permission to create pull request for rg3/youtube-dl.

**Comment by yan12125** [comment]
Note: youtube-dl is released into public domain, so codes to enter it should be released into public domain, too.

**Comment by jackyzy823** [comment]
@PeterDing  feel free to use these codes.

**Comment by PeterDing** [comment]
@jackyzy823 Thank you.

**Comment by yan12125** [comment]
@jackyzy823 iQiyi codes are merged into youtube-dl now. Would you like to be listed as the original author of [iqiyi.py at youtube-dl](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/iqiyi.py)?

**Comment by jackyzy823** [comment]
it's ok,just under `jackyzy823` . New method is introduced in #543 ,anyone wants to merge this to youtube-dl?

**Pull request merged**
